namespace SourceGen.Ioc;

partial class IocSourceGenerator
{
    /// <summary>
    /// Generates the container source code output.
    /// </summary>
    private static void GenerateContainerOutput(
        in SourceProductionContext ctx,
        ContainerWithGroups containerWithGroups,
        string assemblyName,
        (string? RootNamespace, string? CustomIocName) msbuildProps,
        bool hasDIPackage)
    {
        var source = GenerateContainerSource(containerWithGroups, assemblyName, msbuildProps, hasDIPackage);
        var fileName = $"{containerWithGroups.Container.ClassName}.Container.g.cs";
        ctx.AddSource(fileName, source);
    }

    /// <summary>
    /// Generates the container source code.
    /// </summary>
    private static string GenerateContainerSource(
        ContainerWithGroups containerWithGroups,
        string assemblyName,
        (string? RootNamespace, string? CustomIocName) msbuildProps,
        bool hasDIPackage)
    {
        var writer = new SourceWriter();
        var container = containerWithGroups.Container;
        var groups = containerWithGroups.Groups;

        // Determine if IServiceProviderFactory should be generated
        // Only generate if ResolveIServiceCollection is true AND the DI package is referenced
        var canGenerateServiceProviderFactory = container.ResolveIServiceCollection && hasDIPackage;

        // Effective UseSwitchStatement: when there are imported modules, always use FrozenDictionary
        // because combining services from multiple sources requires dictionary-based lookup
        var effectiveUseSwitchStatement = container.UseSwitchStatement && container.ImportedModules.Length == 0;

        WriteContainerHeader(writer);
        WriteContainerNamespaceAndClass(writer, container, groups, canGenerateServiceProviderFactory, effectiveUseSwitchStatement);

        return writer.ToString();
    }

    /// <summary>
    /// Writes the auto-generated header and using directives.
    /// </summary>
    private static void WriteContainerHeader(SourceWriter writer)
    {
        writer.WriteLine("// <auto-generated/>");
        writer.WriteLine("#nullable enable");
        writer.WriteLine();
        writer.WriteLine("using System;");
        writer.WriteLine("using System.Collections.Frozen;");
        writer.WriteLine("using System.Collections.Generic;");
        writer.WriteLine("using System.Linq;");
        writer.WriteLine("using System.Threading;");
        writer.WriteLine("using System.Threading.Tasks;");
        writer.WriteLine("using Microsoft.Extensions.DependencyInjection;");
        writer.WriteLine("using SourceGen.Ioc;");
        writer.WriteLine();
    }

    /// <summary>
    /// Writes the namespace and class declaration with all implemented interfaces.
    /// </summary>
    private static void WriteContainerNamespaceAndClass(
        SourceWriter writer,
        ContainerModel container,
        ContainerRegistrationGroups groups,
        bool canGenerateServiceProviderFactory,
        bool effectiveUseSwitchStatement)
    {
        // Write namespace if not global
        bool hasNamespace = !string.IsNullOrEmpty(container.ContainerNamespace);
        if(hasNamespace)
        {
            writer.WriteLine($"namespace {container.ContainerNamespace};");
            writer.WriteLine();
        }

        // Get interface list
        var interfaces = GetContainerInterfaces(container, canGenerateServiceProviderFactory);

        // Write class declaration
        writer.WriteLine($"partial class {container.ClassName} : {string.Join(", ", interfaces)}");
        writer.WriteLine("{");
        writer.Indentation++;

        // Write fields
        WriteContainerFields(writer, container, groups, effectiveUseSwitchStatement);

        // Write constructors
        WriteContainerConstructors(writer, container, groups, effectiveUseSwitchStatement);

        // Write service resolver methods
        WriteServiceResolverMethods(writer, container, groups);

        // Write IServiceProvider implementation
        WriteIServiceProviderImplementation(writer, container, groups, effectiveUseSwitchStatement);

        // Write IKeyedServiceProvider implementation
        WriteIKeyedServiceProviderImplementation(writer, container, groups, effectiveUseSwitchStatement);

        // Write ISupportRequiredService implementation
        WriteISupportRequiredServiceImplementation(writer, container);

        // Write IServiceProviderIsService implementation
        WriteIServiceProviderIsServiceImplementation(writer, container, groups, effectiveUseSwitchStatement);

        // Write IServiceScopeFactory implementation
        WriteIServiceScopeFactoryImplementation(writer, container);

        // Write IIocContainer implementation
        WriteIIocContainerImplementation(writer, container, groups, effectiveUseSwitchStatement);

        // Write IServiceProviderFactory implementation (if DI package is available)
        if(canGenerateServiceProviderFactory)
        {
            WriteIServiceProviderFactoryImplementation(writer, container);
        }

        // Write Disposal implementation
        WriteDisposalImplementation(writer, container, groups);

        writer.Indentation--;
        writer.WriteLine("}");
    }

    private static readonly string[] _FixedContainerInterfaces = [
        "IServiceProvider",
        "IKeyedServiceProvider",
        "IServiceProviderIsService",
        "IServiceProviderIsKeyedService",
        "ISupportRequiredService",
        "IServiceScopeFactory",
        "IServiceScope",
        "IDisposable",
        "IAsyncDisposable"
    ];
    /// <summary>
    /// Builds the list of interfaces the container should implement.
    /// </summary>
    private static IEnumerable<string> GetContainerInterfaces(ContainerModel container, bool canGenerateServiceProviderFactory)
    {
        yield return $"IIocContainer<{container.ContainerTypeName}>";

        foreach(var i in _FixedContainerInterfaces)
            yield return i;

        if(canGenerateServiceProviderFactory)
            yield return "IServiceProviderFactory<IServiceCollection>";
    }

    /// <summary>
    /// Writes container fields (fallback provider, service storage, locks, etc.).
    /// </summary>
    private static void WriteContainerFields(
        SourceWriter writer,
        ContainerModel container,
        ContainerRegistrationGroups groups,
        bool effectiveUseSwitchStatement)
    {
        // Fallback provider field (only if ResolveIServiceCollection is enabled)
        if(container.ResolveIServiceCollection)
        {
            writer.WriteLine("private readonly IServiceProvider? _fallbackProvider;");
        }

        // Scope tracking
        writer.WriteLine("private readonly bool _isRootScope = true;");
        writer.WriteLine("private int _disposed;");
        writer.WriteLine();

        // Service resolver dictionary
        if(!effectiveUseSwitchStatement)
        {
            writer.WriteLine($"private readonly FrozenDictionary<(Type ServiceType, object Key), Func<{container.ContainerTypeName}, object>> _serviceResolvers;");
            writer.WriteLine();
        }

        // Imported module fields
        foreach(var module in container.ImportedModules)
        {
            var fieldName = GetModuleFieldName(module.Name);
            writer.WriteLine($"private readonly {module.Name} {fieldName};");
        }

        if(container.ImportedModules.Length > 0)
        {
            writer.WriteLine();
        }
    }

    /// <summary>
    /// Writes a service instance field and optional lock for a single registration.
    /// </summary>
    private static void WriteServiceInstanceField(
        SourceWriter writer,
        ServiceRegistrationModel reg,
        string fieldName,
        bool hasDecorators,
        bool hasInjectionMembers)
    {
        // When there are decorators, field type is ServiceType (interface), otherwise ImplementationType
        var typeName = hasDecorators ? reg.ServiceType.Name : reg.ImplementationType.Name;
        writer.WriteLine($"private {typeName}? {fieldName};");

        // Add lock for complex initialization (property/method injection or decorators)
        if(hasInjectionMembers || hasDecorators)
        {
            writer.WriteLine($"private readonly Lock {fieldName}Lock = new();");
        }
    }

    /// <summary>
    /// Writes container constructors.
    /// </summary>
    private static void WriteContainerConstructors(
        SourceWriter writer,
        ContainerModel container,
        ContainerRegistrationGroups groups,
        bool effectiveUseSwitchStatement)
    {
        writer.WriteLine("#region Constructors");
        writer.WriteLine();

        // Default constructor
        writer.WriteLine("/// <summary>");
        writer.WriteLine("/// Creates a new standalone container without external service provider fallback.");
        writer.WriteLine("/// </summary>");

        // Need fallback provider constructor if ResolveIServiceCollection is enabled
        var needsFallbackProvider = container.ResolveIServiceCollection;

        if(needsFallbackProvider)
        {
            writer.WriteLine($"public {container.ClassName}() : this((IServiceProvider?)null) {{ }}");
        }
        else
        {
            // Standalone mode - no fallback provider
            writer.WriteLine($"public {container.ClassName}()");
            writer.WriteLine("{");
            writer.Indentation++;
            WriteConstructorBody(writer, container, groups, hasParameter: false, effectiveUseSwitchStatement);
            writer.Indentation--;
            writer.WriteLine("}");
        }
        writer.WriteLine();

        // Constructor with fallback provider (if enabled)
        if(needsFallbackProvider)
        {
            writer.WriteLine("/// <summary>");
            writer.WriteLine("/// Creates a new container with optional fallback to external service provider.");
            writer.WriteLine("/// </summary>");
            writer.WriteLine("/// <param name=\"fallbackProvider\">Optional external service provider for unknown dependencies.</param>");
            writer.WriteLine($"public {container.ClassName}(IServiceProvider? fallbackProvider)");
            writer.WriteLine("{");
            writer.Indentation++;
            writer.WriteLine("_fallbackProvider = fallbackProvider;");
            WriteConstructorBody(writer, container, groups, hasParameter: true, effectiveUseSwitchStatement);
            writer.Indentation--;
            writer.WriteLine("}");
            writer.WriteLine();
        }

        // Private constructor for scoped instances
        writer.WriteLine($"private {container.ClassName}({container.ClassName} parent)");
        writer.WriteLine("{");
        writer.Indentation++;
        if(needsFallbackProvider)
        {
            writer.WriteLine("_fallbackProvider = parent._fallbackProvider;");
        }
        writer.WriteLine("_isRootScope = false;");

        // Copy singleton references from parent (already filtered for non-open-generics)
        foreach(var cached in groups.Singletons)
        {
            writer.WriteLine($"{cached.FieldName} = parent.{cached.FieldName};");
        }

        // Create scopes for imported modules (so their scoped services are properly isolated)
        foreach(var module in container.ImportedModules)
        {
            var fieldName = GetModuleFieldName(module.Name);
            writer.WriteLine($"{fieldName} = ({module.Name})parent.{fieldName}.CreateScope().ServiceProvider;");
        }

        // Because resolvers are static, they can be reused from parent
        if(!effectiveUseSwitchStatement)
        {
            writer.WriteLine("_serviceResolvers = parent._serviceResolvers;");
        }

        writer.Indentation--;
        writer.WriteLine("}");
        writer.WriteLine();

        writer.WriteLine("#endregion");
        writer.WriteLine();
    }

    /// <summary>
    /// Writes the constructor body for building the service resolver dictionary.
    /// </summary>
    private static void WriteConstructorBody(
        SourceWriter writer,
        ContainerModel container,
        ContainerRegistrationGroups groups,
        bool hasParameter,
        bool effectiveUseSwitchStatement)
    {
        // Initialize imported modules
        foreach(var module in container.ImportedModules)
        {
            var fieldName = GetModuleFieldName(module.Name);
            if(container.ResolveIServiceCollection && hasParameter)
            {
                writer.WriteLine($"{fieldName} = new {module.Name}(fallbackProvider);");
            }
            else
            {
                writer.WriteLine($"{fieldName} = new {module.Name}();");
            }
        }

        // Build FrozenDictionary
        if(!effectiveUseSwitchStatement)
        {
            writer.WriteLine();
            if(container.ImportedModules.Length > 0)
            {
                // Combine with imported modules - wrap module resolvers to pass the correct module instance
                var sb = new StringBuilder();
                sb.Append("_serviceResolvers = ");

                bool first = true;
                foreach(var module in container.ImportedModules)
                {
                    var fieldName = GetModuleFieldName(module.Name);
                    // Wrap each module's Services to call resolver with the module instance instead of this container
                    if(first)
                    {
                        sb.Append($"{fieldName}.Services.Select(static kvp => new KeyValuePair<(Type, object), Func<{container.ContainerTypeName}, object>>(kvp.Key, c => kvp.Value(c.{fieldName})))");
                        first = false;
                    }
                    else
                    {
                        sb.Append($".Concat({fieldName}.Services.Select(static kvp => new KeyValuePair<(Type, object), Func<{container.ContainerTypeName}, object>>(kvp.Key, c => kvp.Value(c.{fieldName}))))");
                    }
                }

                sb.Append(".Concat(_localServices).ToFrozenDictionary();");
                writer.WriteLine(sb.ToString());
            }
            else
            {
                writer.WriteLine("_serviceResolvers = _localServices.ToFrozenDictionary();");
            }
        }
    }

    /// <summary>
    /// Writes individual service resolver methods.
    /// </summary>
    private static void WriteServiceResolverMethods(
        SourceWriter writer,
        ContainerModel container,
        ContainerRegistrationGroups groups)
    {
        writer.WriteLine("#region Service Resolution");
        writer.WriteLine();

        var writtenMethods = new HashSet<string>();

        // All registrations are already filtered (no open generics)
        foreach(var cached in groups.Singletons)
        {
            if(!writtenMethods.Add(cached.ResolverMethodName))
                continue;
            WriteServiceResolverMethod(writer, container, cached);
            writer.WriteLine();
        }

        foreach(var cached in groups.Scoped)
        {
            if(!writtenMethods.Add(cached.ResolverMethodName))
                continue;
            WriteServiceResolverMethod(writer, container, cached);
            writer.WriteLine();
        }

        foreach(var cached in groups.Transients)
        {
            if(!writtenMethods.Add(cached.ResolverMethodName))
                continue;
            WriteServiceResolverMethod(writer, container, cached);
            writer.WriteLine();
        }

        // Write collection resolver methods for IEnumerable<T> support
        foreach(var serviceType in groups.CollectionServiceTypes)
        {
            WriteCollectionResolverMethod(writer, serviceType, groups);
            writer.WriteLine();
        }

        writer.WriteLine("#endregion");
        writer.WriteLine();
    }

    /// <summary>
    /// Writes a collection resolver method for IEnumerable&lt;T&gt; service resolution.
    /// </summary>
    private static void WriteCollectionResolverMethod(
        SourceWriter writer,
        string serviceType,
        ContainerRegistrationGroups groups)
    {
        var methodName = GetCollectionResolverMethodName(serviceType);
        var returnType = $"global::System.Collections.Generic.IEnumerable<{serviceType}>";

        // Use pre-computed collection registrations (already filtered for non-open-generics)
        if(!groups.CollectionRegistrations.TryGetValue(serviceType, out var registrations))
            return;

        writer.WriteLine($"private {returnType} {methodName}() =>");
        writer.Indentation++;
        writer.WriteLine("[");
        writer.Indentation++;

        foreach(var cached in registrations)
        {
            writer.WriteLine($"{cached.ResolverMethodName}(),");
        }

        writer.Indentation--;
        writer.WriteLine("];");
        writer.Indentation--;
    }

    /// <summary>
    /// Writes a single service resolver method.
    /// </summary>
    private static void WriteServiceResolverMethod(
        SourceWriter writer,
        ContainerModel container,
        CachedRegistration cached)
    {
        var reg = cached.Registration;
        var methodName = cached.ResolverMethodName;
        var fieldName = cached.FieldName;

        // Check if factory or instance registration
        bool hasFactory = reg.Factory is not null;
        bool hasInstance = reg.Instance is not null;
        bool hasInjectionMembers = reg.InjectionMembers.Length > 0;
        bool hasDecorators = reg.Decorators.Length > 0;

        // Return type: if there are decorators, return the ServiceType (interface), otherwise ImplementationType
        var returnType = hasDecorators ? reg.ServiceType.Name : reg.ImplementationType.Name;

        switch(reg.Lifetime)
        {
            case ServiceLifetime.Singleton:
            case ServiceLifetime.Scoped:
                // Write field and lock above the resolver method for better readability
                WriteServiceInstanceField(writer, reg, fieldName, hasDecorators, hasInjectionMembers);

                if(hasInjectionMembers || hasDecorators)
                {
                    WriteResolverMethodWithLock(writer, methodName, returnType, fieldName, reg, hasFactory, hasInstance, hasDecorators);
                }
                else
                {
                    WriteResolverMethodWithInterlocked(writer, methodName, returnType, fieldName, reg, hasFactory, hasInstance);
                }
                break;

            case ServiceLifetime.Transient:
                WriteTransientResolverMethod(writer, methodName, returnType, reg, hasFactory, hasInstance, hasDecorators);
                break;
        }
    }

    /// <summary>
    /// Writes resolver method using Interlocked.CompareExchange for thread safety.
    /// </summary>
    private static void WriteResolverMethodWithInterlocked(
        SourceWriter writer,
        string methodName,
        string returnType,
        string fieldName,
        ServiceRegistrationModel reg,
        bool hasFactory,
        bool hasInstance)
    {
        writer.WriteLine($"private {returnType} {methodName}()");
        writer.WriteLine("{");
        writer.Indentation++;

        writer.WriteLine($"if({fieldName} is not null) return {fieldName};");
        writer.WriteLine();

        // Create instance
        WriteInstanceCreation(writer, "instance", reg, hasFactory, hasInstance);
        writer.WriteLine();

        writer.WriteLine($"return Interlocked.CompareExchange(ref {fieldName}, instance, null) ?? instance;");

        writer.Indentation--;
        writer.WriteLine("}");
    }

    /// <summary>
    /// Writes resolver method using lock for complex initialization.
    /// </summary>
    private static void WriteResolverMethodWithLock(
        SourceWriter writer,
        string methodName,
        string returnType,
        string fieldName,
        ServiceRegistrationModel reg,
        bool hasFactory,
        bool hasInstance,
        bool hasDecorators)
    {
        writer.WriteLine($"private {returnType} {methodName}()");
        writer.WriteLine("{");
        writer.Indentation++;

        writer.WriteLine($"if({fieldName} is not null) return {fieldName};");
        writer.WriteLine();

        writer.WriteLine($"lock({fieldName}Lock)");
        writer.WriteLine("{");
        writer.Indentation++;

        writer.WriteLine($"if({fieldName} is not null) return {fieldName};");
        writer.WriteLine();

        // Create instance with injection
        // When decorators are present, use ServiceType for variable declaration
        var variableType = hasDecorators ? reg.ServiceType.Name : null;
        WriteInstanceCreationWithInjection(writer, "instance", reg, hasFactory, hasInstance, variableType);

        // Apply decorators if any
        if(hasDecorators)
        {
            writer.WriteLine();
            WriteDecoratorApplication(writer, "instance", reg);
        }

        writer.WriteLine();

        writer.WriteLine($"{fieldName} = instance;");
        writer.WriteLine("return instance;");

        writer.Indentation--;
        writer.WriteLine("}");

        writer.Indentation--;
        writer.WriteLine("}");
    }

    /// <summary>
    /// Writes transient resolver method (creates new instance each time).
    /// </summary>
    private static void WriteTransientResolverMethod(
        SourceWriter writer,
        string methodName,
        string returnType,
        ServiceRegistrationModel reg,
        bool hasFactory,
        bool hasInstance,
        bool hasDecorators)
    {
        writer.WriteLine($"private {returnType} {methodName}()");
        writer.WriteLine("{");
        writer.Indentation++;

        if(reg.InjectionMembers.Length > 0 || hasDecorators)
        {
            // When decorators are present, use ServiceType for variable declaration
            var variableType = hasDecorators ? reg.ServiceType.Name : null;
            WriteInstanceCreationWithInjection(writer, "instance", reg, hasFactory, hasInstance, variableType);

            // Apply decorators if any
            if(hasDecorators)
            {
                writer.WriteLine();
                WriteDecoratorApplication(writer, "instance", reg);
            }

            writer.WriteLine("return instance;");
        }
        else
        {
            var instanceCreation = BuildInstanceCreationInline(reg, hasFactory, hasInstance);
            writer.WriteLine($"return {instanceCreation};");
        }

        writer.Indentation--;
        writer.WriteLine("}");
    }

    /// <summary>
    /// Writes instance creation code.
    /// </summary>
    private static void WriteInstanceCreation(
        SourceWriter writer,
        string varName,
        ServiceRegistrationModel reg,
        bool hasFactory,
        bool hasInstance)
    {
        if(hasInstance)
        {
            writer.WriteLine($"var {varName} = {reg.Instance};");
            return;
        }

        if(hasFactory)
        {
            var factory = reg.Factory!;
            var factoryCall = BuildFactoryCallForContainer(factory, reg);
            // Cast to implementation type if factory returns a different type
            writer.WriteLine($"var {varName} = ({reg.ImplementationType.Name}){factoryCall};");
            return;
        }

        // Constructor invocation
        var args = BuildConstructorArgumentsString(reg);
        writer.WriteLine($"var {varName} = new {reg.ImplementationType.Name}({args});");
    }

    /// <summary>
    /// Writes instance creation with property/method injection.
    /// </summary>
    /// <param name="variableType">Optional explicit type for the variable. When null, 'var' is used.</param>
    private static void WriteInstanceCreationWithInjection(
        SourceWriter writer,
        string varName,
        ServiceRegistrationModel reg,
        bool hasFactory,
        bool hasInstance,
        string? variableType = null)
    {
        // Use explicit type when provided (for decorator scenarios), otherwise use 'var'
        var typeDeclaration = variableType ?? "var";

        if(hasInstance)
        {
            writer.WriteLine($"{typeDeclaration} {varName} = {reg.Instance};");
        }
        else if(hasFactory)
        {
            var factory = reg.Factory!;
            var factoryCall = BuildFactoryCallForContainer(factory, reg);
            // Cast to implementation type if factory returns a different type
            writer.WriteLine($"{typeDeclaration} {varName} = ({reg.ImplementationType.Name}){factoryCall};");
        }
        else
        {
            // Single-pass categorization of injection members to avoid multiple iterations
            List<InjectionMemberData>? properties = null;
            List<InjectionMemberData>? methods = null;

            foreach(var member in reg.InjectionMembers)
            {
                if(member.MemberType is InjectionMemberType.Property or InjectionMemberType.Field)
                {
                    properties ??= [];
                    properties.Add(member);
                }
                else if(member.MemberType == InjectionMemberType.Method)
                {
                    methods ??= [];
                    methods.Add(member);
                }
            }

            var args = BuildConstructorArgumentsString(reg);

            if(properties is { Count: > 0 })
            {
                writer.WriteLine($"{typeDeclaration} {varName} = new {reg.ImplementationType.Name}({args})");
                writer.WriteLine("{");
                writer.Indentation++;

                foreach(var prop in properties)
                {
                    var resolveCall = BuildServiceResolutionCallForContainer(prop.Type!, prop.Key, prop.IsNullable);
                    writer.WriteLine($"{prop.Name} = {resolveCall},");
                }

                writer.Indentation--;
                writer.WriteLine("};");
            }
            else
            {
                writer.WriteLine($"{typeDeclaration} {varName} = new {reg.ImplementationType.Name}({args});");
            }

            // Method injection
            if(methods is not null)
            {
                foreach(var method in methods)
                {
                    var methodArgs = "";
                    if(method.Parameters is { Length: > 0 })
                    {
                        var argsList = method.Parameters.Select(p => BuildParameterForContainer(p, reg));
                        methodArgs = string.Join(", ", argsList);
                    }
                    writer.WriteLine($"{varName}.{method.Name}({methodArgs});");
                }
            }
        }
    }

    /// <summary>
    /// Writes decorator application code.
    /// Decorators are applied in reverse order (from innermost to outermost),
    /// matching the behavior of Register mode.
    /// </summary>
    private static void WriteDecoratorApplication(
        SourceWriter writer,
        string varName,
        ServiceRegistrationModel reg)
    {
        // Decorators array is in order from outermost to innermost,
        // we iterate in reverse order for building the chain from inner to outer
        var decorators = reg.Decorators;
        for(int i = decorators.Length - 1; i >= 0; i--)
        {
            var decorator = decorators[i];
            // Build decorator constructor arguments
            // First parameter is always the inner instance (the decorated service)
            var decoratorArgs = new List<string> { varName };

            // Add other constructor parameters (dependency injection)
            if(decorator.ConstructorParameters is { Length: > 1 })
            {
                // Skip the first parameter (it's the inner/decorated service)
                foreach(var param in decorator.ConstructorParameters.Skip(1))
                {
                    var resolveCall = BuildServiceResolutionCallForContainer(param.Type, param.ServiceKey, param.IsNullable);
                    decoratorArgs.Add(resolveCall);
                }
            }

            var argsString = string.Join(", ", decoratorArgs);
            writer.WriteLine($"{varName} = new {decorator.Name}({argsString});");
        }
    }

    /// <summary>
    /// Builds instance creation inline (for return statements).
    /// </summary>
    private static string BuildInstanceCreationInline(
        ServiceRegistrationModel reg,
        bool hasFactory,
        bool hasInstance)
    {
        if(hasInstance)
        {
            return reg.Instance!;
        }

        if(hasFactory)
        {
            var factory = reg.Factory!;
            var factoryCall = BuildFactoryCallForContainer(factory, reg);
            // Cast to implementation type if factory returns a different type
            return $"({reg.ImplementationType.Name}){factoryCall}";
        }

        var args = BuildConstructorArgumentsString(reg);
        return $"new {reg.ImplementationType.Name}({args})";
    }

    /// <summary>
    /// Builds constructor arguments as a string.
    /// </summary>
    private static string BuildConstructorArgumentsString(ServiceRegistrationModel reg)
    {
        var parameters = reg.ImplementationType.ConstructorParameters;
        if(parameters is null or { Length: 0 })
            return "";

        var args = new List<string>();
        foreach(var param in parameters)
        {
            args.Add(BuildParameterForContainer(param, reg));
        }

        return string.Join(", ", args);
    }

    /// <summary>
    /// Builds a single parameter for container (constructor, method injection, or factory).
    /// Handles [ServiceKey], IServiceProvider, and regular service resolution.
    /// </summary>
    private static string BuildParameterForContainer(ParameterData param, ServiceRegistrationModel reg)
    {
        if(param.HasServiceKeyAttribute)
        {
            // Inject the registration key
            return reg.Key ?? "null";
        }

        if(param.Type.Name == "System.IServiceProvider" || param.Type.Name == "global::System.IServiceProvider")
        {
            return "this";
        }

        var key = param.ServiceKey ?? (param.HasFromKeyedServicesAttribute ? param.ServiceKey : null);
        return BuildServiceResolutionCallForContainer(param.Type, key, param.IsOptional);
    }

    /// <summary>
    /// Builds a factory method call string for container.
    /// </summary>
    private static string BuildFactoryCallForContainer(FactoryMethodData factory, ServiceRegistrationModel reg)
    {
        var args = new List<string>();

        if(factory.HasServiceProvider)
        {
            args.Add("this");
        }

        if(factory.HasKey && reg.Key is not null)
        {
            args.Add(reg.Key);
        }

        foreach(var param in factory.AdditionalParameters)
        {
            args.Add(BuildParameterForContainer(param, reg));
        }

        // Handle generic factory methods with [IocGenericFactory] attribute
        var genericTypeArgs = BuildGenericFactoryTypeArgs(factory, reg.ServiceType);
        var factoryCallPath = genericTypeArgs is not null ? $"{factory.Path}<{genericTypeArgs}>" : factory.Path;

        return $"{factoryCallPath}({string.Join(", ", args)})";
    }

    /// <summary>
    /// Builds a service resolution call for container (GetService, GetRequiredService, etc.).
    /// </summary>
    private static string BuildServiceResolutionCallForContainer(TypeData type, string? key, bool isOptional)
    {
        // Collection types
        if(type.CollectionKind != CollectionKind.None)
        {
            var elementType = ExtractElementTypeForContainer(type);
            if(key is not null)
            {
                return $"GetKeyedServices<{elementType}>({key})";
            }
            return $"GetServices<{elementType}>()";
        }

        // Keyed services
        if(key is not null)
        {
            if(isOptional)
            {
                return $"GetKeyedService(typeof({type.Name}), {key}) as {type.Name}";
            }
            return $"({type.Name})GetRequiredKeyedService(typeof({type.Name}), {key})";
        }

        // Regular services
        if(isOptional)
        {
            return $"GetService(typeof({type.Name})) as {type.Name}";
        }
        return $"({type.Name})GetRequiredService(typeof({type.Name}))";
    }

    /// <summary>
    /// Extracts the element type from a collection type using pre-computed TypeParameters.
    /// </summary>
    private static string ExtractElementTypeForContainer(TypeData type)
    {
        // Use TypeParameters for efficient element type extraction
        if(type.TypeParameters is { Length: > 0 })
        {
            return type.TypeParameters[0].Type.Name;
        }
        return "object";
    }

    /// <summary>
    /// Writes IServiceProvider implementation.
    /// </summary>
    private static void WriteIServiceProviderImplementation(
        SourceWriter writer,
        ContainerModel container,
        ContainerRegistrationGroups groups,
        bool effectiveUseSwitchStatement)
    {
        writer.WriteLine("#region IServiceProvider");
        writer.WriteLine();

        writer.WriteLine("public object? GetService(Type serviceType)");
        writer.WriteLine("{");
        writer.Indentation++;

        // Built-in services
        writer.WriteLine("if(serviceType == typeof(IServiceProvider)) return this;");
        writer.WriteLine("if(serviceType == typeof(IServiceScopeFactory)) return this;");
        writer.WriteLine($"if(serviceType == typeof({container.ClassName})) return this;");
        writer.WriteLine();

        if(effectiveUseSwitchStatement)
        {
            // Cascading if statements - registrations already filtered (no open generics)
            foreach(var kvp in groups.ByServiceTypeAndKey)
            {
                if(kvp.Key.Key is not null)
                    continue;

                var cached = kvp.Value[^1]; // Last wins
                var reg = cached.Registration;
                writer.WriteLine($"if(serviceType == typeof({reg.ServiceType.Name})) return {cached.ResolverMethodName}();");
            }

            writer.WriteLine();
        }
        else
        {
            writer.WriteLine("if(_serviceResolvers.TryGetValue((serviceType, global::Microsoft.Extensions.DependencyInjection.KeyedService.AnyKey), out var resolver))");
            writer.Indentation++;
            writer.WriteLine("return resolver(this);");
            writer.Indentation--;
            writer.WriteLine();
        }

        // Fallback
        if(container.ResolveIServiceCollection)
        {
            writer.WriteLine("return _fallbackProvider?.GetService(serviceType);");
        }
        else
        {
            writer.WriteLine("return null;");
        }

        writer.Indentation--;
        writer.WriteLine("}");
        writer.WriteLine();

        writer.WriteLine("#endregion");
        writer.WriteLine();
    }

    /// <summary>
    /// Writes IKeyedServiceProvider implementation.
    /// </summary>
    private static void WriteIKeyedServiceProviderImplementation(
        SourceWriter writer,
        ContainerModel container,
        ContainerRegistrationGroups groups,
        bool effectiveUseSwitchStatement)
    {
        writer.WriteLine("#region IKeyedServiceProvider");
        writer.WriteLine();

        writer.WriteLine("public object? GetKeyedService(Type serviceType, object? serviceKey)");
        writer.WriteLine("{");
        writer.Indentation++;

        writer.WriteLine("var key = serviceKey ?? global::Microsoft.Extensions.DependencyInjection.KeyedService.AnyKey;");
        writer.WriteLine();

        if(effectiveUseSwitchStatement)
        {
            // Use pre-computed hasKeyedServices flag
            if(groups.HasKeyedServices)
            {
                // Use tuple pattern matching switch expression
                writer.WriteLine("return (serviceType, key) switch");
                writer.WriteLine("{");
                writer.Indentation++;

                foreach(var kvp in groups.ByServiceTypeAndKey)
                {
                    if(kvp.Key.Key is null)
                        continue;

                    var cached = kvp.Value[^1]; // Last wins
                    writer.WriteLine($"(Type t, object k) when t == typeof({kvp.Key.ServiceType}) && Equals(k, {kvp.Key.Key}) => {cached.ResolverMethodName}(),");
                }

                // Fallback in switch default case
                if(container.ResolveIServiceCollection)
                {
                    writer.WriteLine("_ => _fallbackProvider is IKeyedServiceProvider keyed ? keyed.GetKeyedService(serviceType, serviceKey) : null");
                }
                else
                {
                    writer.WriteLine("_ => null");
                }

                writer.Indentation--;
                writer.WriteLine("};");
            }
            else
            {
                // No keyed services, just return fallback
                if(container.ResolveIServiceCollection)
                {
                    writer.WriteLine("return _fallbackProvider is IKeyedServiceProvider keyed ? keyed.GetKeyedService(serviceType, serviceKey) : null;");
                }
                else
                {
                    writer.WriteLine("return null;");
                }
            }
        }
        else
        {
            writer.WriteLine("if(_serviceResolvers.TryGetValue((serviceType, key), out var resolver))");
            writer.Indentation++;
            writer.WriteLine("return resolver(this);");
            writer.Indentation--;
            writer.WriteLine();

            // Fallback
            if(container.ResolveIServiceCollection)
            {
                writer.WriteLine("return _fallbackProvider is IKeyedServiceProvider keyed ? keyed.GetKeyedService(serviceType, serviceKey) : null;");
            }
            else
            {
                writer.WriteLine("return null;");
            }
        }

        writer.Indentation--;
        writer.WriteLine("}");
        writer.WriteLine();

        // GetRequiredKeyedService
        writer.WriteLine("public object GetRequiredKeyedService(Type serviceType, object? serviceKey)");
        writer.WriteLine("{");
        writer.Indentation++;
        writer.WriteLine("return GetKeyedService(serviceType, serviceKey) ?? throw new InvalidOperationException($\"No service for type '{serviceType}' with key '{serviceKey}' has been registered.\");");
        writer.Indentation--;
        writer.WriteLine("}");
        writer.WriteLine();

        writer.WriteLine("#endregion");
        writer.WriteLine();
    }

    /// <summary>
    /// Writes ISupportRequiredService implementation.
    /// </summary>
    private static void WriteISupportRequiredServiceImplementation(SourceWriter writer, ContainerModel container)
    {
        writer.WriteLine("#region ISupportRequiredService");
        writer.WriteLine();

        writer.WriteLine("public object GetRequiredService(Type serviceType)");
        writer.WriteLine("{");
        writer.Indentation++;
        writer.WriteLine("return GetService(serviceType) ?? throw new InvalidOperationException($\"No service for type '{serviceType}' has been registered.\");");
        writer.Indentation--;
        writer.WriteLine("}");
        writer.WriteLine();

        writer.WriteLine("#endregion");
        writer.WriteLine();
    }

    /// <summary>
    /// Writes IServiceProviderIsService implementation.
    /// </summary>
    private static void WriteIServiceProviderIsServiceImplementation(
        SourceWriter writer,
        ContainerModel container,
        ContainerRegistrationGroups groups,
        bool effectiveUseSwitchStatement)
    {
        writer.WriteLine("#region IServiceProviderIsService");
        writer.WriteLine();

        // IsService
        writer.WriteLine("public bool IsService(Type serviceType)");
        writer.WriteLine("{");
        writer.Indentation++;

        writer.WriteLine("if(serviceType == typeof(IServiceProvider)) return true;");
        writer.WriteLine("if(serviceType == typeof(IServiceScopeFactory)) return true;");
        writer.WriteLine($"if(serviceType == typeof({container.ClassName})) return true;");
        writer.WriteLine();

        if(effectiveUseSwitchStatement)
        {
            foreach(var serviceType in groups.AllServiceTypes)
            {
                writer.WriteLine($"if(serviceType == typeof({serviceType})) return true;");
            }
            writer.WriteLine();
        }
        else
        {
            writer.WriteLine("if(_serviceResolvers.ContainsKey((serviceType, global::Microsoft.Extensions.DependencyInjection.KeyedService.AnyKey))) return true;");
            writer.WriteLine();
        }

        if(container.ResolveIServiceCollection)
        {
            writer.WriteLine("return _fallbackProvider is IServiceProviderIsService isService && isService.IsService(serviceType);");
        }
        else
        {
            writer.WriteLine("return false;");
        }

        writer.Indentation--;
        writer.WriteLine("}");
        writer.WriteLine();

        // IsKeyedService
        writer.WriteLine("public bool IsKeyedService(Type serviceType, object? serviceKey)");
        writer.WriteLine("{");
        writer.Indentation++;

        writer.WriteLine("var key = serviceKey ?? global::Microsoft.Extensions.DependencyInjection.KeyedService.AnyKey;");

        if(!effectiveUseSwitchStatement)
        {
            writer.WriteLine();
            writer.WriteLine("if(_serviceResolvers.ContainsKey((serviceType, key))) return true;");
        }

        writer.WriteLine();

        if(container.ResolveIServiceCollection)
        {
            writer.WriteLine("return _fallbackProvider is IServiceProviderIsKeyedService isKeyed && isKeyed.IsKeyedService(serviceType, serviceKey);");
        }
        else
        {
            writer.WriteLine("return false;");
        }

        writer.Indentation--;
        writer.WriteLine("}");
        writer.WriteLine();

        writer.WriteLine("#endregion");
        writer.WriteLine();
    }

    /// <summary>
    /// Writes IServiceScopeFactory implementation.
    /// </summary>
    private static void WriteIServiceScopeFactoryImplementation(SourceWriter writer, ContainerModel container)
    {
        writer.WriteLine("#region IServiceScopeFactory");
        writer.WriteLine();

        writer.WriteLine($"public IServiceScope CreateScope() => new {container.ClassName}(this);");
        writer.WriteLine();
        writer.WriteLine("public AsyncServiceScope CreateAsyncScope() => new(CreateScope());");
        writer.WriteLine();
        writer.WriteLine("IServiceProvider IServiceScope.ServiceProvider => this;");
        writer.WriteLine();

        writer.WriteLine("#endregion");
        writer.WriteLine();
    }

    /// <summary>
    /// Writes IIocContainer implementation.
    /// </summary>
    private static void WriteIIocContainerImplementation(
        SourceWriter writer,
        ContainerModel container,
        ContainerRegistrationGroups groups,
        bool effectiveUseSwitchStatement)
    {
        writer.WriteLine("#region IIocContainer");
        writer.WriteLine();

        if(effectiveUseSwitchStatement)
        {
            writer.WriteLine($"public IReadOnlyCollection<KeyValuePair<(Type ServiceType, object Key), Func<{container.ContainerTypeName}, object>>> Services => _localServices;");
        }
        else
        {
            writer.WriteLine($"public IReadOnlyCollection<KeyValuePair<(Type ServiceType, object Key), Func<{container.ContainerTypeName}, object>>> Services => _serviceResolvers;");
        }
        writer.WriteLine();

        // Write _localServices as static field
        writer.WriteLine($"private static readonly KeyValuePair<(Type, object), Func<{container.ContainerTypeName}, object>>[] _localServices =");
        writer.WriteLine("[");
        writer.Indentation++;

        // Use ByServiceTypeAndKey to include all service types (already filtered for non-open-generics)
        foreach(var kvp in groups.ByServiceTypeAndKey)
        {
            var cached = kvp.Value[^1]; // Last wins
            var keyExpr = kvp.Key.Key ?? "global::Microsoft.Extensions.DependencyInjection.KeyedService.AnyKey";
            writer.WriteLine($"new((typeof({kvp.Key.ServiceType}), {keyExpr}), static c => c.{cached.ResolverMethodName}()),");
        }

        // Add IEnumerable<T> entries for collection service types
        foreach(var serviceType in groups.CollectionServiceTypes)
        {
            var methodName = GetCollectionResolverMethodName(serviceType);
            writer.WriteLine($"new((typeof(global::System.Collections.Generic.IEnumerable<{serviceType}>), global::Microsoft.Extensions.DependencyInjection.KeyedService.AnyKey), static c => c.{methodName}()),");
        }

        writer.Indentation--;
        writer.WriteLine("];");

        writer.WriteLine();
        writer.WriteLine("#endregion");
        writer.WriteLine();
    }

    /// <summary>
    /// Writes IServiceProviderFactory implementation.
    /// </summary>
    private static void WriteIServiceProviderFactoryImplementation(SourceWriter writer, ContainerModel container)
    {
        writer.WriteLine("#region IServiceProviderFactory<IServiceCollection>");
        writer.WriteLine();

        writer.WriteLine("/// <summary>");
        writer.WriteLine("/// Creates a new container builder (returns the same IServiceCollection).");
        writer.WriteLine("/// </summary>");
        writer.WriteLine("public IServiceCollection CreateBuilder(IServiceCollection services) => services;");
        writer.WriteLine();

        writer.WriteLine("/// <summary>");
        writer.WriteLine("/// Creates the service provider from the built IServiceCollection.");
        writer.WriteLine("/// </summary>");
        writer.WriteLine("public IServiceProvider CreateServiceProvider(IServiceCollection containerBuilder)");
        writer.WriteLine("{");
        writer.Indentation++;
        writer.WriteLine("var fallbackProvider = containerBuilder.BuildServiceProvider();");
        writer.WriteLine($"return new {container.ClassName}(fallbackProvider);");
        writer.Indentation--;
        writer.WriteLine("}");
        writer.WriteLine();

        writer.WriteLine("#endregion");
        writer.WriteLine();
    }

    /// <summary>
    /// Writes Disposal implementation (IDisposable and IAsyncDisposable).
    /// </summary>
    private static void WriteDisposalImplementation(
        SourceWriter writer,
        ContainerModel container,
        ContainerRegistrationGroups groups)
    {
        writer.WriteLine("#region Disposal");
        writer.WriteLine();

        // IDisposable.Dispose
        writer.WriteLine("public void Dispose()");
        writer.WriteLine("{");
        writer.Indentation++;

        writer.WriteLine("if(Interlocked.Exchange(ref _disposed, 1) != 0) return;");
        writer.WriteLine();

        // Dispose scoped services if this is a scope
        writer.WriteLine("if(!_isRootScope)");
        writer.WriteLine("{");
        writer.Indentation++;

        // Use pre-computed reversed list for disposal
        foreach(var cached in groups.ReversedScopedForDisposal)
        {
            writer.WriteLine($"DisposeService({cached.FieldName});");
        }

        // Dispose imported module scopes (child scopes have their own module scopes)
        foreach(var module in container.ImportedModules)
        {
            var fieldName = GetModuleFieldName(module.Name);
            writer.WriteLine($"{fieldName}.Dispose();");
        }

        writer.WriteLine("return;");

        writer.Indentation--;
        writer.WriteLine("}");
        writer.WriteLine();

        // Use pre-computed reversed list for disposal
        foreach(var cached in groups.ReversedSingletonsForDisposal)
        {
            writer.WriteLine($"DisposeService({cached.FieldName});");
        }

        // Dispose imported modules (root scope)
        foreach(var module in container.ImportedModules)
        {
            var fieldName = GetModuleFieldName(module.Name);
            writer.WriteLine($"{fieldName}.Dispose();");
        }

        writer.Indentation--;
        writer.WriteLine("}");
        writer.WriteLine();

        // IAsyncDisposable.DisposeAsync
        writer.WriteLine("public async ValueTask DisposeAsync()");
        writer.WriteLine("{");
        writer.Indentation++;

        writer.WriteLine("if(Interlocked.Exchange(ref _disposed, 1) != 0) return;");
        writer.WriteLine();

        // Dispose scoped services if this is a scope
        writer.WriteLine("if(!_isRootScope)");
        writer.WriteLine("{");
        writer.Indentation++;

        // Use pre-computed reversed list for disposal
        foreach(var cached in groups.ReversedScopedForDisposal)
        {
            writer.WriteLine($"await DisposeServiceAsync({cached.FieldName});");
        }

        // Dispose imported module scopes (child scopes have their own module scopes)
        foreach(var module in container.ImportedModules)
        {
            var fieldName = GetModuleFieldName(module.Name);
            writer.WriteLine($"await {fieldName}.DisposeAsync();");
        }

        writer.WriteLine("return;");

        writer.Indentation--;
        writer.WriteLine("}");
        writer.WriteLine();

        // Use pre-computed reversed list for disposal
        foreach(var cached in groups.ReversedSingletonsForDisposal)
        {
            writer.WriteLine($"await DisposeServiceAsync({cached.FieldName});");
        }

        // Dispose imported modules (root scope)
        foreach(var module in container.ImportedModules)
        {
            var fieldName = GetModuleFieldName(module.Name);
            writer.WriteLine($"await {fieldName}.DisposeAsync();");
        }

        writer.Indentation--;
        writer.WriteLine("}");
        writer.WriteLine();

        // Helper method for async disposal
        writer.WriteLine("private static async ValueTask DisposeServiceAsync(object? service)");
        writer.WriteLine("{");
        writer.Indentation++;
        writer.WriteLine("if(service is IAsyncDisposable asyncDisposable) await asyncDisposable.DisposeAsync();");
        writer.WriteLine("else if(service is IDisposable disposable) disposable.Dispose();");
        writer.Indentation--;
        writer.WriteLine("}");
        writer.WriteLine();

        // Helper method for sync disposal
        writer.WriteLine("private static void DisposeService(object? service)");
        writer.WriteLine("{");
        writer.Indentation++;
        writer.WriteLine("if(service is IDisposable disposable) disposable.Dispose();");
        writer.Indentation--;
        writer.WriteLine("}");
        writer.WriteLine();

        writer.WriteLine("#endregion");
    }

    /// <summary>
    /// Gets the collection resolver method name for IEnumerable&lt;T&gt; resolution.
    /// </summary>
    private static string GetCollectionResolverMethodName(string serviceType)
    {
        var baseName = GetSafeIdentifier(serviceType);
        return $"GetAll{baseName}";
    }

    /// <summary>
    /// Gets the field name for an imported module.
    /// </summary>
    private static string GetModuleFieldName(string moduleName)
    {
        var baseName = GetSafeIdentifier(moduleName);
        return $"_{char.ToLowerInvariant(baseName[0])}{baseName[1..]}";
    }
}
