using static SourceGen.Ioc.SourceGenerator.Models.Constants;

namespace SourceGen.Ioc;

partial class IocSourceGenerator
{
    /// <summary>
    /// Generates the container source code output.
    /// </summary>
    private static void GenerateContainerOutput(
        in SourceProductionContext ctx,
        ContainerWithGroups containerWithGroups,
        string assemblyName,
        (string? RootNamespace, string? CustomIocName) msbuildProps,
        bool hasDIPackage)
    {
        var source = GenerateContainerSource(containerWithGroups, assemblyName, msbuildProps, hasDIPackage);
        var fileName = $"{containerWithGroups.Container.ClassName}.Container.g.cs";
        ctx.AddSource(fileName, source);
    }

    /// <summary>
    /// Generates the container source code.
    /// </summary>
    private static string GenerateContainerSource(
        ContainerWithGroups containerWithGroups,
        string assemblyName,
        (string? RootNamespace, string? CustomIocName) msbuildProps,
        bool hasDIPackage)
    {
        var writer = new SourceWriter();
        var container = containerWithGroups.Container;
        var groups = containerWithGroups.Groups;

        // Determine if IServiceProviderFactory should be generated
        // Only generate if ResolveIServiceCollection is true AND the DI package is referenced
        var canGenerateServiceProviderFactory = container.ResolveIServiceCollection && hasDIPackage;

        // Effective UseSwitchStatement: when there are imported modules, always use FrozenDictionary
        // because combining services from multiple sources requires dictionary-based lookup
        var effectiveUseSwitchStatement = container.UseSwitchStatement && container.ImportedModules.Length == 0;

        WriteContainerHeader(writer);
        WriteContainerNamespaceAndClass(writer, container, groups, canGenerateServiceProviderFactory, effectiveUseSwitchStatement);

        return writer.ToString();
    }

    /// <summary>
    /// Writes the auto-generated header and using directives.
    /// </summary>
    private static void WriteContainerHeader(SourceWriter writer)
    {
        writer.WriteLine(AutoGeneratedHeader);
        writer.WriteLine(NullableEnable);
        writer.WriteLine();
        writer.WriteLine("using System;");
        writer.WriteLine("using System.Collections.Frozen;");
        writer.WriteLine("using System.Collections.Generic;");
        writer.WriteLine("using System.Linq;");
        writer.WriteLine("using System.Threading;");
        writer.WriteLine("using System.Threading.Tasks;");
        writer.WriteLine("using Microsoft.Extensions.DependencyInjection;");
        writer.WriteLine("using SourceGen.Ioc;");
        writer.WriteLine();
    }

    /// <summary>
    /// Writes the namespace and class declaration with all implemented interfaces.
    /// </summary>
    private static void WriteContainerNamespaceAndClass(
        SourceWriter writer,
        ContainerModel container,
        ContainerRegistrationGroups groups,
        bool canGenerateServiceProviderFactory,
        bool effectiveUseSwitchStatement)
    {
        // Write namespace if not global
        bool hasNamespace = !string.IsNullOrEmpty(container.ContainerNamespace);
        if(hasNamespace)
        {
            writer.WriteLine($"namespace {container.ContainerNamespace};");
            writer.WriteLine();
        }

        // Get interface list
        var interfaces = GetContainerInterfaces(container, canGenerateServiceProviderFactory);

        // Write class declaration
        writer.WriteLine($"partial class {container.ClassName} : {string.Join(", ", interfaces)}");
        writer.WriteLine("{");
        writer.Indentation++;

        // Write fields
        WriteContainerFields(writer, container, effectiveUseSwitchStatement);

        // Write constructors
        WriteContainerConstructors(writer, container, groups, effectiveUseSwitchStatement);

        // Write service resolver methods
        WriteServiceResolverMethods(writer, container.ThreadSafeStrategy, groups);

        // Write IServiceProvider implementation
        WriteIServiceProviderImplementation(writer, container, groups, effectiveUseSwitchStatement);

        // Write IKeyedServiceProvider implementation
        WriteIKeyedServiceProviderImplementation(writer, container, groups, effectiveUseSwitchStatement);

        // Write ISupportRequiredService implementation
        WriteISupportRequiredServiceImplementation(writer, container);

        // Write IServiceProviderIsService implementation
        WriteIServiceProviderIsServiceImplementation(writer, container, groups, effectiveUseSwitchStatement);

        // Write IServiceScopeFactory implementation
        WriteIServiceScopeFactoryImplementation(writer, container);

        // Write IIocContainer implementation
        WriteIIocContainerImplementation(writer, container, groups, effectiveUseSwitchStatement);

        // Write IServiceProviderFactory implementation (if DI package is available)
        if(canGenerateServiceProviderFactory)
        {
            WriteIServiceProviderFactoryImplementation(writer, container);
        }

        // Write Disposal implementation
        WriteDisposalImplementation(writer, container, groups);

        writer.Indentation--;
        writer.WriteLine("}");
    }

    private static readonly string[] _FixedContainerInterfaces = [
        "IServiceProvider",
        "IKeyedServiceProvider",
        "IServiceProviderIsService",
        "IServiceProviderIsKeyedService",
        "ISupportRequiredService",
        "IServiceScopeFactory",
        "IServiceScope",
        "IDisposable",
        "IAsyncDisposable"
    ];
    /// <summary>
    /// Builds the list of interfaces the container should implement.
    /// </summary>
    private static IEnumerable<string> GetContainerInterfaces(ContainerModel container, bool canGenerateServiceProviderFactory)
    {
        yield return $"IIocContainer<{container.ContainerTypeName}>";

        foreach(var i in _FixedContainerInterfaces)
            yield return i;

        if(canGenerateServiceProviderFactory)
            yield return "IServiceProviderFactory<IServiceCollection>";
    }

    /// <summary>
    /// Writes container fields (fallback provider, service storage, locks, etc.).
    /// </summary>
    private static void WriteContainerFields(
        SourceWriter writer,
        ContainerModel container,
        bool effectiveUseSwitchStatement)
    {
        // Fallback provider field (only if ResolveIServiceCollection is enabled)
        if(container.ResolveIServiceCollection)
        {
            writer.WriteLine("private readonly IServiceProvider? _fallbackProvider;");
        }

        // Scope tracking
        writer.WriteLine("private readonly bool _isRootScope = true;");
        writer.WriteLine("private int _disposed;");
        writer.WriteLine();

        // Service resolver dictionary
        if(!effectiveUseSwitchStatement)
        {
            writer.WriteLine($"private readonly FrozenDictionary<(Type ServiceType, object Key), Func<{container.ContainerTypeName}, object>> _serviceResolvers;");
            writer.WriteLine();
        }

        // Imported module fields
        foreach(var module in container.ImportedModules)
        {
            var fieldName = GetModuleFieldName(module.Name);
            writer.WriteLine($"private readonly {module.Name} {fieldName};");
        }

        if(container.ImportedModules.Length > 0)
        {
            writer.WriteLine();
        }
    }

    /// <summary>
    /// Writes a service instance field and synchronization field based on ThreadSafeStrategy.
    /// </summary>
    private static void WriteServiceInstanceField(
        SourceWriter writer,
        ThreadSafeStrategy strategy,
        ServiceRegistrationModel reg,
        string fieldName,
        bool hasDecorators)
    {
        // When there are decorators, field type is ServiceType (interface), otherwise ImplementationType
        var typeName = hasDecorators ? reg.ServiceType.Name : reg.ImplementationType.Name;
        writer.WriteLine($"private {typeName}? {fieldName};");

        // Generate synchronization field based on strategy
        switch(strategy)
        {
            case ThreadSafeStrategy.None:
                // No synchronization field needed
                break;

            case ThreadSafeStrategy.Lock:
                writer.WriteLine($"private readonly Lock {fieldName}Lock = new();");
                break;

            case ThreadSafeStrategy.SemaphoreSlim:
                writer.WriteLine($"private readonly SemaphoreSlim {fieldName}Semaphore = new(1, 1);");
                break;

            case ThreadSafeStrategy.SpinLock:
                // SpinLock must NOT be readonly because Enter/Exit mutate it
                writer.WriteLine($"private SpinLock {fieldName}SpinLock = new(false);");
                break;
        }
    }

    /// <summary>
    /// Writes container constructors.
    /// </summary>
    private static void WriteContainerConstructors(
        SourceWriter writer,
        ContainerModel container,
        ContainerRegistrationGroups groups,
        bool effectiveUseSwitchStatement)
    {
        writer.WriteLine("#region Constructors");
        writer.WriteLine();

        // Default constructor
        writer.WriteLine("/// <summary>");
        writer.WriteLine("/// Creates a new standalone container without external service provider fallback.");
        writer.WriteLine("/// </summary>");

        // Need fallback provider constructor if ResolveIServiceCollection is enabled
        var needsFallbackProvider = container.ResolveIServiceCollection;

        if(needsFallbackProvider)
        {
            writer.WriteLine($"public {container.ClassName}() : this((IServiceProvider?)null) {{ }}");
        }
        else
        {
            // Standalone mode - no fallback provider
            writer.WriteLine($"public {container.ClassName}()");
            writer.WriteLine("{");
            writer.Indentation++;
            WriteConstructorBody(writer, container, groups, hasParameter: false, effectiveUseSwitchStatement);
            writer.Indentation--;
            writer.WriteLine("}");
        }
        writer.WriteLine();

        // Constructor with fallback provider (if enabled)
        if(needsFallbackProvider)
        {
            writer.WriteLine("/// <summary>");
            writer.WriteLine("/// Creates a new container with optional fallback to external service provider.");
            writer.WriteLine("/// </summary>");
            writer.WriteLine("/// <param name=\"fallbackProvider\">Optional external service provider for unknown dependencies.</param>");
            writer.WriteLine($"public {container.ClassName}(IServiceProvider? fallbackProvider)");
            writer.WriteLine("{");
            writer.Indentation++;
            writer.WriteLine("_fallbackProvider = fallbackProvider;");
            WriteConstructorBody(writer, container, groups, hasParameter: true, effectiveUseSwitchStatement);
            writer.Indentation--;
            writer.WriteLine("}");
            writer.WriteLine();
        }

        // Private constructor for scoped instances
        writer.WriteLine($"private {container.ClassName}({container.ClassName} parent)");
        writer.WriteLine("{");
        writer.Indentation++;
        if(needsFallbackProvider)
        {
            writer.WriteLine("_fallbackProvider = parent._fallbackProvider;");
        }
        writer.WriteLine("_isRootScope = false;");

        // Copy singleton references from parent (already filtered for non-open-generics)
        // Skip instance registrations as they don't have fields
        foreach(var cached in groups.Singletons)
        {
            // Instance registrations don't have fields, skip them
            if(cached.Registration.Instance is not null)
                continue;

            writer.WriteLine($"{cached.FieldName} = parent.{cached.FieldName};");
        }

        // Create scopes for imported modules (so their scoped services are properly isolated)
        foreach(var module in container.ImportedModules)
        {
            var fieldName = GetModuleFieldName(module.Name);
            writer.WriteLine($"{fieldName} = ({module.Name})parent.{fieldName}.CreateScope().ServiceProvider;");
        }

        // Because resolvers are immutable per container, they can be reused from parent
        if(!effectiveUseSwitchStatement)
        {
            writer.WriteLine("_serviceResolvers = parent._serviceResolvers;");
        }

        writer.Indentation--;
        writer.WriteLine("}");
        writer.WriteLine();

        writer.WriteLine("#endregion");
        writer.WriteLine();
    }

    /// <summary>
    /// Writes the constructor body for building the service resolver dictionary.
    /// </summary>
    private static void WriteConstructorBody(
        SourceWriter writer,
        ContainerModel container,
        ContainerRegistrationGroups groups,
        bool hasParameter,
        bool effectiveUseSwitchStatement)
    {
        // Initialize imported modules
        foreach(var module in container.ImportedModules)
        {
            var fieldName = GetModuleFieldName(module.Name);
            if(container.ResolveIServiceCollection && hasParameter)
            {
                writer.WriteLine($"{fieldName} = new {module.Name}(fallbackProvider);");
            }
            else
            {
                writer.WriteLine($"{fieldName} = new {module.Name}();");
            }
        }

        // Build FrozenDictionary
        if(!effectiveUseSwitchStatement)
        {
            writer.WriteLine();
            if(container.ImportedModules.Length > 0)
            {
                // Combine with imported modules - wrap module resolvers to pass the correct module instance
                writer.WriteLine("_serviceResolvers =");

                var isFirst = true;
                foreach(var module in container.ImportedModules)
                {
                    var fieldName = GetModuleFieldName(module.Name);
                    var source = $"{fieldName}.Services.Select(static kvp => new KeyValuePair<(Type, object), Func<{container.ContainerTypeName}, object>>(kvp.Key, c => kvp.Value(c.{fieldName})))";

                    if(isFirst)
                    {
                        writer.WriteLine(source);
                        isFirst = false;
                    }
                    else
                    {
                        writer.WriteLine($"    .Concat({source})");
                    }
                }

                writer.WriteLine("    .Concat(_localServices)");
                writer.WriteLine("    .ToFrozenDictionary();");
            }
            else
            {
                writer.WriteLine("_serviceResolvers = _localServices.ToFrozenDictionary();");
            }
        }
    }

    /// <summary>
    /// Writes individual service resolver methods.
    /// </summary>
    private static void WriteServiceResolverMethods(
        SourceWriter writer,
        ThreadSafeStrategy strategy,
        ContainerRegistrationGroups groups)
    {
        writer.WriteLine("#region Service Resolution");
        writer.WriteLine();

        var writtenMethods = new HashSet<string>();

        // All registrations are already filtered (no open generics)
        WriteServiceResolverGroup(writer, strategy, groups.Singletons, writtenMethods, groups);
        WriteServiceResolverGroup(writer, strategy, groups.Scoped, writtenMethods, groups);
        WriteServiceResolverGroup(writer, strategy, groups.Transients, writtenMethods, groups);

        // Write array resolver methods for IEnumerable<T>, IReadOnlyCollection<T>, IReadOnlyList<T>, T[] support
        foreach(var serviceType in groups.CollectionServiceTypes)
        {
            WriteArrayResolverMethod(writer, serviceType, groups);
            writer.WriteLine();
        }

        writer.WriteLine("#endregion");
        writer.WriteLine();
    }

    /// <summary>
    /// Writes resolver methods for a group of registrations, ensuring unique method names.
    /// </summary>
    private static void WriteServiceResolverGroup(
        SourceWriter writer,
        ThreadSafeStrategy strategy,
        IEnumerable<CachedRegistration> registrations,
        HashSet<string> writtenMethods,
        ContainerRegistrationGroups groups)
    {
        foreach(var cached in registrations)
        {
            if(!writtenMethods.Add(cached.ResolverMethodName))
                continue;
            WriteServiceResolverMethod(writer, strategy, cached, groups);
            writer.WriteLine();
        }
    }

    /// <summary>
    /// Writes an array resolver method for IEnumerable&lt;T&gt;, IReadOnlyCollection&lt;T&gt;, IReadOnlyList&lt;T&gt;, T[] resolution.
    /// </summary>
    private static void WriteArrayResolverMethod(
        SourceWriter writer,
        string serviceType,
        ContainerRegistrationGroups groups)
    {
        var methodName = GetArrayResolverMethodName(serviceType);
        var returnType = $"{serviceType}[]";

        // Use pre-computed collection registrations (already filtered for non-open-generics)
        if(!groups.CollectionRegistrations.TryGetValue(serviceType, out var registrations))
            return;

        // Deduplicate resolver method names to avoid calling the same resolver multiple times
        var uniqueResolvers = new HashSet<string>();
        var resolverMethods = new List<string>();

        foreach(var cached in registrations)
        {
            if(uniqueResolvers.Add(cached.ResolverMethodName))
            {
                resolverMethods.Add(cached.ResolverMethodName);
            }
        }

        // Only generate collection if there are multiple unique resolvers
        if(resolverMethods.Count < 2)
            return;

        writer.WriteLine($"private {returnType} {methodName}() =>");
        writer.Indentation++;
        writer.WriteLine("[");
        writer.Indentation++;

        foreach(var resolverMethod in resolverMethods)
        {
            writer.WriteLine($"{resolverMethod}(),");
        }

        writer.Indentation--;
        writer.WriteLine("];");
        writer.Indentation--;
    }

    /// <summary>
    /// Writes a single service resolver method.
    /// </summary>
    private static void WriteServiceResolverMethod(
        SourceWriter writer,
        ThreadSafeStrategy strategy,
        CachedRegistration cached,
        ContainerRegistrationGroups groups)
    {
        var reg = cached.Registration;
        var methodName = cached.ResolverMethodName;
        var fieldName = cached.FieldName;

        // Check if factory or instance registration
        bool hasFactory = reg.Factory is not null;
        bool hasInstance = reg.Instance is not null;
        bool hasDecorators = reg.Decorators.Length > 0;

        // Return type: if there are decorators, return the ServiceType (interface), otherwise ImplementationType
        var returnType = hasDecorators ? reg.ServiceType.Name : reg.ImplementationType.Name;

        // Instance registration: directly return the instance without field caching
        // The instance is already externally managed, no need for field storage
        if(hasInstance)
        {
            WriteInstanceResolverMethod(writer, methodName, returnType, reg);
            return;
        }

        switch(reg.Lifetime)
        {
            case ServiceLifetime.Singleton:
            case ServiceLifetime.Scoped:
                // Write field and synchronization field above the resolver method for better readability
                WriteServiceInstanceField(writer, strategy, reg, fieldName, hasDecorators);

                // Write resolver method based on thread-safe strategy
                WriteResolverMethodWithThreadSafety(writer, strategy, methodName, returnType, fieldName, reg, hasFactory, hasDecorators, groups);
                break;

            case ServiceLifetime.Transient:
                WriteTransientResolverMethod(writer, methodName, returnType, reg, hasFactory, hasDecorators, groups);
                break;
        }
    }

    /// <summary>
    /// Writes a simple resolver method for instance registrations.
    /// Instance registrations directly return the pre-existing instance without field caching.
    /// </summary>
    private static void WriteInstanceResolverMethod(
        SourceWriter writer,
        string methodName,
        string returnType,
        ServiceRegistrationModel reg)
    {
        writer.WriteLine($"private {returnType} {methodName}() => {reg.Instance};");
    }

    /// <summary>
    /// Writes resolver method based on the specified thread-safety strategy.
    /// </summary>
    private static void WriteResolverMethodWithThreadSafety(
        SourceWriter writer,
        ThreadSafeStrategy strategy,
        string methodName,
        string returnType,
        string fieldName,
        ServiceRegistrationModel reg,
        bool hasFactory,
        bool hasDecorators,
        ContainerRegistrationGroups groups)
    {
        writer.WriteLine($"private {returnType} {methodName}()");
        writer.WriteLine("{");
        writer.Indentation++;

        // Early return check (common to all strategies)
        writer.WriteLine($"if ({fieldName} is not null) return {fieldName};");
        writer.WriteLine();

        switch(strategy)
        {
            case ThreadSafeStrategy.None:
                WriteResolverBodyNone(writer, fieldName, reg, hasFactory, hasDecorators, groups);
                break;

            case ThreadSafeStrategy.Lock:
                WriteResolverBodyLock(writer, fieldName, reg, hasFactory, hasDecorators, groups);
                break;

            case ThreadSafeStrategy.SemaphoreSlim:
                WriteResolverBodySemaphoreSlim(writer, fieldName, reg, hasFactory, hasDecorators, groups);
                break;

            case ThreadSafeStrategy.SpinLock:
                WriteResolverBodySpinLock(writer, fieldName, reg, hasFactory, hasDecorators, groups);
                break;
        }

        writer.Indentation--;
        writer.WriteLine("}");
    }

    /// <summary>
    /// Writes resolver body for ThreadSafeStrategy.None (no synchronization).
    /// </summary>
    private static void WriteResolverBodyNone(
        SourceWriter writer,
        string fieldName,
        ServiceRegistrationModel reg,
        bool hasFactory,
        bool hasDecorators,
        ContainerRegistrationGroups groups)
    {
        var variableType = hasDecorators ? reg.ServiceType.Name : null;
        WriteInstanceCreationWithInjection(writer, "instance", reg, hasFactory, variableType, groups);

        if(hasDecorators)
        {
            writer.WriteLine();
            WriteDecoratorApplication(writer, "instance", reg, groups);
        }

        writer.WriteLine();
        writer.WriteLine($"{fieldName} = instance;");
        writer.WriteLine("return instance;");
    }

    /// <summary>
    /// Writes resolver body for ThreadSafeStrategy.Lock (using lock statement).
    /// </summary>
    private static void WriteResolverBodyLock(
        SourceWriter writer,
        string fieldName,
        ServiceRegistrationModel reg,
        bool hasFactory,
        bool hasDecorators,
        ContainerRegistrationGroups groups)
    {
        writer.WriteLine($"lock ({fieldName}Lock)");
        writer.WriteLine("{");
        writer.Indentation++;

        writer.WriteLine($"if ({fieldName} is not null) return {fieldName};");
        writer.WriteLine();

        var variableType = hasDecorators ? reg.ServiceType.Name : null;
        WriteInstanceCreationWithInjection(writer, "instance", reg, hasFactory, variableType, groups);

        if(hasDecorators)
        {
            writer.WriteLine();
            WriteDecoratorApplication(writer, "instance", reg, groups);
        }

        writer.WriteLine();
        writer.WriteLine($"{fieldName} = instance;");
        writer.WriteLine("return instance;");

        writer.Indentation--;
        writer.WriteLine("}");
    }

    /// <summary>
    /// Writes resolver body for ThreadSafeStrategy.SemaphoreSlim.
    /// </summary>
    private static void WriteResolverBodySemaphoreSlim(
        SourceWriter writer,
        string fieldName,
        ServiceRegistrationModel reg,
        bool hasFactory,
        bool hasDecorators,
        ContainerRegistrationGroups groups)
    {
        writer.WriteLine($"{fieldName}Semaphore.Wait();");
        writer.WriteLine("try");
        writer.WriteLine("{");
        writer.Indentation++;

        writer.WriteLine($"if ({fieldName} is not null) return {fieldName};");
        writer.WriteLine();

        var variableType = hasDecorators ? reg.ServiceType.Name : null;
        WriteInstanceCreationWithInjection(writer, "instance", reg, hasFactory, variableType, groups);

        if(hasDecorators)
        {
            writer.WriteLine();
            WriteDecoratorApplication(writer, "instance", reg, groups);
        }

        writer.WriteLine();
        writer.WriteLine($"{fieldName} = instance;");
        writer.WriteLine("return instance;");

        writer.Indentation--;
        writer.WriteLine("}");
        writer.WriteLine("finally");
        writer.WriteLine("{");
        writer.Indentation++;
        writer.WriteLine($"{fieldName}Semaphore.Release();");
        writer.Indentation--;
        writer.WriteLine("}");
    }

    /// <summary>
    /// Writes resolver body for ThreadSafeStrategy.SpinLock.
    /// </summary>
    private static void WriteResolverBodySpinLock(
        SourceWriter writer,
        string fieldName,
        ServiceRegistrationModel reg,
        bool hasFactory,
        bool hasDecorators,
        ContainerRegistrationGroups groups)
    {
        writer.WriteLine("bool lockTaken = false;");
        writer.WriteLine("try");
        writer.WriteLine("{");
        writer.Indentation++;

        writer.WriteLine($"{fieldName}SpinLock.Enter(ref lockTaken);");
        writer.WriteLine($"if ({fieldName} is not null) return {fieldName};");
        writer.WriteLine();

        var variableType = hasDecorators ? reg.ServiceType.Name : null;
        WriteInstanceCreationWithInjection(writer, "instance", reg, hasFactory, variableType, groups);

        if(hasDecorators)
        {
            writer.WriteLine();
            WriteDecoratorApplication(writer, "instance", reg, groups);
        }

        writer.WriteLine();
        writer.WriteLine($"{fieldName} = instance;");
        writer.WriteLine("return instance;");

        writer.Indentation--;
        writer.WriteLine("}");
        writer.WriteLine("finally");
        writer.WriteLine("{");
        writer.Indentation++;
        writer.WriteLine("if (lockTaken) {fieldName}SpinLock.Exit();".Replace("{fieldName}", fieldName));
        writer.Indentation--;
        writer.WriteLine("}");
    }

    /// <summary>
    /// Writes transient resolver method (creates new instance each time).
    /// </summary>
    private static void WriteTransientResolverMethod(
        SourceWriter writer,
        string methodName,
        string returnType,
        ServiceRegistrationModel reg,
        bool hasFactory,
        bool hasDecorators,
        ContainerRegistrationGroups groups)
    {
        writer.WriteLine($"private {returnType} {methodName}()");
        writer.WriteLine("{");
        writer.Indentation++;

        // Simple case: no injection members and no decorators
        if(reg.InjectionMembers.Length == 0 && !hasDecorators)
        {
            var instanceCreation = BuildInstanceCreationInline(reg, hasFactory, groups);
            writer.WriteLine($"return {instanceCreation};");
            writer.Indentation--;
            writer.WriteLine("}");
            return;
        }

        // Complex case: has injection members or decorators
        var variableType = hasDecorators ? reg.ServiceType.Name : null;
        WriteInstanceCreationWithInjection(writer, "instance", reg, hasFactory, variableType, groups);

        if(hasDecorators)
        {
            writer.WriteLine();
            WriteDecoratorApplication(writer, "instance", reg, groups);
        }

        writer.WriteLine("return instance;");
        writer.Indentation--;
        writer.WriteLine("}");
    }

    /// <summary>
    /// Writes instance creation with property/method injection.
    /// </summary>
    /// <param name="variableType">Optional explicit type for the variable. When null, 'var' is used.</param>
    private static void WriteInstanceCreationWithInjection(
        SourceWriter writer,
        string varName,
        ServiceRegistrationModel reg,
        bool hasFactory,
        string? variableType,
        ContainerRegistrationGroups groups)
    {
        var typeDeclaration = variableType ?? "var";

        if(hasFactory)
        {
            var factoryCall = BuildFactoryCallForContainer(reg.Factory!, reg, groups);
            writer.WriteLine($"{typeDeclaration} {varName} = ({reg.ImplementationType.Name}){factoryCall};");
            return;
        }

        WriteConstructorWithInjection(writer, varName, typeDeclaration, reg, groups);
    }

    /// <summary>
    /// Writes constructor invocation with property/field and method injection.
    /// </summary>
    private static void WriteConstructorWithInjection(
        SourceWriter writer,
        string varName,
        string typeDeclaration,
        ServiceRegistrationModel reg,
        ContainerRegistrationGroups groups)
    {
        var (properties, methods) = CategorizeInjectionMembers(reg.InjectionMembers);
        var args = BuildConstructorArgumentsString(reg, groups);

        WriteConstructorWithPropertyInitializers(writer, varName, typeDeclaration, reg.ImplementationType.Name, args, properties, groups);
        WriteMethodInjectionCalls(writer, varName, methods, reg, groups);
    }

    /// <summary>
    /// Categorizes injection members into properties/fields and methods.
    /// </summary>
    private static (List<InjectionMemberData>? Properties, List<InjectionMemberData>? Methods) CategorizeInjectionMembers(
        ImmutableEquatableArray<InjectionMemberData> injectionMembers)
    {
        List<InjectionMemberData>? properties = null;
        List<InjectionMemberData>? methods = null;

        foreach(var member in injectionMembers)
        {
            if(member.MemberType is InjectionMemberType.Property or InjectionMemberType.Field)
            {
                properties ??= [];
                properties.Add(member);
            }
            else if(member.MemberType == InjectionMemberType.Method)
            {
                methods ??= [];
                methods.Add(member);
            }
        }

        return (properties, methods);
    }

    /// <summary>
    /// Writes constructor invocation with optional property initializers.
    /// </summary>
    private static void WriteConstructorWithPropertyInitializers(
        SourceWriter writer,
        string varName,
        string typeDeclaration,
        string typeName,
        string args,
        List<InjectionMemberData>? properties,
        ContainerRegistrationGroups groups)
    {
        if(properties is not { Count: > 0 })
        {
            writer.WriteLine($"{typeDeclaration} {varName} = new {typeName}({args});");
            return;
        }

        writer.WriteLine($"{typeDeclaration} {varName} = new {typeName}({args})");
        writer.WriteLine("{");
        writer.Indentation++;

        foreach(var prop in properties)
        {
            var resolveCall = BuildServiceResolutionCallForContainer(prop.Type!, prop.Key, prop.IsNullable, groups);
            writer.WriteLine($"{prop.Name} = {resolveCall},");
        }

        writer.Indentation--;
        writer.WriteLine("};");
    }

    /// <summary>
    /// Writes method injection calls.
    /// </summary>
    private static void WriteMethodInjectionCalls(
        SourceWriter writer,
        string varName,
        List<InjectionMemberData>? methods,
        ServiceRegistrationModel reg,
        ContainerRegistrationGroups groups)
    {
        if(methods is null)
            return;

        foreach(var method in methods)
        {
            var methodArgs = method.Parameters is { Length: > 0 }
                ? string.Join(", ", method.Parameters.Select(p => BuildParameterForContainer(p, reg, groups)))
                : "";
            writer.WriteLine($"{varName}.{method.Name}({methodArgs});");
        }
    }

    /// <summary>
    /// Writes decorator application code.
    /// Decorators are applied in reverse order (from innermost to outermost),
    /// matching the behavior of Register mode.
    /// </summary>
    private static void WriteDecoratorApplication(
        SourceWriter writer,
        string varName,
        ServiceRegistrationModel reg,
        ContainerRegistrationGroups groups)
    {
        // Decorators array is in order from outermost to innermost,
        // we iterate in reverse order for building the chain from inner to outer
        var decorators = reg.Decorators;
        for(int i = decorators.Length - 1; i >= 0; i--)
        {
            var decorator = decorators[i];
            var hasInjectionMembers = decorator.InjectionMembers?.Length > 0;
            var argsString = string.Join(", ", GetDecoratorArguments(varName, decorator, groups));

            if(hasInjectionMembers)
            {
                // When decorator has injection members, use a temporary variable with concrete type
                // to allow accessing the decorator's properties/methods before assigning to interface variable
                var decoratorVarName = $"decorator{decorators.Length - 1 - i}";
                WriteDecoratorCreationWithInjection(writer, decoratorVarName, decorator, argsString, reg, groups);

                // Assign to the interface variable
                writer.WriteLine($"{varName} = {decoratorVarName};");
            }
            else
            {
                // No injection members, directly assign to the interface variable
                writer.WriteLine($"{varName} = new {decorator.Name}({argsString});");
            }
        }
    }

    /// <summary>
    /// Yields decorator constructor arguments without allocating a List.
    /// First parameter is always the inner instance (the decorated service).
    /// </summary>
    private static IEnumerable<string> GetDecoratorArguments(string innerInstance, TypeData decorator, ContainerRegistrationGroups groups)
    {
        yield return innerInstance;

        if(decorator.ConstructorParameters?.Length > 1)
        {
            // Skip the first parameter (it's the inner/decorated service)
            foreach(var param in decorator.ConstructorParameters.Skip(1))
            {
                yield return BuildServiceResolutionCallForContainer(param.Type, param.ServiceKey, param.IsNullable, groups);
            }
        }
    }

    /// <summary>
    /// Writes decorator creation with object initializer for property/field injection,
    /// and method calls for method injection.
    /// </summary>
    private static void WriteDecoratorCreationWithInjection(
        SourceWriter writer,
        string varName,
        TypeData decorator,
        string argsString,
        ServiceRegistrationModel reg,
        ContainerRegistrationGroups groups)
    {
        var injectionMembers = decorator.InjectionMembers;
        if(injectionMembers is null or { Length: 0 })
        {
            writer.WriteLine($"var {varName} = new {decorator.Name}({argsString});");
            return;
        }

        List<string>? propertyAssignments = null;
        List<string>? methodInvocations = null;

        foreach(var member in injectionMembers)
        {
            switch(member.MemberType)
            {
                case InjectionMemberType.Property:
                case InjectionMemberType.Field:
                    if(member.Type is not null)
                    {
                        var resolveCall = BuildServiceResolutionCallForContainer(member.Type, member.Key, member.IsNullable, groups);
                        propertyAssignments ??= [];
                        propertyAssignments.Add($"{member.Name} = {resolveCall},");
                    }
                    break;

                case InjectionMemberType.Method:
                    var methodArgs = member.Parameters is { Length: > 0 }
                        ? string.Join(", ", member.Parameters.Select(p => BuildParameterForInjectionMethod(p, reg, groups)))
                        : "";
                    methodInvocations ??= [];
                    methodInvocations.Add($"{varName}.{member.Name}({methodArgs});");
                    break;
            }
        }

        WriteDecoratorConstructorWithProperties(writer, varName, decorator.Name, argsString, propertyAssignments);

        if(methodInvocations is not null)
        {
            foreach(var invocation in methodInvocations)
            {
                writer.WriteLine(invocation);
            }
        }
    }

    /// <summary>
    /// Writes decorator constructor with optional property initializers.
    /// </summary>
    private static void WriteDecoratorConstructorWithProperties(
        SourceWriter writer,
        string varName,
        string decoratorName,
        string argsString,
        List<string>? propertyAssignments)
    {
        if(propertyAssignments is not { Count: > 0 })
        {
            writer.WriteLine($"var {varName} = new {decoratorName}({argsString});");
            return;
        }

        writer.WriteLine($"var {varName} = new {decoratorName}({argsString})");
        writer.WriteLine("{");
        writer.Indentation++;

        foreach(var assignment in propertyAssignments)
        {
            writer.WriteLine(assignment);
        }

        writer.Indentation--;
        writer.WriteLine("};");
    }

    /// <summary>
    /// Builds instance creation inline (for return statements).
    /// </summary>
    private static string BuildInstanceCreationInline(
        ServiceRegistrationModel reg,
        bool hasFactory,
        ContainerRegistrationGroups groups)
    {
        if(hasFactory)
        {
            var factoryCall = BuildFactoryCallForContainer(reg.Factory!, reg, groups);
            return $"({reg.ImplementationType.Name}){factoryCall}";
        }

        var args = BuildConstructorArgumentsString(reg, groups);
        return $"new {reg.ImplementationType.Name}({args})";
    }

    /// <summary>
    /// Builds constructor arguments as a string.
    /// </summary>
    private static string BuildConstructorArgumentsString(ServiceRegistrationModel reg, ContainerRegistrationGroups groups)
    {
        var parameters = reg.ImplementationType.ConstructorParameters;
        if(parameters is null or { Length: 0 })
            return "";

        return string.Join(", ", parameters.Select(p => BuildParameterForContainer(p, reg, groups)));
    }

    /// <summary>
    /// Builds a single parameter for injection method (handles IServiceProvider and service resolution).
    /// </summary>
    private static string BuildParameterForInjectionMethod(ParameterData param, ServiceRegistrationModel reg, ContainerRegistrationGroups groups)
    {
        if(param.Type.Name is IServiceProviderTypeName or IServiceProviderGlobalTypeName)
            return "this";

        return BuildServiceResolutionCallForContainer(param.Type, param.ServiceKey, param.IsOptional, groups);
    }

    /// <summary>
    /// Builds a single parameter for container (constructor, method injection, or factory).
    /// Handles [ServiceKey], [FromKeyedServices], IServiceProvider, and regular service resolution.
    /// </summary>
    private static string BuildParameterForContainer(ParameterData param, ServiceRegistrationModel reg, ContainerRegistrationGroups groups)
    {
        if(param.HasServiceKeyAttribute)
            return reg.Key ?? "null";

        if(param.Type.Name is IServiceProviderTypeName or IServiceProviderGlobalTypeName)
            return "this";

        return BuildServiceResolutionCallForContainer(param.Type, param.ServiceKey, param.IsOptional, groups);
    }

    /// <summary>
    /// Builds a factory method call string for container.
    /// </summary>
    private static string BuildFactoryCallForContainer(FactoryMethodData factory, ServiceRegistrationModel reg, ContainerRegistrationGroups groups)
    {
        var args = GetFactoryArguments(factory, reg, groups);
        var genericTypeArgs = BuildGenericFactoryTypeArgs(factory, reg.ServiceType);
        var factoryCallPath = genericTypeArgs is not null ? $"{factory.Path}<{genericTypeArgs}>" : factory.Path;

        return $"{factoryCallPath}({string.Join(", ", args)})";
    }

    /// <summary>
    /// Yields factory method arguments without allocating a List.
    /// </summary>
    private static IEnumerable<string> GetFactoryArguments(FactoryMethodData factory, ServiceRegistrationModel reg, ContainerRegistrationGroups groups)
    {
        if(factory.HasServiceProvider)
            yield return "this";

        if(factory.HasKey && reg.Key is not null)
            yield return reg.Key;

        foreach(var param in factory.AdditionalParameters)
            yield return BuildParameterForContainer(param, reg, groups);
    }

    /// <summary>
    /// Builds a service resolution call for container (direct call or GetService/GetRequiredService).
    /// When the dependency is registered in the same container, calls the resolver method directly.
    /// </summary>
    private static string BuildServiceResolutionCallForContainer(
        TypeData type,
        string? key,
        bool isOptional,
        ContainerRegistrationGroups groups)
    {
        // Collection types - use collection resolver method if available
        if(type.CollectionKind != CollectionKind.None)
        {
            var elementType = ExtractElementTypeForContainer(type);

            // Keyed collection services - fallback to GetKeyedServices (no direct call support yet)
            if(key is not null)
            {
                return $"GetKeyedServices<{elementType}>({key})";
            }

            // Check if we have a collection resolver for this element type
            if(groups.CollectionRegistrations.ContainsKey(elementType))
            {
                var methodName = GetArrayResolverMethodName(elementType);
                return $"{methodName}()";
            }

            return $"GetServices<{elementType}>()";
        }

        // Try to find direct resolver in this container
        if(groups.ByServiceTypeAndKey.TryGetValue((type.Name, key), out var registrations))
        {
            var cached = registrations[^1]; // Last wins
            return $"{cached.ResolverMethodName}()";
        }

        // Fallback to GetService/GetRequiredService for dependencies not in this container

        // Keyed services
        if(key is not null)
        {
            if(isOptional)
            {
                return $"GetKeyedService(typeof({type.Name}), {key}) as {type.Name}";
            }
            return $"({type.Name})GetRequiredKeyedService(typeof({type.Name}), {key})";
        }

        // Regular services
        if(isOptional)
        {
            return $"GetService(typeof({type.Name})) as {type.Name}";
        }
        return $"({type.Name})GetRequiredService(typeof({type.Name}))";
    }

    /// <summary>
    /// Extracts the element type from a collection type using pre-computed TypeParameters.
    /// </summary>
    private static string ExtractElementTypeForContainer(TypeData type)
    {
        // Use TypeParameters for efficient element type extraction
        if(type.TypeParameters is { Length: > 0 })
        {
            return type.TypeParameters[0].Type.Name;
        }
        return "object";
    }

    /// <summary>
    /// Writes IServiceProvider implementation.
    /// </summary>
    private static void WriteIServiceProviderImplementation(
        SourceWriter writer,
        ContainerModel container,
        ContainerRegistrationGroups groups,
        bool effectiveUseSwitchStatement)
    {
        writer.WriteLine("#region IServiceProvider");
        writer.WriteLine();

        writer.WriteLine("public object? GetService(Type serviceType)");
        writer.WriteLine("{");
        writer.Indentation++;

        // Built-in services
        writer.WriteLine("if(serviceType == typeof(IServiceProvider)) return this;");
        writer.WriteLine("if(serviceType == typeof(IServiceScopeFactory)) return this;");
        writer.WriteLine($"if(serviceType == typeof({container.ClassName})) return this;");
        writer.WriteLine();

        if(effectiveUseSwitchStatement)
        {
            // Cascading if statements - registrations already filtered (no open generics)
            foreach(var kvp in groups.ByServiceTypeAndKey)
            {
                if(kvp.Key.Key is not null)
                    continue;

                var cached = kvp.Value[^1]; // Last wins
                var reg = cached.Registration;
                writer.WriteLine($"if(serviceType == typeof({reg.ServiceType.Name})) return {cached.ResolverMethodName}();");
            }

            writer.WriteLine();
        }
        else
        {
            writer.WriteLine($"if(_serviceResolvers.TryGetValue((serviceType, {KeyedServiceAnyKey}), out var resolver))");
            writer.Indentation++;
            writer.WriteLine("return resolver(this);");
            writer.Indentation--;
            writer.WriteLine();
        }

        // Fallback
        if(container.ResolveIServiceCollection)
        {
            writer.WriteLine("return _fallbackProvider?.GetService(serviceType);");
        }
        else
        {
            writer.WriteLine("return null;");
        }

        writer.Indentation--;
        writer.WriteLine("}");
        writer.WriteLine();

        writer.WriteLine("#endregion");
        writer.WriteLine();
    }

    /// <summary>
    /// Writes IKeyedServiceProvider implementation.
    /// </summary>
    private static void WriteIKeyedServiceProviderImplementation(
        SourceWriter writer,
        ContainerModel container,
        ContainerRegistrationGroups groups,
        bool effectiveUseSwitchStatement)
    {
        writer.WriteLine("#region IKeyedServiceProvider");
        writer.WriteLine();

        writer.WriteLine("public object? GetKeyedService(Type serviceType, object? serviceKey)");
        writer.WriteLine("{");
        writer.Indentation++;

        writer.WriteLine($"var key = serviceKey ?? {KeyedServiceAnyKey};");
        writer.WriteLine();

        if(effectiveUseSwitchStatement)
        {
            // Use pre-computed hasKeyedServices flag
            if(groups.HasKeyedServices)
            {
                // Use tuple pattern matching switch expression
                writer.WriteLine("return (serviceType, key) switch");
                writer.WriteLine("{");
                writer.Indentation++;

                foreach(var kvp in groups.ByServiceTypeAndKey)
                {
                    if(kvp.Key.Key is null)
                        continue;

                    var cached = kvp.Value[^1]; // Last wins
                    writer.WriteLine($"(Type t, object k) when t == typeof({kvp.Key.ServiceType}) && Equals(k, {kvp.Key.Key}) => {cached.ResolverMethodName}(),");
                }

                // Fallback in switch default case
                if(container.ResolveIServiceCollection)
                {
                    writer.WriteLine("_ => _fallbackProvider is IKeyedServiceProvider keyed ? keyed.GetKeyedService(serviceType, serviceKey) : null");
                }
                else
                {
                    writer.WriteLine("_ => null");
                }

                writer.Indentation--;
                writer.WriteLine("};");
            }
            else
            {
                // No keyed services, just return fallback
                if(container.ResolveIServiceCollection)
                {
                    writer.WriteLine("return _fallbackProvider is IKeyedServiceProvider keyed ? keyed.GetKeyedService(serviceType, serviceKey) : null;");
                }
                else
                {
                    writer.WriteLine("return null;");
                }
            }
        }
        else
        {
            writer.WriteLine("if(_serviceResolvers.TryGetValue((serviceType, key), out var resolver))");
            writer.Indentation++;
            writer.WriteLine("return resolver(this);");
            writer.Indentation--;
            writer.WriteLine();

            // Fallback
            if(container.ResolveIServiceCollection)
            {
                writer.WriteLine("return _fallbackProvider is IKeyedServiceProvider keyed ? keyed.GetKeyedService(serviceType, serviceKey) : null;");
            }
            else
            {
                writer.WriteLine("return null;");
            }
        }

        writer.Indentation--;
        writer.WriteLine("}");
        writer.WriteLine();

        // GetRequiredKeyedService
        writer.WriteLine("public object GetRequiredKeyedService(Type serviceType, object? serviceKey)");
        writer.WriteLine("{");
        writer.Indentation++;
        writer.WriteLine("return GetKeyedService(serviceType, serviceKey) ?? throw new InvalidOperationException($\"No service for type '{serviceType}' with key '{serviceKey}' has been registered.\");");
        writer.Indentation--;
        writer.WriteLine("}");
        writer.WriteLine();

        writer.WriteLine("#endregion");
        writer.WriteLine();
    }

    /// <summary>
    /// Writes ISupportRequiredService implementation.
    /// </summary>
    private static void WriteISupportRequiredServiceImplementation(SourceWriter writer, ContainerModel container)
    {
        writer.WriteLine("#region ISupportRequiredService");
        writer.WriteLine();

        writer.WriteLine("public object GetRequiredService(Type serviceType)");
        writer.WriteLine("{");
        writer.Indentation++;
        writer.WriteLine("return GetService(serviceType) ?? throw new InvalidOperationException($\"No service for type '{serviceType}' has been registered.\");");
        writer.Indentation--;
        writer.WriteLine("}");
        writer.WriteLine();

        writer.WriteLine("#endregion");
        writer.WriteLine();
    }

    /// <summary>
    /// Writes IServiceProviderIsService implementation.
    /// </summary>
    private static void WriteIServiceProviderIsServiceImplementation(
        SourceWriter writer,
        ContainerModel container,
        ContainerRegistrationGroups groups,
        bool effectiveUseSwitchStatement)
    {
        writer.WriteLine("#region IServiceProviderIsService");
        writer.WriteLine();

        // IsService
        writer.WriteLine("public bool IsService(Type serviceType)");
        writer.WriteLine("{");
        writer.Indentation++;

        writer.WriteLine("if(serviceType == typeof(IServiceProvider)) return true;");
        writer.WriteLine("if(serviceType == typeof(IServiceScopeFactory)) return true;");
        writer.WriteLine($"if(serviceType == typeof({container.ClassName})) return true;");
        writer.WriteLine();

        if(effectiveUseSwitchStatement)
        {
            foreach(var serviceType in groups.AllServiceTypes)
            {
                writer.WriteLine($"if(serviceType == typeof({serviceType})) return true;");
            }
            writer.WriteLine();
        }
        else
        {
            writer.WriteLine($"if(_serviceResolvers.ContainsKey((serviceType, {KeyedServiceAnyKey}))) return true;");
            writer.WriteLine();
        }

        if(container.ResolveIServiceCollection)
        {
            writer.WriteLine("return _fallbackProvider is IServiceProviderIsService isService && isService.IsService(serviceType);");
        }
        else
        {
            writer.WriteLine("return false;");
        }

        writer.Indentation--;
        writer.WriteLine("}");
        writer.WriteLine();

        // IsKeyedService
        writer.WriteLine("public bool IsKeyedService(Type serviceType, object? serviceKey)");
        writer.WriteLine("{");
        writer.Indentation++;

        writer.WriteLine($"var key = serviceKey ?? {KeyedServiceAnyKey};");

        if(!effectiveUseSwitchStatement)
        {
            writer.WriteLine();
            writer.WriteLine("if(_serviceResolvers.ContainsKey((serviceType, key))) return true;");
        }

        writer.WriteLine();

        if(container.ResolveIServiceCollection)
        {
            writer.WriteLine("return _fallbackProvider is IServiceProviderIsKeyedService isKeyed && isKeyed.IsKeyedService(serviceType, serviceKey);");
        }
        else
        {
            writer.WriteLine("return false;");
        }

        writer.Indentation--;
        writer.WriteLine("}");
        writer.WriteLine();

        writer.WriteLine("#endregion");
        writer.WriteLine();
    }

    /// <summary>
    /// Writes IServiceScopeFactory implementation.
    /// </summary>
    private static void WriteIServiceScopeFactoryImplementation(SourceWriter writer, ContainerModel container)
    {
        writer.WriteLine("#region IServiceScopeFactory");
        writer.WriteLine();

        writer.WriteLine($"public IServiceScope CreateScope() => new {container.ClassName}(this);");
        writer.WriteLine();
        writer.WriteLine("public AsyncServiceScope CreateAsyncScope() => new(CreateScope());");
        writer.WriteLine();
        writer.WriteLine("IServiceProvider IServiceScope.ServiceProvider => this;");
        writer.WriteLine();

        writer.WriteLine("#endregion");
        writer.WriteLine();
    }

    /// <summary>
    /// Writes IIocContainer implementation.
    /// </summary>
    private static void WriteIIocContainerImplementation(
        SourceWriter writer,
        ContainerModel container,
        ContainerRegistrationGroups groups,
        bool effectiveUseSwitchStatement)
    {
        writer.WriteLine("#region IIocContainer");
        writer.WriteLine();

        if(effectiveUseSwitchStatement)
        {
            writer.WriteLine($"public IReadOnlyCollection<KeyValuePair<(Type ServiceType, object Key), Func<{container.ContainerTypeName}, object>>> Services => _localServices;");
        }
        else
        {
            writer.WriteLine($"public IReadOnlyCollection<KeyValuePair<(Type ServiceType, object Key), Func<{container.ContainerTypeName}, object>>> Services => _serviceResolvers;");
        }
        writer.WriteLine();

        // Write _localServices as static field
        writer.WriteLine($"private static readonly KeyValuePair<(Type, object), Func<{container.ContainerTypeName}, object>>[] _localServices =");
        writer.WriteLine("[");
        writer.Indentation++;

        // Use ByServiceTypeAndKey to include all service types (already filtered for non-open-generics)
        foreach(var kvp in groups.ByServiceTypeAndKey)
        {
            var cached = kvp.Value[^1]; // Last wins
            var keyExpr = kvp.Key.Key ?? KeyedServiceAnyKey;
            writer.WriteLine($"new((typeof({kvp.Key.ServiceType}), {keyExpr}), static c => c.{cached.ResolverMethodName}()),");
        }

        // Add IEnumerable<T>, IReadOnlyCollection<T>, IReadOnlyList<T>, T[] entries for collection service types
        foreach(var serviceType in groups.CollectionServiceTypes)
        {
            var methodName = GetArrayResolverMethodName(serviceType);
            writer.WriteLine($"new((typeof(global::System.Collections.Generic.IEnumerable<{serviceType}>), {KeyedServiceAnyKey}), static c => c.{methodName}()),");
            writer.WriteLine($"new((typeof(global::System.Collections.Generic.IReadOnlyCollection<{serviceType}>), {KeyedServiceAnyKey}), static c => c.{methodName}()),");
            writer.WriteLine($"new((typeof(global::System.Collections.Generic.IReadOnlyList<{serviceType}>), {KeyedServiceAnyKey}), static c => c.{methodName}()),");
            writer.WriteLine($"new((typeof({serviceType}[]), {KeyedServiceAnyKey}), static c => c.{methodName}()),");
        }

        writer.Indentation--;
        writer.WriteLine("];");

        writer.WriteLine();
        writer.WriteLine("#endregion");
        writer.WriteLine();
    }

    /// <summary>
    /// Writes IServiceProviderFactory implementation.
    /// </summary>
    private static void WriteIServiceProviderFactoryImplementation(SourceWriter writer, ContainerModel container)
    {
        writer.WriteLine("#region IServiceProviderFactory<IServiceCollection>");
        writer.WriteLine();

        writer.WriteLine("/// <summary>");
        writer.WriteLine("/// Creates a new container builder (returns the same IServiceCollection).");
        writer.WriteLine("/// </summary>");
        writer.WriteLine("public IServiceCollection CreateBuilder(IServiceCollection services) => services;");
        writer.WriteLine();

        writer.WriteLine("/// <summary>");
        writer.WriteLine("/// Creates the service provider from the built IServiceCollection.");
        writer.WriteLine("/// </summary>");
        writer.WriteLine("public IServiceProvider CreateServiceProvider(IServiceCollection containerBuilder)");
        writer.WriteLine("{");
        writer.Indentation++;
        writer.WriteLine("var fallbackProvider = containerBuilder.BuildServiceProvider();");
        writer.WriteLine($"return new {container.ClassName}(fallbackProvider);");
        writer.Indentation--;
        writer.WriteLine("}");
        writer.WriteLine();

        writer.WriteLine("#endregion");
        writer.WriteLine();
    }

    /// <summary>
    /// Writes Disposal implementation (IDisposable and IAsyncDisposable).
    /// </summary>
    private static void WriteDisposalImplementation(
        SourceWriter writer,
        ContainerModel container,
        ContainerRegistrationGroups groups)
    {
        writer.WriteLine("#region Disposal");
        writer.WriteLine();

        // IDisposable.Dispose
        writer.WriteLine("public void Dispose()");
        writer.WriteLine("{");
        writer.Indentation++;
        writer.WriteLine("if(Interlocked.Exchange(ref _disposed, 1) != 0) return;");
        writer.WriteLine();
        WriteDisposalBody(writer, container, groups, isAsync: false);
        writer.Indentation--;
        writer.WriteLine("}");
        writer.WriteLine();

        // IAsyncDisposable.DisposeAsync
        writer.WriteLine("public async ValueTask DisposeAsync()");
        writer.WriteLine("{");
        writer.Indentation++;
        writer.WriteLine("if(Interlocked.Exchange(ref _disposed, 1) != 0) return;");
        writer.WriteLine();
        WriteDisposalBody(writer, container, groups, isAsync: true);
        writer.Indentation--;
        writer.WriteLine("}");
        writer.WriteLine();

        WriteDisposalHelperMethods(writer);

        writer.WriteLine("#endregion");
    }

    /// <summary>
    /// Writes the disposal body for both sync and async disposal methods.
    /// </summary>
    private static void WriteDisposalBody(
        SourceWriter writer,
        ContainerModel container,
        ContainerRegistrationGroups groups,
        bool isAsync)
    {
        // Dispose scoped services if this is a scope
        writer.WriteLine("if(!_isRootScope)");
        writer.WriteLine("{");
        writer.Indentation++;

        WriteDisposalCalls(writer, groups.ReversedScopedForDisposal, container.ImportedModules, container.ThreadSafeStrategy, isAsync);
        writer.WriteLine("return;");

        writer.Indentation--;
        writer.WriteLine("}");
        writer.WriteLine();

        // Root scope disposal
        WriteDisposalCalls(writer, groups.ReversedSingletonsForDisposal, container.ImportedModules, container.ThreadSafeStrategy, isAsync);
    }

    /// <summary>
    /// Writes disposal calls for services and modules.
    /// </summary>
    private static void WriteDisposalCalls(
        SourceWriter writer,
        IEnumerable<CachedRegistration> services,
        ImmutableEquatableArray<TypeData> modules,
        ThreadSafeStrategy strategy,
        bool isAsync)
    {
        var (serviceMethod, moduleMethod) = isAsync
            ? ("await DisposeServiceAsync", "await {0}.DisposeAsync()")
            : ("DisposeService", "{0}.Dispose()");

        foreach(var cached in services)
        {
            // Skip instance registrations - they are externally managed and should not be disposed by the container
            if(cached.Registration.Instance is not null)
                continue;

            writer.WriteLine($"{serviceMethod}({cached.FieldName});");

            // Dispose SemaphoreSlim if using SemaphoreSlim strategy
            if(strategy == ThreadSafeStrategy.SemaphoreSlim)
            {
                writer.WriteLine($"{cached.FieldName}Semaphore.Dispose();");
            }
        }

        foreach(var module in modules)
        {
            var fieldName = GetModuleFieldName(module.Name);
            writer.WriteLine(string.Format(moduleMethod, fieldName) + ";");
        }
    }

    /// <summary>
    /// Writes the static helper methods for disposal.
    /// </summary>
    private static void WriteDisposalHelperMethods(SourceWriter writer)
    {
        // Helper method for async disposal
        writer.WriteLine("private static async ValueTask DisposeServiceAsync(object? service)");
        writer.WriteLine("{");
        writer.Indentation++;
        writer.WriteLine("if(service is IAsyncDisposable asyncDisposable) await asyncDisposable.DisposeAsync();");
        writer.WriteLine("else if(service is IDisposable disposable) disposable.Dispose();");
        writer.Indentation--;
        writer.WriteLine("}");
        writer.WriteLine();

        // Helper method for sync disposal
        writer.WriteLine("private static void DisposeService(object? service)");
        writer.WriteLine("{");
        writer.Indentation++;
        writer.WriteLine("if(service is IDisposable disposable) disposable.Dispose();");
        writer.Indentation--;
        writer.WriteLine("}");
        writer.WriteLine();
    }

    /// <summary>
    /// Gets the array resolver method name for IEnumerable&lt;T&gt;, IReadOnlyCollection&lt;T&gt;, IReadOnlyList&lt;T&gt;, T[] resolution.
    /// </summary>
    private static string GetArrayResolverMethodName(string serviceType)
    {
        var baseName = GetSafeIdentifier(serviceType);
        return $"GetAll{baseName}Array";
    }

    /// <summary>
    /// Gets the field name for an imported module.
    /// </summary>
    private static string GetModuleFieldName(string moduleName)
    {
        var baseName = GetSafeIdentifier(moduleName);
        return $"_{char.ToLowerInvariant(baseName[0])}{baseName[1..]}";
    }
}
