namespace SourceGen.Ioc;

partial class RegisterSourceGenerator
{
    private static void GenerateRegisterOutput(
        in SourceProductionContext ctx,
        ImmutableEquatableArray<ServiceRegistrationWithTags> registrations,
        string rootNamespace,
        string assemblyName,
        string? customIocName)
    {
        if(registrations.Length == 0)
            return;

        // Generate source
        var source = GenerateExtensionMethodSource(registrations, rootNamespace, assemblyName, customIocName);
        ctx.AddSource($"{assemblyName}.ServiceRegistration.g.cs", source);
    }

    private static string GenerateExtensionMethodSource(
        ImmutableEquatableArray<ServiceRegistrationWithTags> registrations,
        string rootNamespace,
        string assemblyName,
        string? customIocName)
    {
        // Use custom IoC name if provided, otherwise use assembly name
        var methodBaseName = !string.IsNullOrWhiteSpace(customIocName)
            ? GetSafeMethodName(customIocName!)
            : GetSafeMethodName(assemblyName);

        // Use Dictionary<string, SourceWriter> to write registrations directly grouped by method name
        // This avoids building intermediate data structures and minimizes loop iterations
        var methodWriters = new Dictionary<string, SourceWriter>(StringComparer.Ordinal);

        // Single pass: iterate once through all registrations, writing directly to method-specific SourceWriters
        foreach(var regWithTags in registrations)
        {
            var registration = regWithTags.Registration;

            // Write to default method if not tag-only
            if(!regWithTags.TagOnly)
            {
                var writer = GetOrCreateMethodWriter(methodWriters, DefaultMethodKey);
                WriteRegistration(writer, registration);
            }

            // Write to each tag-specific method
            foreach(var tag in regWithTags.Tags)
            {
                var writer = GetOrCreateMethodWriter(methodWriters, tag);
                WriteRegistration(writer, registration);
            }
        }

        // Build the final output
        var mainWriter = new SourceWriter();

        mainWriter.WriteLine("// <auto-generated/>");
        mainWriter.WriteLine("#nullable enable");
        mainWriter.WriteLine();
        mainWriter.WriteLine("using Microsoft.Extensions.DependencyInjection;");
        mainWriter.WriteLine("using System.Linq;");
        mainWriter.WriteLine();

        mainWriter.WriteLine($"namespace {GetSafeNamespace(rootNamespace)}");
        mainWriter.WriteLine("{");
        mainWriter.Indentation++;

        mainWriter.WriteLine("/// <summary>");
        mainWriter.WriteLine($"/// Extension methods for registering services from {assemblyName}.");
        mainWriter.WriteLine("/// </summary>");
        mainWriter.WriteLine($"public static class {methodBaseName}ServiceCollectionExtensions");
        mainWriter.WriteLine("{");
        mainWriter.Indentation++;

        // Output methods in sorted order for deterministic output
        bool isFirst = true;
        foreach(var kvp in methodWriters.OrderBy(static kvp => kvp.Key, StringComparer.Ordinal))
        {
            var methodKey = kvp.Key;
            var methodBodyWriter = kvp.Value;

            if(!isFirst)
            {
                mainWriter.WriteLine();
            }
            isFirst = false;

            if(string.IsNullOrEmpty(methodKey))
            {
                // Default method
                WriteMethodWrapper(mainWriter, methodBodyWriter, methodBaseName, "Registers all default services.");
            }
            else
            {
                // Tag-specific method
                var safeTagName = GetSafeMethodName(methodKey);
                WriteMethodWrapper(mainWriter, methodBodyWriter, $"{methodBaseName}_{safeTagName}", $"Registers all services tagged with '{methodKey}'.");
            }
        }

        mainWriter.Indentation--;
        mainWriter.WriteLine("}");

        mainWriter.Indentation--;
        mainWriter.WriteLine("}");

        return mainWriter.ToString();
    }

    /// <summary>
    /// Gets or creates a SourceWriter for a specific method key.
    /// The writer is pre-configured with the indentation level for method body content.
    /// </summary>
    private static SourceWriter GetOrCreateMethodWriter(Dictionary<string, SourceWriter> methodWriters, string methodKey)
    {
        if(!methodWriters.TryGetValue(methodKey, out var writer))
        {
            writer = new SourceWriter();
            // No need to set indentation since we write line by line without wrapping
            methodWriters[methodKey] = writer;
        }

        return writer;
    }

    /// <summary>
    /// Writes the method wrapper around the pre-generated registration code.
    /// </summary>
    private static void WriteMethodWrapper(
        SourceWriter mainWriter,
        SourceWriter methodBodyWriter,
        string methodName,
        string summary)
    {
        mainWriter.WriteLine("/// <summary>");
        mainWriter.WriteLine($"/// {summary}");
        mainWriter.WriteLine("/// </summary>");
        mainWriter.WriteLine($"public static IServiceCollection Add{methodName}(this IServiceCollection services)");
        mainWriter.WriteLine("{");
        mainWriter.Indentation++;

        // The methodBodyWriter has line-by-line output without indentation.
        // We need to write each line with proper indentation from mainWriter.
        var methodBody = methodBodyWriter.ToString();
        if(!string.IsNullOrEmpty(methodBody))
        {
            // Trim trailing newlines to avoid extra blank lines with indentation
            methodBody = methodBody.TrimEnd('\r', '\n');
            // Write each line with proper indentation
            mainWriter.WriteLine(methodBody);
        }

        // Add blank line before return statement
        mainWriter.WriteLine();
        mainWriter.WriteLine("return services;");

        mainWriter.Indentation--;
        mainWriter.WriteLine("}");
    }

    private static void WriteRegistration(SourceWriter writer, ServiceRegistrationModel registration)
    {
        var lifetime = registration.Lifetime.Name;
        var serviceTypeName = registration.ServiceType.Name;
        var implTypeName = registration.ImplementationType.Name;

        // Check if this registration uses Factory or Instance
        // Note: Factory and Instance cannot be used with open generics - they require concrete types
        bool hasFactory = registration.Factory is not null && !registration.IsOpenGeneric;
        bool hasInstance = registration.Instance is not null && !registration.IsOpenGeneric;

        // Handle Factory registration first (takes precedence)
        if(hasFactory)
        {
            WriteFactoryMethodRegistration(writer, registration, lifetime);
            return;
        }

        // Handle Instance registration (only for Singleton)
        if(hasInstance)
        {
            if(registration.Lifetime == ServiceLifetime.Singleton)
                WriteInstanceRegistration(writer, registration);

            return;
        }

        // Skip registration if constructor has unresolvable parameters
        // (built-in types or collections of built-in types without [IocInject], [ServiceKey], [FromKeyedServices], or default value)
        var constructorParameters = registration.ImplementationType.ConstructorParameters;
        if(constructorParameters?.Any(static p => p.IsUnresolvable) == true)
        {
            return;
        }

        // Check if service type is different from implementation type (registering interface/base class)
        bool isServiceTypeRegistration = serviceTypeName != implTypeName;

        // Check if this registration has decorators and is not the implementation type itself
        bool hasDecorators = registration.Decorators.Length > 0 && isServiceTypeRegistration;

        if(hasDecorators)
        {
            WriteDecoratorRegistration(writer, registration, lifetime);
            return;
        }

        // Check if this registration has injection members (properties, fields, methods with [Inject])
        bool hasInjectionMembers = registration.InjectionMembers.Length > 0;

        // Check if the constructor was selected by [Inject] attribute (requires factory for proper constructor selection)
        bool hasInjectConstructor = registration.ImplementationType.HasInjectConstructor;

        // Check constructor parameters for special handling requirements:
        // - [Inject] attribute on parameters: MS.DI doesn't recognize it
        // - Non-IEnumerable collection types (IList<T>, T[], etc.): MS.DI only supports IEnumerable<T>
        // - Has default value and is resolvable type: needs conditional handling (GetService + null check)
        // Note: [FromKeyedServices], [ServiceKey], IServiceProvider are handled by MS.DI automatically
        var constructorParams = registration.ImplementationType.ConstructorParameters;
        bool hasSpecialConstructorParams = constructorParams?.Any(static p =>
            p.HasInjectAttribute ||
            p.Type.IsNonEnumerableCollection ||
            (p.HasDefaultValue && !p.Type.IsBuiltInTypeOrBuiltInCollection)) == true;

        // Determine if factory construction is needed:
        // - Injection members (properties, fields, methods) always require factory
        // - Constructor with [Inject] attribute requires factory (to use correct constructor)
        // - Constructor parameters with special handling (see above)
        bool needsFactoryConstruction = hasInjectionMembers || hasInjectConstructor || hasSpecialConstructorParams;

        if(needsFactoryConstruction && !registration.IsOpenGeneric && isServiceTypeRegistration)
        {
            // Service type registration (interface/base class) where implementation is already registered with factory
            // Just resolve the implementation from the service provider
            WriteServiceTypeForwardingRegistration(writer, registration, lifetime);
            return;
        }

        if(needsFactoryConstruction && !registration.IsOpenGeneric)
        {
            // Self registration with injection members or constructor params with special handling - generate factory method
            WriteInjectionRegistration(writer, registration, lifetime);
            return;
        }

        if(registration.IsOpenGeneric)
        {
            // Open generic registration requires typeof() syntax
            var serviceTypeOf = ConvertToTypeOf(registration.ServiceType);
            var implTypeOf = ConvertToTypeOf(registration.ImplementationType);

            if(registration.Key is not null)
            {
                writer.WriteLine($"services.AddKeyed{lifetime}({serviceTypeOf}, {registration.Key}, {implTypeOf});");
                return;
            }

            writer.WriteLine($"services.Add{lifetime}({serviceTypeOf}, {implTypeOf});");
            return;
        }

        if(registration.Key is not null)
        {
            // Keyed registration
            writer.WriteLine($"services.AddKeyed{lifetime}<{serviceTypeName}, {registration.ImplementationType.Name}>({registration.Key});");
            return;
        }

        // Non-keyed registration
        writer.WriteLine($"services.Add{lifetime}<{serviceTypeName}, {registration.ImplementationType.Name}>();");
    }

    /// <summary>
    /// Writes registration code using a factory method specified in the attribute.
    /// </summary>
    /// <remarks>
    /// Supports factory methods with different parameter combinations:
    /// <list type="bullet">
    ///   <item>No parameters: <c>services.AddSingleton&lt;IService&gt;(Factory());</c></item>
    ///   <item>IServiceProvider only: <c>services.AddSingleton&lt;IService&gt;(sp => Factory(sp));</c></item>
    ///   <item>object key only (keyed): <c>services.AddKeyedSingleton&lt;IService&gt;("key", (sp, key) => Factory(key));</c></item>
    ///   <item>Both (keyed): <c>services.AddKeyedSingleton&lt;IService&gt;("key", (sp, key) => Factory(sp, key));</c></item>
    /// </list>
    /// If the factory return type differs from the service type, adds a cast.
    /// </remarks>
    private static void WriteFactoryMethodRegistration(SourceWriter writer, ServiceRegistrationModel registration, string lifetime)
    {
        var serviceTypeName = registration.ServiceType.Name;
        var factory = registration.Factory!;
        var factoryPath = factory.Path;
        var hasServiceProvider = factory.HasServiceProvider;
        // hasKey is only meaningful when registration has a key
        var hasKey = factory.HasKey && registration.Key is not null;
        var returnTypeName = factory.ReturnTypeName;

        // Build factory invocation based on parameters
        string factoryInvocation = (hasServiceProvider, hasKey) switch
        {
            (true, true) => $"{factoryPath}(sp, {registration.Key})",
            (true, false) => $"{factoryPath}(sp)",
            (false, true) => $"{factoryPath}({registration.Key})",
            (false, false) => $"{factoryPath}()"
        };

        // Add cast if return type differs from service type
        if(returnTypeName is not null && returnTypeName != serviceTypeName)
        {
            factoryInvocation = $"({serviceTypeName}){factoryInvocation}";
        }

        if(registration.Key is not null)
        {
            // Keyed registration with factory
            writer.WriteLine($"services.AddKeyed{lifetime}<{serviceTypeName}>({registration.Key}, (global::System.IServiceProvider sp, object? key) => {factoryInvocation});");
        }
        else if(hasServiceProvider)
        {
            // Non-keyed registration with factory
            writer.WriteLine($"services.Add{lifetime}<{serviceTypeName}>((global::System.IServiceProvider sp) => {factoryInvocation});");
        }
        else
        {
            // No parameters factory - direct invocation
            writer.WriteLine($"services.Add{lifetime}<{serviceTypeName}>({factoryInvocation});");
        }
    }

    /// <summary>
    /// Writes registration code using a static instance specified in the attribute.
    /// Instance registrations are only valid for Singleton lifetime.
    /// </summary>
    /// <remarks>
    /// Generates code like:
    /// <code>
    /// services.AddSingleton&lt;IMySrevice&gt;(MyService.Default);
    /// // or for keyed:
    /// services.AddKeyedSingleton&lt;IMySrevice&gt;("key", MyService.Default);
    /// </code>
    /// </remarks>
    private static void WriteInstanceRegistration(SourceWriter writer, ServiceRegistrationModel registration)
    {
        var serviceTypeName = registration.ServiceType.Name;
        var instance = registration.Instance!;

        // Instance registration should only be used with Singleton
        // The analyzer should catch invalid lifetime usage
        if(registration.Key is not null)
        {
            // Keyed singleton with instance
            writer.WriteLine($"services.AddKeyedSingleton<{serviceTypeName}>({registration.Key}, {instance});");
        }
        else
        {
            // Non-keyed singleton with instance
            writer.WriteLine($"services.AddSingleton<{serviceTypeName}>({instance});");
        }
    }

    /// <summary>
    /// Writes registration code for service types (interfaces/base classes) that forward to an already-registered implementation.
    /// The implementation is already registered with its own factory method, so we just resolve it from the service provider.
    /// </summary>
    /// <remarks>
    /// Generates code like:
    /// <code>
    /// services.AddTransient&lt;IMyService&gt;(sp => sp.GetRequiredService&lt;MyService&gt;());
    /// </code>
    /// </remarks>
    private static void WriteServiceTypeForwardingRegistration(SourceWriter writer, ServiceRegistrationModel registration, string lifetime)
    {
        var serviceTypeName = registration.ServiceType.Name;
        var implTypeName = registration.ImplementationType.Name;

        if(registration.Key is not null)
        {
            // Keyed registration - forward to keyed implementation
            writer.WriteLine($"services.AddKeyed{lifetime}<{serviceTypeName}>({registration.Key}, (global::System.IServiceProvider sp, object? key) => sp.GetRequiredKeyedService<{implTypeName}>(key));");
        }
        else
        {
            // Non-keyed registration - forward to implementation
            writer.WriteLine($"services.Add{lifetime}<{serviceTypeName}>((global::System.IServiceProvider sp) => sp.GetRequiredService<{implTypeName}>());");
        }
    }

    /// <summary>
    /// Writes registration code for services with injection members (properties, fields, methods marked with InjectAttribute).
    /// </summary>
    /// <remarks>
    /// Generates code like:
    /// <code>
    /// services.AddSingleton&lt;MyService&gt;((IServiceProvider sp) =>
    /// {
    ///     var s0_p0 = sp.GetRequiredService&lt;IMayServiceDependency1&gt;();
    ///     var s0_p1 = sp.GetRequiredService&lt;IMayServiceDependency2&gt;();
    ///     var s0_p2 = sp.GetRequiredService&lt;IMayServiceDependency3&gt;();
    ///     var s0 = new MyService(s0_p0) { Dependency = s0_p1 };
    ///     s0.Initialize(s0_p2);
    ///     return s0;
    /// });
    /// </code>
    /// For optional parameters with default values, generates conditional logic:
    /// <code>
    /// var p0 = sp.GetService&lt;IOptionalDep&gt;();
    /// var s0 = p0 is not null ? new MyService(optDep: p0) : new MyService();
    /// </code>
    /// </remarks>
    private static void WriteInjectionRegistration(SourceWriter writer, ServiceRegistrationModel registration, string lifetime)
    {
        var serviceTypeName = registration.ServiceType.Name;
        var implTypeName = registration.ImplementationType.Name;
        var injectionMembers = registration.InjectionMembers;

        // Build the factory lambda
        if(registration.Key is not null)
        {
            // Keyed registration with injection
            writer.WriteLine($"services.AddKeyed{lifetime}<{serviceTypeName}>({registration.Key}, (global::System.IServiceProvider sp, object? key) =>");
        }
        else
        {
            // Non-keyed registration with injection
            writer.WriteLine($"services.Add{lifetime}<{serviceTypeName}>((global::System.IServiceProvider sp) =>");
        }

        writer.WriteLine("{");
        writer.Indentation++;

        // Resolve constructor parameters
        var constructorParams = registration.ImplementationType.ConstructorParameters ?? [];
        var constructorParamEntries = new List<(string Name, string? Value, bool NeedsConditional)>(constructorParams.Length);
        bool isKeyedRegistration = registration.Key is not null;
        int paramIndex = 0;

        foreach(var param in constructorParams)
        {
            var paramVar = $"p{paramIndex}";
            var result = WriteParameterResolutionWithConditional(writer, param, paramVar, param.Type.Name, isKeyedRegistration, registration.Key);
            constructorParamEntries.Add((param.Name, result.VarName, result.NeedsConditional));
            paramIndex++;
        }

        // Count property/field and method members for pre-allocation
        int propertyFieldCount = 0;
        int methodCount = 0;
        foreach(var member in injectionMembers)
        {
            if(member.MemberType is InjectionMemberType.Property or InjectionMemberType.Field)
                propertyFieldCount++;
            else if(member.MemberType == InjectionMemberType.Method)
                methodCount++;
        }

        // Pre-allocate arrays based on counts
        var propertyInitializers = propertyFieldCount > 0 ? new (string Name, string ParamVar, bool NeedsConditional)[propertyFieldCount] : [];
        var methodCalls = methodCount > 0 ? new (string MethodName, string?[] ParamVars, string[] ParamNames, bool[] NeedsConditional)[methodCount] : [];

        // Process property/field injection parameters
        int propertyIndex = 0;
        int memberParamIndex = 0;
        foreach(var member in injectionMembers)
        {
            if(member.MemberType is not (InjectionMemberType.Property or InjectionMemberType.Field))
                continue;

            var paramVar = $"s0_p{memberParamIndex}";
            var memberType = member.Type;
            var memberTypeName = memberType?.Name ?? "object";

            // Determine if this member needs conditional handling
            // Property/Field with non-null default value needs conditional handling
            bool needsConditional = member.HasDefaultValue && !member.DefaultValueIsNull;

            if(member.Key is not null)
            {
                // Check for collection types with key
                if(memberType?.CollectionKind is not null and not CollectionKind.None)
                {
                    WriteCollectionResolution(writer, memberType, paramVar, member.Key, member.IsNullable);
                }
                else if(needsConditional)
                {
                    // Use GetKeyedService for conditional handling
                    writer.WriteLine($"var {paramVar} = sp.GetKeyedService<{memberTypeName}>({member.Key});");
                }
                else
                {
                    // Use GetService only if the type is nullable, regardless of default value
                    var getKeyedServiceMethod = member.IsNullable ? "GetKeyedService" : "GetRequiredKeyedService";
                    writer.WriteLine($"var {paramVar} = sp.{getKeyedServiceMethod}<{memberTypeName}>({member.Key});");
                }
            }
            else
            {
                // Check for collection types without key
                if(memberType?.CollectionKind is not null and not CollectionKind.None)
                {
                    WriteCollectionResolution(writer, memberType, paramVar, serviceKey: null, member.IsNullable);
                }
                else if(needsConditional)
                {
                    // Use GetService for conditional handling
                    writer.WriteLine($"var {paramVar} = sp.GetService<{memberTypeName}>();");
                }
                else
                {
                    // Use GetService only if the type is nullable, regardless of default value
                    var getServiceMethod = member.IsNullable ? "GetService" : "GetRequiredService";
                    writer.WriteLine($"var {paramVar} = sp.{getServiceMethod}<{memberTypeName}>();");
                }
            }

            propertyInitializers[propertyIndex++] = (member.Name, paramVar, needsConditional);
            memberParamIndex++;
        }

        // Process method injection parameters
        int methodIndex = 0;
        foreach(var method in injectionMembers)
        {
            if(method.MemberType != InjectionMemberType.Method)
                continue;

            var methodParams = method.Parameters ?? [];
            var methodParamVars = new string?[methodParams.Length];
            var methodParamNames = new string[methodParams.Length];
            var methodNeedsConditional = new bool[methodParams.Length];
            int methodParamIdx = 0;

            foreach(var param in methodParams)
            {
                var paramVar = $"s0_m{memberParamIndex}";
                methodParamNames[methodParamIdx] = param.Name;

                if(method.Key is not null)
                {
                    // Method has explicit key from [Inject] attribute
                    if(IsServiceProviderType(param.Type.Name))
                    {
                        methodParamVars[methodParamIdx] = "sp";
                        methodNeedsConditional[methodParamIdx] = false;
                    }
                    else if(param.HasServiceKeyAttribute)
                    {
                        // [ServiceKey] attribute - inject the class registration's key, not the method's key
                        methodParamVars[methodParamIdx] = WriteServiceKeyParameterResolution(
                            writer, paramVar, param.Type.Name, isKeyedRegistration, registration.Key);
                        methodNeedsConditional[methodParamIdx] = false;
                    }
                    else if(param.Type.CollectionKind is not CollectionKind.None)
                    {
                        // Collection type with method-level key
                        WriteCollectionResolution(writer, param.Type, paramVar, method.Key);
                        methodParamVars[methodParamIdx] = paramVar;
                        methodNeedsConditional[methodParamIdx] = false;
                    }
                    else if(param.HasDefaultValue && !param.Type.IsBuiltInTypeOrBuiltInCollection && !param.DefaultValueIsNull)
                    {
                        // Optional parameter with non-null default value and method-level key - use GetService and conditional
                        writer.WriteLine($"var {paramVar} = sp.GetKeyedService<{param.Type.Name}>({method.Key});");
                        methodParamVars[methodParamIdx] = paramVar;
                        methodNeedsConditional[methodParamIdx] = true;
                    }
                    else if(param.HasDefaultValue && param.Type.IsBuiltInTypeOrBuiltInCollection)
                    {
                        // Built-in type with default value - skip
                        methodParamVars[methodParamIdx] = null;
                        methodNeedsConditional[methodParamIdx] = false;
                    }
                    else if(param.HasDefaultValue && param.DefaultValueIsNull)
                    {
                        // Default value is null - use GetKeyedService directly without conditional
                        writer.WriteLine($"var {paramVar} = sp.GetKeyedService<{param.Type.Name}>({method.Key});");
                        methodParamVars[methodParamIdx] = paramVar;
                        methodNeedsConditional[methodParamIdx] = false;
                    }
                    else
                    {
                        writer.WriteLine($"var {paramVar} = sp.GetRequiredKeyedService<{param.Type.Name}>({method.Key});");
                        methodParamVars[methodParamIdx] = paramVar;
                        methodNeedsConditional[methodParamIdx] = false;
                    }
                    methodParamIdx++;
                }
                else
                {
                    var result = WriteParameterResolutionWithConditional(writer, param, paramVar, param.Type.Name, isKeyedRegistration, registration.Key);
                    methodParamVars[methodParamIdx] = result.VarName;
                    methodNeedsConditional[methodParamIdx] = result.NeedsConditional;
                    methodParamIdx++;
                }
                memberParamIndex++;
            }

            methodCalls[methodIndex++] = (method.Name, methodParamVars, methodParamNames, methodNeedsConditional);
        }

        // Check if any constructor parameter needs conditional handling
        bool hasConditionalConstructorParams = constructorParamEntries.Any(e => e.NeedsConditional);

        // Split property initializers into unconditional and conditional
        var unconditionalPropertyInits = propertyInitializers.Where(p => !p.NeedsConditional).Select(p => $"{p.Name} = {p.ParamVar}").ToArray();
        var conditionalPropertyInits = propertyInitializers.Where(p => p.NeedsConditional).ToArray();

        // Create the instance with constructor and unconditional property initializers
        if(hasConditionalConstructorParams)
        {
            // Generate conditional construction using ternary operator pattern
            WriteConditionalConstruction(writer, implTypeName, constructorParamEntries, unconditionalPropertyInits);
        }
        else
        {
            // Use named arguments if any parameter uses default value (value is null)
            var constructorArgs = BuildArgumentListFromEntries(constructorParamEntries);

            if(unconditionalPropertyInits.Length > 0)
            {
                var initializerList = string.Join(", ", unconditionalPropertyInits);
                writer.WriteLine($"var s0 = new {implTypeName}({constructorArgs}) {{ {initializerList} }};");
            }
            else
            {
                writer.WriteLine($"var s0 = new {implTypeName}({constructorArgs});");
            }
        }

        // Apply conditional property/field assignments
        foreach(var (propName, paramVar, _) in conditionalPropertyInits)
        {
            writer.WriteLine($"if ({paramVar} is not null)");
            writer.WriteLine("{");
            writer.Indentation++;
            writer.WriteLine($"s0.{propName} = {paramVar};");
            writer.Indentation--;
            writer.WriteLine("}");
        }

        // Call injection methods
        foreach(var (methodName, methodParamVars, methodParamNames, methodNeedsConditional) in methodCalls)
        {
            // Check if any method parameter needs conditional handling
            bool hasConditionalMethodParams = methodNeedsConditional.Any(c => c);

            if(hasConditionalMethodParams)
            {
                // Generate conditional method call
                WriteConditionalMethodCall(writer, methodName, methodParamVars, methodParamNames, methodNeedsConditional);
            }
            else
            {
                var methodEntries = new List<(string Name, string? Value, bool NeedsConditional)>(methodParamVars.Length);
                for(int i = 0; i < methodParamVars.Length; i++)
                {
                    methodEntries.Add((methodParamNames[i], methodParamVars[i], false));
                }
                var methodArgs = BuildArgumentListFromEntries(methodEntries);
                writer.WriteLine($"s0.{methodName}({methodArgs});");
            }
        }

        // Return the instance
        writer.WriteLine("return s0;");

        writer.Indentation--;
        writer.WriteLine("});");
    }

    /// <summary>
    /// Writes conditional construction code when some constructor parameters need conditional handling.
    /// Generates code like:
    /// <code>
    /// var s0 = p0 is not null ? new MyService(optDep: p0) : new MyService();
    /// </code>
    /// For multiple conditional parameters, uses nested ternary or if-else blocks.
    /// </summary>
    private static void WriteConditionalConstruction(
        SourceWriter writer,
        string implTypeName,
        List<(string Name, string? Value, bool NeedsConditional)> paramEntries,
        string[] propertyInitializers)
    {
        var conditionalParams = paramEntries.Where(e => e.NeedsConditional && e.Value is not null).ToList();
        var initializerPart = propertyInitializers.Length > 0
            ? $" {{ {string.Join(", ", propertyInitializers)} }}"
            : "";

        if(conditionalParams.Count == 1)
        {
            // Single conditional parameter - use simple ternary
            var condParam = conditionalParams[0];
            var withArgsEntries = paramEntries.Select(e => (e.Name, e.NeedsConditional ? e.Value : e.Value, false)).ToList();
            var withoutArgsEntries = paramEntries.Select(e => (e.Name, e.NeedsConditional ? (string?)null : e.Value, false)).ToList();

            var withArgs = BuildArgumentListFromEntries(withArgsEntries);
            var withoutArgs = BuildArgumentListFromEntries(withoutArgsEntries);

            writer.WriteLine($"var s0 = {condParam.Value} is not null ? new {implTypeName}({withArgs}){initializerPart} : new {implTypeName}({withoutArgs}){initializerPart};");
        }
        else
        {
            // Multiple conditional parameters - generate if-else chain
            // Build all possible combinations would be exponential, so we use a simpler approach:
            // Check each conditional param and add to args if not null
            writer.WriteLine($"{implTypeName} s0;");

            // Generate condition check
            var conditions = conditionalParams.Select(p => $"{p.Value} is not null").ToList();
            var allCondition = string.Join(" && ", conditions);

            // Generate the "all not null" case
            writer.WriteLine($"if ({allCondition})");
            writer.WriteLine("{");
            writer.Indentation++;
            var allArgs = BuildArgumentListFromEntries(paramEntries.Select(e => (e.Name, e.Value, false)).ToList());
            writer.WriteLine($"s0 = new {implTypeName}({allArgs}){initializerPart};");
            writer.Indentation--;
            writer.WriteLine("}");

            // Generate the "fallback" case (only non-conditional params)
            writer.WriteLine("else");
            writer.WriteLine("{");
            writer.Indentation++;
            var fallbackArgs = BuildArgumentListFromEntries(paramEntries.Select(e => (e.Name, e.NeedsConditional ? (string?)null : e.Value, false)).ToList());
            writer.WriteLine($"s0 = new {implTypeName}({fallbackArgs}){initializerPart};");
            writer.Indentation--;
            writer.WriteLine("}");
        }
    }

    /// <summary>
    /// Writes conditional method call when some parameters need conditional handling.
    /// </summary>
    private static void WriteConditionalMethodCall(
        SourceWriter writer,
        string methodName,
        string?[] paramVars,
        string[] paramNames,
        bool[] needsConditional)
    {
        var conditionalIndices = new List<int>();
        for(int i = 0; i < needsConditional.Length; i++)
        {
            if(needsConditional[i] && paramVars[i] is not null)
            {
                conditionalIndices.Add(i);
            }
        }

        if(conditionalIndices.Count == 1)
        {
            // Single conditional parameter - use simple if
            var idx = conditionalIndices[0];
            var condVar = paramVars[idx]!;

            writer.WriteLine($"if ({condVar} is not null)");
            writer.WriteLine("{");
            writer.Indentation++;

            var withArgs = BuildMethodArgumentList(paramVars, paramNames, i => true);
            writer.WriteLine($"s0.{methodName}({withArgs});");

            writer.Indentation--;
            writer.WriteLine("}");
            writer.WriteLine("else");
            writer.WriteLine("{");
            writer.Indentation++;

            var withoutArgs = BuildMethodArgumentList(paramVars, paramNames, i => !needsConditional[i]);
            writer.WriteLine($"s0.{methodName}({withoutArgs});");

            writer.Indentation--;
            writer.WriteLine("}");
        }
        else
        {
            // Multiple conditional parameters
            var conditions = conditionalIndices.Select(i => $"{paramVars[i]} is not null").ToList();
            var allCondition = string.Join(" && ", conditions);

            writer.WriteLine($"if ({allCondition})");
            writer.WriteLine("{");
            writer.Indentation++;
            var allArgs = BuildMethodArgumentList(paramVars, paramNames, i => true);
            writer.WriteLine($"s0.{methodName}({allArgs});");
            writer.Indentation--;
            writer.WriteLine("}");

            writer.WriteLine("else");
            writer.WriteLine("{");
            writer.Indentation++;
            var fallbackArgs = BuildMethodArgumentList(paramVars, paramNames, i => !needsConditional[i]);
            writer.WriteLine($"s0.{methodName}({fallbackArgs});");
            writer.Indentation--;
            writer.WriteLine("}");
        }
    }

    /// <summary>
    /// Builds a method argument list based on which parameters to include.
    /// </summary>
    private static string BuildMethodArgumentList(string?[] paramVars, string[] paramNames, Func<int, bool> includeParam)
    {
        bool hasExcluded = false;
        for(int i = 0; i < paramVars.Length; i++)
        {
            if(!includeParam(i) || paramVars[i] is null)
            {
                hasExcluded = true;
                break;
            }
        }

        if(!hasExcluded)
        {
            // All parameters included - use positional
            var values = new List<string>(paramVars.Length);
            for(int i = 0; i < paramVars.Length; i++)
            {
                if(paramVars[i] is not null)
                {
                    values.Add(paramVars[i]!);
                }
            }
            return string.Join(", ", values);
        }

        // Some parameters excluded - use named arguments for included ones
        var namedArgs = new List<string>(paramVars.Length);
        for(int i = 0; i < paramVars.Length; i++)
        {
            if(includeParam(i) && paramVars[i] is not null)
            {
                namedArgs.Add($"{paramNames[i]}: {paramVars[i]}");
            }
        }
        return string.Join(", ", namedArgs);
    }

    /// <summary>
    /// Builds an argument list from entries with conditional flag.
    /// </summary>
    private static string BuildArgumentListFromEntries(List<(string Name, string? Value, bool NeedsConditional)> entries)
    {
        // Check if any parameter uses default value
        bool hasDefaultValue = entries.Any(e => e.Value is null);

        if(!hasDefaultValue)
        {
            // All values present - use positional arguments
            return string.Join(", ", entries.Select(e => e.Value!));
        }

        // Some values are null - use named arguments for non-null values only
        var namedArgs = entries.Where(e => e.Value is not null).Select(e => $"{e.Name}: {e.Value}").ToList();
        return string.Join(", ", namedArgs);
    }

    /// <summary>
    /// Converts a TypeData to typeof() syntax for open generic types.
    /// For example: TypeData with Name="global::Namespace.GenericTest&lt;T&gt;" becomes "typeof(global::Namespace.GenericTest&lt;&gt;)"
    /// </summary>
    private static string ConvertToTypeOf(TypeData typeData)
    {
        if(typeData.GenericArity == 0)
        {
            return $"typeof({typeData.Name})";
        }

        // Build the open generic typeof
        return $"typeof({typeData.NameWithoutGeneric}{GetGenericString(typeData.GenericArity)})";
    }

    /// <summary>
    /// Cached generic arity strings to avoid repeated allocations.
    /// </summary>
    private static readonly string[] s_genericArityStrings =
    [
        "<>",
        "<,>",
        "<,,>",
        "<,,,>",
        "<,,,,>",
        "<,,,,,>",
        "<,,,,,,>",
        "<,,,,,,,>",
        "<,,,,,,,,>"
    ];

    private static string GetGenericString(in int arity) =>
        arity <= 9 ? s_genericArityStrings[arity - 1] : '<' + new string(',', arity - 1) + '>';

    /// <summary>
    /// Writes decorator pattern registration code.
    /// </summary>
    /// <remarks>
    /// Generates code like:
    /// <code>
    /// services.AddSingleton&lt;IMyService&gt;((IServiceProvider sp) =>
    /// {
    ///     var s0 = sp.GetRequiredService&lt;MyService&gt;();
    ///     var s1_p0 = sp.GetRequiredService&lt;ILogger&lt;MyServiceDecorator2&gt;&gt;();
    ///     var s1 = new MyServiceDecorator2(s1_p0, s0);
    ///     var s2_p0 = sp.GetRequiredService&lt;ILogger&lt;MyServiceDecorator&gt;&gt;();
    ///     var s2 = new MyServiceDecorator(s2_p0, s1);
    ///     return s2;
    /// });
    /// </code>
    /// For open generic decorators, falls back to ActivatorUtilities.CreateInstance.
    /// </remarks>
    private static void WriteDecoratorRegistration(SourceWriter writer, ServiceRegistrationModel registration, string lifetime)
    {
        var decorators = registration.Decorators;
        // Decorators array is in order from outermost to innermost,
        // we iterate in reverse order for building the chain from inner to outer
        var decoratorCount = decorators.Length;

        // Get generic arguments from the service type (for closed generic service types)
        var serviceTypeParams = registration.ServiceType.TypeParameters;
        var serviceTypeName = registration.ServiceType.Name;

        // Build service type names set for IsServiceParameter check
        var serviceTypeNames = BuildServiceTypeNames(registration);

        if(registration.Key is not null)
        {
            writer.WriteLine($"services.AddKeyed{lifetime}<{serviceTypeName}>({registration.Key}, (global::System.IServiceProvider sp, object? key) =>");
        }
        else
        {
            writer.WriteLine($"services.Add{lifetime}<{serviceTypeName}>((global::System.IServiceProvider sp) =>");
        }

        writer.WriteLine("{");
        writer.Indentation++;

        // s0 = implementation instance
        if(registration.Key is not null)
        {
            writer.WriteLine($"var s0 = sp.GetRequiredKeyedService<{registration.ImplementationType.Name}>(key);");
        }
        else
        {
            writer.WriteLine($"var s0 = sp.GetRequiredService<{registration.ImplementationType.Name}>();");
        }

        // Build decorator chain (iterate in reverse order: from innermost to outermost)
        for(int i = 0; i < decoratorCount; i++)
        {
            // Access decorators in reverse order
            var decorator = decorators[decoratorCount - 1 - i];
            var prevVar = $"s{i}";
            var currentVar = $"s{i + 1}";

            // If the decorator is an open generic, substitute with the service type's generic arguments
            var decoratorTypeName = GetClosedDecoratorTypeName(decorator, serviceTypeParams);

            // Get constructor parameters and generate service resolution for each
            var constructorParams = decorator.ConstructorParameters ?? [];
            if(constructorParams.Length == 0)
            {
                // No constructor info available, use ActivatorUtilities as fallback (Shouldn't reach here)
                writer.WriteLine($"var {currentVar} = global::Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance<{decoratorTypeName}>(sp, {prevVar});");
            }
            else
            {
                // Resolve each non-service parameter from IServiceProvider
                var paramVars = new string[constructorParams.Length];
                int paramIndex = 0;
                int paramVarIndex = 0;
                foreach(var param in constructorParams)
                {
                    // Check if this parameter is the service type being decorated
                    // For open generic decorators, substitute type parameters first
                    var paramTypeName = decorator.IsOpenGeneric && serviceTypeParams is not null
                        ? SubstituteGenericArguments(param.Type, decorator, serviceTypeParams)
                        : param.Type.Name;

                    if(IsServiceTypeParameter(param.Type, paramTypeName, serviceTypeNames))
                    {
                        // This is the decorated service, use the previous variable
                        paramVars[paramVarIndex++] = prevVar;
                    }
                    else
                    {
                        // This is a dependency, resolve it from service provider
                        var paramVar = $"{currentVar}_p{paramIndex}";
                        bool isKeyedRegistration = registration.Key is not null;
                        var resolvedVar = WriteParameterResolution(writer, param, paramVar, paramTypeName, isKeyedRegistration, registration.Key);
                        // Use named argument if parameter uses default value (null means use default)
                        paramVars[paramVarIndex++] = resolvedVar is not null ? resolvedVar : $"{param.Name}: default";
                        paramIndex++;
                    }
                }

                // Create the decorator instance with resolved parameters
                var paramList = string.Join(", ", paramVars);
                writer.WriteLine($"var {currentVar} = new {decoratorTypeName}({paramList});");
            }
        }

        // Return the outermost decorator
        writer.WriteLine($"return s{decoratorCount};");

        writer.Indentation--;
        writer.WriteLine("});");
    }

    /// <summary>
    /// Gets the closed decorator type name by substituting generic arguments if the decorator is an open generic.
    /// </summary>
    /// <param name="decorator">The decorator type data.</param>
    /// <param name="serviceTypeParams">The type parameters from the service type.</param>
    /// <returns>The closed decorator type name.</returns>
    private static string GetClosedDecoratorTypeName(TypeData decorator, ImmutableEquatableArray<TypeParameter>? serviceTypeParams)
    {
        // If decorator is not open generic, return as-is
        if(!decorator.IsOpenGeneric)
        {
            return decorator.Name;
        }

        // If no generic arguments available from service type, return as-is (this shouldn't happen in valid scenarios)
        if(serviceTypeParams is null || serviceTypeParams.Length == 0)
        {
            return decorator.Name;
        }

        // Replace the open generic parameters with the service type's generic arguments
        // e.g., "global::Namespace.Decorator<TRequest, TResponse>" -> "global::Namespace.Decorator<global::Ns.TestRequest, global::Ns.TestResponse>"
        return $"{decorator.NameWithoutGeneric}<{string.Join(", ", serviceTypeParams.Select(a => a.Type.Name))}>";
    }

    /// <summary>
    /// Substitutes generic type parameters in a parameter type with actual generic arguments.
    /// </summary>
    /// <param name="paramType">The parameter type data that may contain type parameters.</param>
    /// <param name="decorator">The decorator type data containing type parameter information.</param>
    /// <param name="serviceTypeParams">The type parameters from the service type.</param>
    /// <returns>The type name with substituted generic arguments.</returns>
    private static string SubstituteGenericArguments(TypeData paramType, TypeData decorator, ImmutableEquatableArray<TypeParameter> serviceTypeParams)
    {
        // Use pre-extracted type arguments from TypeData
        var decoratorTypeParams = decorator.TypeParameters;
        if(decoratorTypeParams is null || decoratorTypeParams.Length == 0)
        {
            return paramType.Name;
        }

        if(serviceTypeParams.Length != decoratorTypeParams.Length)
        {
            // Mismatch in arity, return original
            return paramType.Name;
        }

        // Build replacement map and apply substitutions
        var result = paramType.Name;
        for(int i = 0; i < decoratorTypeParams.Length; i++)
        {
            // Replace type parameter with actual argument from service type
            // Need to be careful to replace whole type names, not partial matches
            result = ReplaceTypeParameter(result, decoratorTypeParams[i].ParameterName, serviceTypeParams[i].Type.Name);
        }

        return result;
    }

    /// <summary>
    /// Builds a set of service type names for IsServiceParameter check.
    /// Includes the service type, implementation type, all base classes, and all interfaces.
    /// This ensures decorator parameters that reference any service type are correctly identified.
    /// </summary>
    private static HashSet<string> BuildServiceTypeNames(ServiceRegistrationModel registration)
    {
        var serviceTypeNames = new HashSet<string>(StringComparer.Ordinal);

        // Add service type variants
        AddTypeNameVariants(serviceTypeNames, registration.ServiceType);

        // Add implementation type variants
        AddTypeNameVariants(serviceTypeNames, registration.ImplementationType);

        // Add all base classes (important for decorator parameter matching)
        if(registration.ImplementationType.AllBaseClasses is not null)
        {
            foreach(var baseClass in registration.ImplementationType.AllBaseClasses)
            {
                AddTypeNameVariants(serviceTypeNames, baseClass);
            }
        }

        // Add all interfaces (important when multiple service types exist)
        if(registration.ImplementationType.AllInterfaces is not null)
        {
            foreach(var iface in registration.ImplementationType.AllInterfaces)
            {
                AddTypeNameVariants(serviceTypeNames, iface);
            }
        }

        return serviceTypeNames;
    }

    /// <summary>
    /// Adds both the full name and non-generic name variants to the set.
    /// </summary>
    private static void AddTypeNameVariants(HashSet<string> set, TypeData type)
    {
        set.Add(type.Name);
        if(type.Name != type.NameWithoutGeneric)
        {
            set.Add(type.NameWithoutGeneric);
        }
    }

    /// <summary>
    /// Checks if a parameter type matches any of the service types.
    /// </summary>
    private static bool IsServiceTypeParameter(TypeData paramType, string substitutedTypeName, HashSet<string> serviceTypeNames)
    {
        // Check substituted type name first (for open generic decorators)
        if(serviceTypeNames.Contains(substitutedTypeName))
        {
            return true;
        }

        // Direct match on full name or non-generic name
        return serviceTypeNames.Contains(paramType.Name)
            || serviceTypeNames.Contains(paramType.NameWithoutGeneric);
    }

    /// <summary>
    /// Result of parameter resolution containing the variable name and whether it needs conditional handling.
    /// </summary>
    /// <param name="VarName">The variable name or expression to use for this parameter, or null if the parameter should use its default value.</param>
    /// <param name="NeedsConditional">Whether this parameter needs conditional handling (only use if not null).</param>
    private readonly record struct ParameterResolutionResult(string? VarName, bool NeedsConditional = false);

    /// <summary>
    /// Writes parameter resolution code and returns the variable name to use.
    /// Handles special cases: IServiceProvider, [FromKeyedServices], [Inject] with key, [ServiceKey], and keyed service key parameter.
    /// </summary>
    /// <param name="writer">The source writer.</param>
    /// <param name="param">The parameter data.</param>
    /// <param name="paramVar">The variable name for this parameter.</param>
    /// <param name="paramTypeName">The resolved parameter type name (for generic substitution).</param>
    /// <param name="isKeyedRegistration">Whether this is a keyed service registration.</param>
    /// <param name="registrationKey">The registration key for keyed services, used for [ServiceKey] parameter injection.</param>
    /// <returns>The variable name or expression to use for this parameter, or null if the parameter should use its default value.</returns>
    private static string? WriteParameterResolution(
        SourceWriter writer,
        ParameterData param,
        string paramVar,
        string paramTypeName,
        bool isKeyedRegistration,
        string? registrationKey = null)
    {
        var result = WriteParameterResolutionWithConditional(writer, param, paramVar, paramTypeName, isKeyedRegistration, registrationKey);
        return result.VarName;
    }

    /// <summary>
    /// Writes parameter resolution code and returns the result with conditional handling information.
    /// </summary>
    private static ParameterResolutionResult WriteParameterResolutionWithConditional(
        SourceWriter writer,
        ParameterData param,
        string paramVar,
        string paramTypeName,
        bool isKeyedRegistration,
        string? registrationKey = null)
    {
        // Skip built-in type parameters with default values - let them use their default value
        if(param.HasDefaultValue && param.Type.IsBuiltInTypeOrBuiltInCollection)
        {
            return new ParameterResolutionResult(null, false);
        }

        // Case 1: IServiceProvider - pass sp directly
        if(IsServiceProviderType(paramTypeName))
        {
            return new ParameterResolutionResult("sp", false);
        }

        // Case 2: [ServiceKey] attribute - inject the registration key
        // Must check before collection resolution since string implements IEnumerable<char>
        if(param.HasServiceKeyAttribute)
        {
            var keyVar = WriteServiceKeyParameterResolution(writer, paramVar, paramTypeName, isKeyedRegistration, registrationKey);
            return new ParameterResolutionResult(keyVar, false);
        }

        // Case 3: Non-IEnumerable collection types (IList<T>, T[], IReadOnlyList<T>, etc.)
        // OR IEnumerable<T> without [FromKeyedServices] key (MS.DI can handle [FromKeyedServices] + IEnumerable<T> automatically)
        // Use CollectionKind to determine resolution method
        var collectionKind = param.Type.CollectionKind;
        var needsManualCollectionResolution = collectionKind is not CollectionKind.None &&
            (collectionKind is not CollectionKind.Enumerable || param.ServiceKey is null);

        if(needsManualCollectionResolution)
        {
            WriteCollectionResolution(writer, param.Type, paramVar, param.ServiceKey, param.IsOptional);
            return new ParameterResolutionResult(paramVar, false);
        }

        // Case 4: [FromKeyedServices] or [Inject] attribute with key - use the specified key
        if(param.ServiceKey is not null)
        {
            // For optional parameters with default values (non-null default), use GetService and conditional handling
            // If default value is null, GetService returning null is equivalent to using default, so no conditional needed
            if(param.HasDefaultValue && !param.DefaultValueIsNull)
            {
                writer.WriteLine($"var {paramVar} = sp.GetKeyedService<{paramTypeName}>({param.ServiceKey});");
                return new ParameterResolutionResult(paramVar, true);
            }

            var getKeyedServiceMethod = param.IsOptional ? "GetKeyedService" : "GetRequiredKeyedService";
            writer.WriteLine($"var {paramVar} = sp.{getKeyedServiceMethod}<{paramTypeName}>({param.ServiceKey});");
            return new ParameterResolutionResult(paramVar, false);
        }

        // Case 5: Parameter with default value (resolvable type) - use GetService and conditional handling
        // If default value is null, GetService returning null is equivalent to using default, so no conditional needed
        if(param.HasDefaultValue && !param.DefaultValueIsNull)
        {
            writer.WriteLine($"var {paramVar} = sp.GetService<{paramTypeName}>();");
            return new ParameterResolutionResult(paramVar, true);
        }

        // Default: resolve from service provider
        var getServiceMethod = param.IsOptional ? "GetService" : "GetRequiredService";
        writer.WriteLine($"var {paramVar} = sp.{getServiceMethod}<{paramTypeName}>();");
        return new ParameterResolutionResult(paramVar, false);
    }

    /// <summary>
    /// Writes parameter resolution code for [ServiceKey] attribute.
    /// When the service is registered as keyed, injects the registration key with appropriate type casting.
    /// When the service is not keyed, injects null.
    /// </summary>
    /// <param name="writer">The source writer.</param>
    /// <param name="paramVar">The variable name for this parameter.</param>
    /// <param name="paramTypeName">The resolved parameter type name.</param>
    /// <param name="isKeyedRegistration">Whether this is a keyed service registration.</param>
    /// <param name="registrationKey">The registration key for keyed services.</param>
    /// <returns>The variable name or expression to use for this parameter.</returns>
    private static string WriteServiceKeyParameterResolution(
        SourceWriter writer,
        string paramVar,
        string paramTypeName,
        bool isKeyedRegistration,
        string? registrationKey)
    {
        if(isKeyedRegistration && registrationKey is not null)
        {
            writer.WriteLine($"var {paramVar} = {registrationKey};");
        }
        else
        {
            // Non-keyed registration: use the default value for the key type
            writer.WriteLine($"var {paramVar} = default({paramTypeName});");
        }
        return paramVar;
    }

    /// <summary>
    /// Writes collection resolution code for constructor parameters and injection members.
    /// Handles all collection types including IEnumerable&lt;T&gt;, IList&lt;T&gt;, T[], IReadOnlyList&lt;T&gt;, etc.
    /// </summary>
    /// <param name="writer">The source writer.</param>
    /// <param name="type">The type data of the collection.</param>
    /// <param name="paramVar">The variable name for this parameter.</param>
    /// <param name="serviceKey">The service key (null for non-keyed services).</param>
    /// <param name="isOptional">Whether the parameter is optional (uses GetService instead of GetRequiredService).</param>
    private static void WriteCollectionResolution(
        SourceWriter writer,
        TypeData type,
        string paramVar,
        string? serviceKey,
        bool isOptional = false)
    {
        var elementType = type.TryGetElementType();
        var isKeyed = serviceKey is not null;

        if(elementType is null)
        {
            // Fallback: couldn't determine element type, use direct service resolution
            if(isKeyed)
            {
                var method = isOptional ? "GetKeyedService" : "GetRequiredKeyedService";
                writer.WriteLine($"var {paramVar} = sp.{method}<{type.Name}>({serviceKey});");
            }
            else
            {
                var method = isOptional ? "GetService" : "GetRequiredService";
                writer.WriteLine($"var {paramVar} = sp.{method}<{type.Name}>();");
            }
            return;
        }

        var elementTypeName = elementType.Name;

        // Use CollectionKind to determine the resolution method
        switch(type.CollectionKind)
        {
            case CollectionKind.Enumerable:
                // IEnumerable<T> - use GetServices directly
                if(isKeyed)
                {
                    writer.WriteLine($"var {paramVar} = sp.GetKeyedServices<{elementTypeName}>({serviceKey});");
                }
                else
                {
                    writer.WriteLine($"var {paramVar} = sp.GetServices<{elementTypeName}>();");
                }
                break;

            case CollectionKind.ReadOnlyCollection:
                // IReadOnlyCollection<T>, IReadOnlyList<T>, T[] - resolve as array
                if(isKeyed)
                {
                    writer.WriteLine($"var {paramVar} = sp.GetKeyedServices<{elementTypeName}>({serviceKey}).ToArray();");
                }
                else
                {
                    writer.WriteLine($"var {paramVar} = sp.GetServices<{elementTypeName}>().ToArray();");
                }
                break;

            default:
                // Fallback for unknown collection types
                if(isKeyed)
                {
                    var method = isOptional ? "GetKeyedService" : "GetRequiredKeyedService";
                    writer.WriteLine($"var {paramVar} = sp.{method}<{type.Name}>({serviceKey});");
                }
                else
                {
                    var method = isOptional ? "GetService" : "GetRequiredService";
                    writer.WriteLine($"var {paramVar} = sp.{method}<{type.Name}>();");
                }
                break;
        }
    }

    /// <summary>
    /// Checks if the type name represents System.IServiceProvider.
    /// </summary>
    private static bool IsServiceProviderType(string typeName) =>
        typeName is "global::System.IServiceProvider" or "System.IServiceProvider" or "IServiceProvider";
}