using System.Diagnostics.CodeAnalysis;
using Microsoft.Extensions.DependencyInjection;

namespace SourceGen.Ioc;

/// <summary>
/// Interface for IoC containers generated by SourceGen.Ioc.
/// Provides access to all registered services and their factory functions.
/// </summary>
/// <typeparam name="TContainer">The Container class itself.</typeparam>
public interface IIocContainer<TContainer> :
    IServiceProvider,
    ISupportRequiredService,
    IKeyedServiceProvider,
    IServiceProviderIsService,
    IServiceProviderIsKeyedService,
    IServiceScopeFactory,
    IDisposable,
    IAsyncDisposable
    where TContainer : IIocContainer<TContainer>
{
    /// <summary>
    /// Gets all resolvers with their composite keys and factory functions.<br/>
    /// The key is a <see cref="ServiceIdentifier"/> where Key is <see cref="KeyedService.AnyKey"/>
    /// for non-keyed services.<br/>
    /// The factory function takes the container instance and returns the resolver.
    /// </summary>
    [Experimental("SGIOCEXP001", Message = "This API is used by SourceGen.Ioc and may change or be removed in future versions.")]
    public IReadOnlyCollection<KeyValuePair<ServiceIdentifier, Func<TContainer, object>>> Resolvers { get; }

    /// <inheritdoc cref="ServiceProviderServiceExtensions.GetService{T}"/>
    public T? GetService<T>()
        where T : class;

    /// <inheritdoc cref="ServiceProviderServiceExtensions.GetRequiredService{T}"/>
    public T? GetRequiredService<T>()
        where T : notnull;

    /// <inheritdoc cref="ServiceProviderServiceExtensions.GetServices{T}"/>
    public IEnumerable<T> GetServices<T>();

    /// <inheritdoc cref="ServiceProviderKeyedServiceExtensions.GetKeyedService{T}"/>
    public T? GetKeyedService<T>(object? serviceKey)
        where T : class;

    /// <inheritdoc cref="ServiceProviderKeyedServiceExtensions.GetRequiredKeyedService{T}"/>
    public T GetRequiredKeyedService<T>(object? serviceKey)
        where T : notnull;

    /// <inheritdoc cref="ServiceProviderKeyedServiceExtensions.GetKeyedServices{T}"/>
    public IEnumerable<T> GetKeyedServices<T>(object? serviceKey);
}
