namespace SourceGen.Ioc;

/// <summary>
/// Global options for IoC containers generated by SourceGen.Ioc.
/// </summary>
public static class IocContainerGlobalOptions
{
    /// <summary>
    /// Gets or sets an action to be called when an exception occurs during disposal of a <see cref="Task{T}"/> service.
    /// Set this to a logging delegate to capture disposal errors.
    /// </summary>
    public static Action<Exception>? OnDisposeException { get; set; }
}
