using static SourceGen.Ioc.SourceGenerator.Models.Constants;

namespace SourceGen.Ioc;

partial class IocSourceGenerator
{
    private static void GenerateRegisterOutput(
        in SourceProductionContext ctx,
        RegisterOutputModel model)
    {
        var source = GenerateExtensionMethodSource(model);
        ctx.AddSource($"{model.AssemblyName}.ServiceRegistration.g.cs", source);
    }

    private static string GenerateExtensionMethodSource(
        RegisterOutputModel model)
    {
        // Build the final output
        var mainWriter = new SourceWriter();

        mainWriter.WriteLine(AutoGeneratedHeader);
        mainWriter.WriteLine(NullableEnable);
        mainWriter.WriteLine();
        mainWriter.WriteLine("using Microsoft.Extensions.DependencyInjection;");
        mainWriter.WriteLine("using System.Collections.Generic;");
        mainWriter.WriteLine("using System.Linq;");
        mainWriter.WriteLine();

        mainWriter.WriteLine($"namespace {GetSafeNamespace(model.RootNamespace)}");
        mainWriter.WriteLine("{");
        mainWriter.Indentation++;

        mainWriter.WriteLine("/// <summary>");
        mainWriter.WriteLine($"/// Extension methods for registering services from {model.AssemblyName}.");
        mainWriter.WriteLine("/// </summary>");
        mainWriter.WriteLine($"public static class {model.MethodBaseName}ServiceCollectionExtensions");
        mainWriter.WriteLine("{");
        mainWriter.Indentation++;

        // Generate single method with tags parameter
        mainWriter.WriteLine("/// <summary>");
        mainWriter.WriteLine("/// Registers services. Services with tags are only registered when matching tags are passed.");
        mainWriter.WriteLine("/// </summary>");
        mainWriter.WriteLine("/// <param name=\"services\">The service collection.</param>");
        mainWriter.WriteLine("/// <param name=\"tags\">Optional tags to filter which services to register.</param>");
        mainWriter.WriteLine($"public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection Add{model.MethodBaseName}(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services, params global::System.Collections.Generic.IEnumerable<string> tags)");
        mainWriter.WriteLine("{");
        mainWriter.Indentation++;

        var context = new RegisterWriteContext(model.AsyncInitServiceTypes);

        bool isFirstGroup = true;
        foreach(var group in model.TagGroups)
        {
            if(!isFirstGroup)
            {
                mainWriter.WriteLine();
            }
            isFirstGroup = false;

            if(group.Tags.Length == 0)
            {
                // No tags - only register when no tags passed (mutually exclusive model)
                WriteNoTagConditionalBlock(mainWriter, group.Registrations, group.LazyEntries, group.FuncEntries, group.KvpEntries, context);
            }
            else
            {
                // Has tags - only register when tags match
                WriteConditionalTagBlock(mainWriter, group.Tags, group.Registrations, group.LazyEntries, group.FuncEntries, group.KvpEntries, context);
            }
        }

        mainWriter.WriteLine();
        mainWriter.WriteLine("return services;");

        mainWriter.Indentation--;
        mainWriter.WriteLine("}");

        mainWriter.Indentation--;
        mainWriter.WriteLine("}");

        mainWriter.Indentation--;
        mainWriter.WriteLine("}");

        return mainWriter.ToString();
    }

    /// <summary>
    /// Writes a conditional block for tag-based registration.
    /// Services with tags are only registered when the passed tags match.
    /// </summary>
    private static void WriteConditionalTagBlock(
        SourceWriter writer,
        ImmutableEquatableArray<string> tags,
        ImmutableEquatableArray<RegisterEntry> registrations,
        ImmutableEquatableArray<LazyRegistrationEntry> lazyEntries,
        ImmutableEquatableArray<FuncRegistrationEntry> funcEntries,
        ImmutableEquatableArray<KvpRegistrationEntry> kvpEntries,
        RegisterWriteContext context)
    {
        // Build the condition - only register when tags match
        var tagConditions = tags.Select(static tag => $"tags.Contains(\"{tag}\")");
        var condition = string.Join(" || ", tagConditions);

        writer.WriteLine($"if ({condition})");
        writer.WriteLine("{");
        writer.Indentation++;

        foreach(var registration in registrations)
        {
            registration.WriteRegistration(writer, context);
        }

        WriteLazyRegistrations(writer, lazyEntries);
        WriteFuncRegistrations(writer, funcEntries);
        WriteKvpRegistrations(writer, kvpEntries);

        writer.Indentation--;
        writer.WriteLine("}");
    }

    /// <summary>
    /// Writes a conditional block for services without tags.
    /// Services without tags are only registered when no tags are passed (mutually exclusive model).
    /// </summary>
    private static void WriteNoTagConditionalBlock(
        SourceWriter writer,
        ImmutableEquatableArray<RegisterEntry> registrations,
        ImmutableEquatableArray<LazyRegistrationEntry> lazyEntries,
        ImmutableEquatableArray<FuncRegistrationEntry> funcEntries,
        ImmutableEquatableArray<KvpRegistrationEntry> kvpEntries,
        RegisterWriteContext context)
    {
        writer.WriteLine("if (!tags.Any())");
        writer.WriteLine("{");
        writer.Indentation++;

        foreach(var registration in registrations)
        {
            registration.WriteRegistration(writer, context);
        }

        WriteLazyRegistrations(writer, lazyEntries);
        WriteFuncRegistrations(writer, funcEntries);
        WriteKvpRegistrations(writer, kvpEntries);

        writer.Indentation--;
        writer.WriteLine("}");
    }
}