using static SourceGen.Ioc.SourceGenerator.Models.Constants;

namespace SourceGen.Ioc;

partial class IocSourceGenerator
{
    /// <summary>
    /// Generates the container source code output.
    /// </summary>
    private static void GenerateContainerOutput(
        in SourceProductionContext ctx,
        ContainerWithGroups containerWithGroups,
        string assemblyName,
        MsBuildProperties msbuildProps,
        bool hasDIPackage)
    {
        if((msbuildProps.Features & IocFeatures.Container) == 0)
            return;

        var source = GenerateContainerSource(containerWithGroups, assemblyName, msbuildProps, hasDIPackage);
        var fileName = $"{containerWithGroups.Container.ClassName}.Container.g.cs";
        ctx.AddSource(fileName, source);
    }

    /// <summary>
    /// Generates the container source code.
    /// </summary>
    private static string GenerateContainerSource(
        ContainerWithGroups containerWithGroups,
        string assemblyName,
        MsBuildProperties msbuildProps,
        bool hasDIPackage)
    {
        var writer = new SourceWriter();
        var container = containerWithGroups.Container;
        var groups = containerWithGroups.Groups;

        // Determine if IServiceProviderFactory should be generated
        // Only generate if IntegrateServiceProvider is true AND the DI package is referenced
        var canGenerateServiceProviderFactory = container.IntegrateServiceProvider && hasDIPackage;

        // Effective UseSwitchStatement: when there are imported modules, always use FrozenDictionary
        // because combining services from multiple sources requires dictionary-based lookup
        var effectiveUseSwitchStatement = container.UseSwitchStatement && container.ImportedModules.Length == 0;

        WriteContainerHeader(writer);

        // Write [assembly: MetadataUpdateHandler] attribute for hot reload cache invalidation
        if(container.ImplementComponentActivator || container.ImplementComponentPropertyActivator)
        {
            writer.WriteLine($"[assembly: global::System.Reflection.Metadata.MetadataUpdateHandler(typeof({container.ContainerTypeName}.__HotReloadHandler))]");
            writer.WriteLine();
        }

        WriteContainerNamespaceAndClass(writer, container, groups, canGenerateServiceProviderFactory, effectiveUseSwitchStatement);

        return writer.ToString();
    }

    /// <summary>
    /// Writes the auto-generated header and using directives.
    /// </summary>
    private static void WriteContainerHeader(SourceWriter writer)
    {
        writer.WriteLine(AutoGeneratedHeader);
        writer.WriteLine(NullableEnable);
        writer.WriteLine("#pragma warning disable SGIOCEXP001");
        writer.WriteLine();
        writer.WriteLine("using System;");
        writer.WriteLine("using System.Collections.Frozen;");
        writer.WriteLine("using System.Collections.Generic;");
        writer.WriteLine("using System.Linq;");
        writer.WriteLine("using System.Threading;");
        writer.WriteLine("using System.Threading.Tasks;");
        writer.WriteLine("using Microsoft.Extensions.DependencyInjection;");
        writer.WriteLine("using SourceGen.Ioc;");
        writer.WriteLine();
    }
}
