using static SourceGen.Ioc.SourceGenerator.Models.Constants;

using System;
using System.Collections.Generic;
using System.Linq;

namespace SourceGen.Ioc;

partial class IocSourceGenerator
{
    /// <summary>
    /// Generates the container source code output.
    /// </summary>
    private static void GenerateContainerOutput(
        in SourceProductionContext ctx,
        ContainerWithGroups containerWithGroups,
        string assemblyName,
        MsBuildProperties msbuildProps,
        bool hasDIPackage)
    {
        if((msbuildProps.Features & IocFeatures.Container) == 0)
            return;

        var source = GenerateContainerSource(containerWithGroups, assemblyName, msbuildProps, hasDIPackage);
        var fileName = $"{containerWithGroups.Container.ClassName}.Container.g.cs";
        ctx.AddSource(fileName, source);
    }

    /// <summary>
    /// Generates the container source code.
    /// </summary>
    private static string GenerateContainerSource(
        ContainerWithGroups containerWithGroups,
        string assemblyName,
        MsBuildProperties msbuildProps,
        bool hasDIPackage)
    {
        var writer = new SourceWriter();
        var container = containerWithGroups.Container;
        var groups = containerWithGroups.Groups;

        // Determine if IServiceProviderFactory should be generated
        // Only generate if IntegrateServiceProvider is true AND the DI package is referenced
        var canGenerateServiceProviderFactory = container.IntegrateServiceProvider && hasDIPackage;

        // Effective UseSwitchStatement: when there are imported modules, always use FrozenDictionary
        // because combining services from multiple sources requires dictionary-based lookup
        var effectiveUseSwitchStatement = container.UseSwitchStatement && container.ImportedModules.Length == 0;

        WriteContainerHeader(writer);

        // Write [assembly: MetadataUpdateHandler] attribute for hot reload cache invalidation
        if(container.ImplementComponentActivator || container.ImplementComponentPropertyActivator)
        {
            writer.WriteLine($"[assembly: global::System.Reflection.Metadata.MetadataUpdateHandler(typeof({container.ContainerTypeName}.__HotReloadHandler))]");
            writer.WriteLine();
        }

        WriteContainerNamespaceAndClass(writer, container, groups, canGenerateServiceProviderFactory, effectiveUseSwitchStatement);

        return writer.ToString();
    }

    /// <summary>
    /// Writes the auto-generated header and using directives.
    /// </summary>
    private static void WriteContainerHeader(SourceWriter writer)
    {
        writer.WriteLine(AutoGeneratedHeader);
        writer.WriteLine(NullableEnable);
        writer.WriteLine("#pragma warning disable SGIOCEXP001");
        writer.WriteLine();
        writer.WriteLine("using System;");
        writer.WriteLine("using System.Collections.Frozen;");
        writer.WriteLine("using System.Collections.Generic;");
        writer.WriteLine("using System.Linq;");
        writer.WriteLine("using System.Threading;");
        writer.WriteLine("using System.Threading.Tasks;");
        writer.WriteLine("using Microsoft.Extensions.DependencyInjection;");
        writer.WriteLine("using SourceGen.Ioc;");
        writer.WriteLine();
    }

    /// <summary>
    /// Writes the namespace and class declaration with all implemented interfaces.
    /// </summary>
    private static void WriteContainerNamespaceAndClass(
        SourceWriter writer,
        ContainerModel container,
        ContainerRegistrationGroups groups,
        bool canGenerateServiceProviderFactory,
        bool effectiveUseSwitchStatement)
    {
        // Write namespace if not global
        bool hasNamespace = !string.IsNullOrEmpty(container.ContainerNamespace);
        if(hasNamespace)
        {
            writer.WriteLine($"namespace {container.ContainerNamespace};");
            writer.WriteLine();
        }

        // Get interface list
        var interfaces = GetContainerInterfaces(container, canGenerateServiceProviderFactory);

        // Write class declaration
        writer.WriteLine($"partial class {container.ClassName} : {string.Join(", ", interfaces)}");
        writer.WriteLine("{");
        writer.Indentation++;

        // Write fields
        WriteContainerFields(writer, container);

        // Write constructors
        WriteContainerConstructors(writer, container, groups, effectiveUseSwitchStatement);

        // Write service resolver methods
        WriteServiceResolverSection(writer, groups);

        // Write partial accessor implementations (user-declared partial methods/properties)
        WritePartialAccessorImplementations(writer, container, groups);

        // Write IServiceProvider implementation
        WriteIServiceProviderImplementation(writer, container, groups, effectiveUseSwitchStatement);

        // Write IKeyedServiceProvider implementation
        WriteIKeyedServiceProviderImplementation(writer, container, groups, effectiveUseSwitchStatement);

        // Write ISupportRequiredService implementation
        WriteISupportRequiredServiceImplementation(writer, container);

        // Write ServiceProvider extension methods (generic overloads)
        WriteServiceProviderExtensions(writer, container, effectiveUseSwitchStatement);

        // Write IServiceProviderIsService implementation
        WriteIServiceProviderIsServiceImplementation(writer, container, groups, effectiveUseSwitchStatement);

        // Write IServiceScopeFactory implementation
        WriteIServiceScopeFactoryImplementation(writer, container);

        // Write IIocContainer implementation
        WriteIIocContainerImplementation(writer, container, groups, effectiveUseSwitchStatement);

        // Write IServiceProviderFactory implementation (if DI package is available)
        if(canGenerateServiceProviderFactory)
        {
            WriteIServiceProviderFactoryImplementation(writer, container);
        }

        // Write Disposal implementation
        WriteDisposalImplementation(writer, container, groups);

        // Write IControllerActivator implementation (if container declares the interface)
        if(container.ImplementControllerActivator)
        {
            WriteIControllerActivatorImplementation(writer, container);
        }

        // Write IComponentActivator implementation (if container declares the interface)
        if(container.ImplementComponentActivator)
        {
            WriteIComponentActivatorImplementation(writer, container);
        }

        // Write IComponentPropertyActivator implementation (if container declares the interface)
        if(container.ImplementComponentPropertyActivator)
        {
            WriteIComponentPropertyActivatorImplementation(writer, container, effectiveUseSwitchStatement);
        }

        // Write hot reload handler (if either component activator interface is implemented)
        if(container.ImplementComponentActivator || container.ImplementComponentPropertyActivator)
        {
            WriteHotReloadHandler(writer, container);
        }

        writer.Indentation--;
        writer.WriteLine("}");
    }

    private static readonly string[] _FixedContainerInterfaces = [
        "IServiceProvider",
        "IKeyedServiceProvider",
        "IServiceProviderIsService",
        "IServiceProviderIsKeyedService",
        "ISupportRequiredService",
        "IServiceScopeFactory",
        "IServiceScope",
        "IDisposable",
        "IAsyncDisposable"
    ];
    /// <summary>
    /// Builds the list of interfaces the container should implement.
    /// </summary>
    private static IEnumerable<string> GetContainerInterfaces(ContainerModel container, bool canGenerateServiceProviderFactory)
    {
        yield return $"IIocContainer<{container.ContainerTypeName}>";

        foreach(var i in _FixedContainerInterfaces)
            yield return i;

        if(canGenerateServiceProviderFactory)
            yield return "IServiceProviderFactory<IServiceCollection>";
    }

    /// <summary>
    /// Writes container fields (fallback provider, service storage, locks, etc.).
    /// </summary>
    private static void WriteContainerFields(
        SourceWriter writer,
        ContainerModel container)
    {
        // Fallback provider field (only if IntegrateServiceProvider is enabled)
        if(container.IntegrateServiceProvider)
        {
            writer.WriteLine("private readonly IServiceProvider? _fallbackProvider;");
        }

        // Scope tracking
        writer.WriteLine("private readonly bool _isRootScope = true;");
        writer.WriteLine("private int _disposed;");
        writer.WriteLine();

        // Imported module fields
        foreach(var module in container.ImportedModules)
        {
            var fieldName = GetModuleFieldName(module.Name);
            writer.WriteLine($"private readonly {module.Name} {fieldName};");
        }

        if(container.ImportedModules.Length > 0)
        {
            writer.WriteLine();
        }
    }

    /// <summary>
    /// Writes a service instance field and synchronization field based on ThreadSafeStrategy.
    /// For eager services, fields are non-nullable and no synchronization is needed.
    /// </summary>
    private static void WriteServiceInstanceField(
        SourceWriter writer,
        ThreadSafeStrategy strategy,
        ServiceRegistrationModel reg,
        string fieldName,
        bool hasDecorators,
        bool isEager)
    {
        // When there are decorators, field type is ServiceType (interface), otherwise ImplementationType
        var typeName = hasDecorators ? reg.ServiceType.Name : reg.ImplementationType.Name;

        writer.WriteLine(isEager
            ? $"private {typeName} {fieldName} = null!;"
            : $"private {typeName}? {fieldName};");

        if(isEager)
            return;

        // SpinLock must NOT be readonly because Enter/Exit mutate it
        var syncFieldDeclaration = strategy switch
        {
            ThreadSafeStrategy.Lock => $"private readonly Lock {fieldName}Lock = new();",
            ThreadSafeStrategy.SemaphoreSlim => $"private readonly SemaphoreSlim {fieldName}Semaphore = new(1, 1);",
            ThreadSafeStrategy.SpinLock => $"private SpinLock {fieldName}SpinLock = new(false);",
            _ => null
        };

        if(syncFieldDeclaration is not null)
        {
            writer.WriteLine(syncFieldDeclaration);
        }
    }

    /// <summary>
    /// Writes container constructors.
    /// </summary>
    private static void WriteContainerConstructors(
        SourceWriter writer,
        ContainerModel container,
        ContainerRegistrationGroups groups,
        bool effectiveUseSwitchStatement)
    {
        writer.WriteLine("#region Constructors");
        writer.WriteLine();

        // Default constructor
        writer.WriteLine("/// <summary>");
        writer.WriteLine("/// Creates a new standalone container without external service provider fallback.");
        writer.WriteLine("/// </summary>");

        // Need fallback provider constructor if IntegrateServiceProvider is enabled
        var needsFallbackProvider = container.IntegrateServiceProvider;

        if(needsFallbackProvider)
        {
            writer.WriteLine($"public {container.ClassName}() : this((IServiceProvider?)null) {{ }}");
        }
        else
        {
            // Standalone mode - no fallback provider
            writer.WriteLine($"public {container.ClassName}()");
            writer.WriteLine("{");
            writer.Indentation++;
            WriteConstructorBody(writer, container, groups, hasParameter: false, effectiveUseSwitchStatement);
            writer.Indentation--;
            writer.WriteLine("}");
        }
        writer.WriteLine();

        // Constructor with fallback provider (if enabled)
        if(needsFallbackProvider)
        {
            writer.WriteLine("/// <summary>");
            writer.WriteLine("/// Creates a new container with optional fallback to external service provider.");
            writer.WriteLine("/// </summary>");
            writer.WriteLine("/// <param name=\"fallbackProvider\">Optional external service provider for unknown dependencies.</param>");
            writer.WriteLine($"public {container.ClassName}(IServiceProvider? fallbackProvider)");
            writer.WriteLine("{");
            writer.Indentation++;
            writer.WriteLine("_fallbackProvider = fallbackProvider;");
            WriteConstructorBody(writer, container, groups, hasParameter: true, effectiveUseSwitchStatement);
            writer.Indentation--;
            writer.WriteLine("}");
            writer.WriteLine();
        }

        // Private constructor for scoped instances
        writer.WriteLine($"private {container.ClassName}({container.ClassName} parent)");
        writer.WriteLine("{");
        writer.Indentation++;
        if(needsFallbackProvider)
        {
            writer.WriteLine("_fallbackProvider = parent._fallbackProvider;");
        }
        writer.WriteLine("_isRootScope = false;");

        // Copy singleton references from parent (already filtered for non-open-generics)
        foreach(var entry in groups.SingletonEntries)
        {
            if(!TryGetServiceFieldName(entry, out var fieldName))
                continue;

            writer.WriteLine($"{fieldName} = parent.{fieldName};");
        }

        // Create scopes for imported modules (so their scoped services are properly isolated)
        foreach(var module in container.ImportedModules)
        {
            var fieldName = GetModuleFieldName(module.Name);
            writer.WriteLine($"{fieldName} = ({module.Name})parent.{fieldName}.CreateScope().ServiceProvider;");
        }

        // Initialize eager scoped services
        if(groups.ScopedEntries.Any(static entry => entry is EagerContainerEntry or AsyncContainerEntry))
        {
            writer.WriteLine();
            writer.WriteLine("// Initialize eager scoped services");
            foreach(var entry in groups.ScopedEntries)
            {
                entry.WriteEagerInit(writer);
            }
        }

        // Initialize Lazy/Func wrapper fields (each scope gets its own wrappers)
        WriteWrapperInitializations(writer, groups.WrapperEntries);

        writer.Indentation--;
        writer.WriteLine("}");
        writer.WriteLine();

        writer.WriteLine("#endregion");
        writer.WriteLine();
    }

    /// <summary>
    /// Writes the constructor body for building the service resolver dictionary.
    /// </summary>
    private static void WriteConstructorBody(
        SourceWriter writer,
        ContainerModel container,
        ContainerRegistrationGroups groups,
        bool hasParameter,
        bool effectiveUseSwitchStatement)
    {
        // Initialize imported modules
        foreach(var module in container.ImportedModules)
        {
            var fieldName = GetModuleFieldName(module.Name);
            if(container.IntegrateServiceProvider && hasParameter)
            {
                writer.WriteLine($"{fieldName} = new {module.Name}(fallbackProvider);");
            }
            else
            {
                writer.WriteLine($"{fieldName} = new {module.Name}();");
            }
        }

        // Initialize eager singleton services
        if(groups.SingletonEntries.Any(static entry => entry is EagerContainerEntry or AsyncContainerEntry))
        {
            writer.WriteLine();
            writer.WriteLine("// Initialize eager singletons");
            foreach(var entry in groups.SingletonEntries)
            {
                entry.WriteEagerInit(writer);
            }
        }

        // Initialize Lazy/Func wrapper fields
        WriteWrapperInitializations(writer, groups.WrapperEntries);
    }

    private static void WriteWrapperInitializations(
        SourceWriter writer,
        ImmutableEquatableArray<ContainerEntry> wrapperEntries)
    {
        var lazyEntries = wrapperEntries.OfType<LazyWrapperContainerEntry>().ToList();
        var funcEntries = wrapperEntries.OfType<FuncWrapperContainerEntry>().ToList();

        if(lazyEntries.Count == 0 && funcEntries.Count == 0)
            return;

        if(lazyEntries.Count > 0)
        {
            writer.WriteLine();
            writer.WriteLine("// Initialize Lazy wrapper fields");
            foreach(var entry in lazyEntries)
            {
                entry.WriteInit(writer);
            }
        }

        if(funcEntries.Count > 0)
        {
            writer.WriteLine();
            writer.WriteLine("// Initialize Func wrapper fields");
            foreach(var entry in funcEntries)
            {
                entry.WriteInit(writer);
            }
        }
    }

    /// <summary>
    /// Writes individual service resolver methods.
    /// </summary>
    private static void WriteServiceResolverSection(
        SourceWriter writer,
        ContainerRegistrationGroups groups)
    {
        writer.WriteLine("#region Service Resolution");
        writer.WriteLine();

        var writtenMethods = new HashSet<string>(StringComparer.Ordinal);

        WriteServiceResolverGroup(writer, groups.SingletonEntries, writtenMethods, writeField: true);
        WriteServiceResolverGroup(writer, groups.ScopedEntries, writtenMethods, writeField: true);
        WriteServiceResolverGroup(writer, groups.TransientEntries, writtenMethods, writeField: false);

        foreach(var entry in groups.CollectionEntries)
        {
            entry.WriteResolver(writer);
            writer.WriteLine();
        }

        var kvpEntries = groups.WrapperEntries
            .OfType<KvpWrapperContainerEntry>()
            .ToList();

        if(kvpEntries.Count > 0)
        {
            writer.WriteLine("// KeyValuePair resolver methods");
            writer.WriteLine();

            foreach(var entry in kvpEntries)
            {
                entry.WriteResolver(writer);
                writer.WriteLine();
            }

            WriteKvpCollectionResolvers(writer, kvpEntries);
        }

        var lazyEntries = groups.WrapperEntries
            .OfType<LazyWrapperContainerEntry>()
            .ToList();

        if(lazyEntries.Count > 0)
        {
            writer.WriteLine("// Lazy wrapper fields");
            writer.WriteLine();

            foreach(var entry in lazyEntries)
            {
                entry.WriteField(writer);
            }

            writer.WriteLine();

            foreach(var entry in lazyEntries)
            {
                if(!entry.EmitCollectionResolver)
                    continue;

                entry.WriteCollectionResolver(writer);
                writer.WriteLine();
            }
        }

        var funcEntries = groups.WrapperEntries
            .OfType<FuncWrapperContainerEntry>()
            .ToList();

        if(funcEntries.Count > 0)
        {
            writer.WriteLine("// Func wrapper fields");
            writer.WriteLine();

            foreach(var entry in funcEntries)
            {
                entry.WriteField(writer);
            }

            writer.WriteLine();

            foreach(var entry in funcEntries)
            {
                if(!entry.EmitCollectionResolver)
                    continue;

                entry.WriteCollectionResolver(writer);
                writer.WriteLine();
            }
        }

        writer.WriteLine("#endregion");
        writer.WriteLine();
    }

    private static void WriteServiceResolverGroup(
        SourceWriter writer,
        ImmutableEquatableArray<ContainerEntry> entries,
        HashSet<string> writtenMethods,
        bool writeField)
    {
        foreach(var entry in entries)
        {
            if(!TryGetResolverMethodName(entry, out var resolverMethodName))
                continue;

            if(!writtenMethods.Add(resolverMethodName))
                continue;

            if(writeField)
            {
                entry.WriteField(writer);

                if(entry is AsyncContainerEntry)
                {
                    writer.WriteLine();
                }
            }

            entry.WriteResolver(writer);
            writer.WriteLine();
        }
    }

    private static void WriteKvpCollectionResolvers(
        SourceWriter writer,
        List<KvpWrapperContainerEntry> kvpEntries)
    {
        var grouped = kvpEntries
            .GroupBy(static e => (e.KeyTypeName, e.ValueTypeName))
            .ToList();

        foreach(var group in grouped)
        {
            var (keyTypeName, valueTypeName) = group.Key;
            var kvpTypeName = $"global::System.Collections.Generic.KeyValuePair<{keyTypeName}, {valueTypeName}>";
            var arrayMethodName = GetKvpArrayResolverMethodName(keyTypeName, valueTypeName);

            writer.WriteLine($"private {kvpTypeName}[] {arrayMethodName}() =>");
            writer.Indentation++;
            writer.WriteLine("[");
            writer.Indentation++;

            foreach(var entry in group)
            {
                writer.WriteLine($"{entry.KvpResolverMethodName}(),");
            }

            writer.Indentation--;
            writer.WriteLine("];");
            writer.Indentation--;
            writer.WriteLine();
        }

        foreach(var group in grouped)
        {
            var (keyTypeName, valueTypeName) = group.Key;
            var dictionaryMethodName = GetKvpDictionaryResolverMethodName(keyTypeName, valueTypeName);

            writer.WriteLine($"private global::System.Collections.Generic.Dictionary<{keyTypeName}, {valueTypeName}> {dictionaryMethodName}() =>");
            writer.Indentation++;
            writer.WriteLine($"new global::System.Collections.Generic.Dictionary<{keyTypeName}, {valueTypeName}>()");
            writer.WriteLine("{");
            writer.Indentation++;

            foreach(var entry in group)
            {
                writer.WriteLine($"[{entry.KeyExpr}] = {entry.ResolverMethodName}(),");
            }

            writer.Indentation--;
            writer.WriteLine("};");
            writer.Indentation--;
            writer.WriteLine();
        }
    }

    private static bool TryGetServiceFieldName(ContainerEntry entry, out string fieldName)
    {
        switch(entry)
        {
            case EagerContainerEntry eager:
                fieldName = eager.FieldName;
                return true;
            case LazyThreadSafeContainerEntry lazy:
                fieldName = lazy.FieldName;
                return true;
            case AsyncContainerEntry asyncEntry:
                fieldName = asyncEntry.FieldName;
                return true;
            default:
                fieldName = string.Empty;
                return false;
        }
    }

    /// <summary>
    /// Writes individual service resolver methods.
    /// </summary>
    private static void WritePartialAccessorImplementations(
        SourceWriter writer,
        ContainerModel container,
        ContainerRegistrationGroups groups)
    {
        if(container.PartialAccessors.Length == 0)
            return;

        writer.WriteLine("#region Partial Accessor Implementations");
        writer.WriteLine();

        foreach(var accessor in container.PartialAccessors)
        {
            var isTaskReturn = accessor.Kind == PartialAccessorKind.Method
                && TryExtractTaskInnerType(accessor.ReturnTypeName, out _);

            var resolveExpression = ResolvePartialAccessorExpression(accessor, container, groups);

            switch(accessor.Kind)
            {
                case PartialAccessorKind.Method:
                    // Async partial methods (returning Task<T>) require the 'async' modifier
                    if(isTaskReturn)
                    {
                        writer.WriteLine($"public partial async {accessor.ReturnTypeName} {accessor.Name}() => {resolveExpression};");
                    }
                    else
                    {
                        writer.WriteLine($"public partial {accessor.ReturnTypeName}{(accessor.IsNullable ? "?" : "")} {accessor.Name}() => {resolveExpression};");
                    }
                    break;

                case PartialAccessorKind.Property:
                    writer.WriteLine($"public partial {accessor.ReturnTypeName}{(accessor.IsNullable ? "?" : "")} {accessor.Name} {{ get => {resolveExpression}; }}");
                    break;
            }

            writer.WriteLine();
        }

        writer.WriteLine("#endregion");
        writer.WriteLine();
    }

    /// <summary>
    /// Resolves the expression to use for a partial accessor implementation.
    /// Looks up the registration by return type and optional key, with fallback to IServiceProvider.
    /// For <c>Task&lt;T&gt;</c> return types, routes through the async resolver.
    /// </summary>
    private static string ResolvePartialAccessorExpression(
        PartialAccessorData accessor,
        ContainerModel container,
        ContainerRegistrationGroups groups)
    {
        var serviceType = accessor.ReturnTypeName;
        var key = accessor.Key;

        // Handle Task<T> return types — route through the async resolver.
        if(TryExtractTaskInnerType(serviceType, out var innerTypeName))
        {
            if(groups.LastWinsByServiceType.TryGetValue((innerTypeName, key), out var entry))
            {
                switch(entry)
                {
                    case AsyncContainerEntry asyncEntry:
                        return $"await {GetAsyncResolverMethodName(asyncEntry.ResolverMethodName)}()";
                    case AsyncTransientContainerEntry asyncTransientEntry:
                        return $"await {GetAsyncCreateMethodName(asyncTransientEntry.ResolverMethodName)}()";
                    case InstanceContainerEntry instanceEntry:
                        return $"global::System.Threading.Tasks.Task.FromResult(({innerTypeName}){instanceEntry.Registration.Instance})";
                    case ServiceContainerEntry serviceEntry:
                        return $"global::System.Threading.Tasks.Task.FromResult(({innerTypeName}){serviceEntry.ResolverMethodName}())";
                }
            }

            // Fallback: delegate to IServiceProvider if available
            if(container.IntegrateServiceProvider)
            {
                if(key is not null)
                    return $"({serviceType})GetRequiredKeyedService(typeof({serviceType}), {key})";
                return $"({serviceType})GetRequiredService(typeof({serviceType}))";
            }

            return $"""throw new global::System.InvalidOperationException("Service '{innerTypeName}' is not registered.")""";
        }

        // Try to find direct resolver in this container
        if(groups.LastWinsByServiceType.TryGetValue((serviceType, key), out var directEntry))
        {
            switch(directEntry)
            {
                case InstanceContainerEntry instanceEntry:
                    return instanceEntry.Registration.Instance!;
                case AsyncContainerEntry asyncEntry:
                    return $"{GetAsyncResolverMethodName(asyncEntry.ResolverMethodName)}().ConfigureAwait(false).GetAwaiter().GetResult()";
                case AsyncTransientContainerEntry asyncTransientEntry:
                    return $"{GetAsyncCreateMethodName(asyncTransientEntry.ResolverMethodName)}().ConfigureAwait(false).GetAwaiter().GetResult()";
                case ServiceContainerEntry serviceEntry:
                    return $"{serviceEntry.ResolverMethodName}()";
            }
        }

        // Fallback to GetService/GetRequiredService (only when IntegrateServiceProvider is enabled)
        if(container.IntegrateServiceProvider)
        {
            if(key is not null)
            {
                return accessor.IsNullable
                    ? $"GetKeyedService(typeof({serviceType}), {key}) as {serviceType}"
                    : $"({serviceType})GetRequiredKeyedService(typeof({serviceType}), {key})";
            }

            return accessor.IsNullable
                ? $"GetService(typeof({serviceType})) as {serviceType}"
                : $"({serviceType})GetRequiredService(typeof({serviceType}))";
        }

        // No resolver found and no fallback: throw (analyzer should have caught this)
        return accessor.IsNullable
            ? "default"
            : $"""throw new global::System.InvalidOperationException("Service '{serviceType}' is not registered.")""";
    }

    /// <summary>
    /// Tries to extract the inner type name from a
    /// <c>global::System.Threading.Tasks.Task&lt;T&gt;</c> type name string.
    /// Returns <see langword="true"/> and sets <paramref name="innerTypeName"/> if matched.
    /// </summary>
    private static bool TryExtractTaskInnerType(string typeName, out string innerTypeName)
    {
        const string TaskPrefix = "global::System.Threading.Tasks.Task<";
        if(typeName.StartsWith(TaskPrefix, StringComparison.Ordinal)
            && typeName.EndsWith(">", StringComparison.Ordinal))
        {
            innerTypeName = typeName[TaskPrefix.Length..^1];
            return true;
        }
        innerTypeName = string.Empty;
        return false;
    }

    /// <summary>
    /// Gets the array resolver method name for IEnumerable&lt;T&gt;, IReadOnlyCollection&lt;T&gt;, IReadOnlyList&lt;T&gt;, T[] resolution.
    /// </summary>
    private static string GetArrayResolverMethodName(string serviceType)
    {
        var baseName = GetSafeIdentifier(serviceType);
        return $"GetAll{baseName}Array";
    }

    /// <summary>
    /// Gets the field name for an imported module.
    /// </summary>
    private static string GetModuleFieldName(string moduleName)
    {
        var baseName = GetSafeIdentifier(moduleName);
        return $"_{char.ToLowerInvariant(baseName[0])}{baseName[1..]}";
    }
}
