using static SourceGen.Ioc.SourceGenerator.Models.Constants;

namespace SourceGen.Ioc;

partial class IocSourceGenerator
{
    /// <summary>
    /// Generates the container source code output.
    /// </summary>
    private static void GenerateContainerOutput(
        in SourceProductionContext ctx,
        ContainerWithGroups containerWithGroups,
        string assemblyName,
        MsBuildProperties msbuildProps,
        bool hasDIPackage)
    {
        if((msbuildProps.Features & IocFeatures.Container) == 0)
            return;

        var source = GenerateContainerSource(containerWithGroups, assemblyName, msbuildProps, hasDIPackage);
        var fileName = $"{containerWithGroups.Container.ClassName}.Container.g.cs";
        ctx.AddSource(fileName, source);
    }

    /// <summary>
    /// Generates the container source code.
    /// </summary>
    private static string GenerateContainerSource(
        ContainerWithGroups containerWithGroups,
        string assemblyName,
        MsBuildProperties msbuildProps,
        bool hasDIPackage)
    {
        var writer = new SourceWriter();
        var container = containerWithGroups.Container;
        var groups = containerWithGroups.Groups;

        // Determine if IServiceProviderFactory should be generated
        // Only generate if IntegrateServiceProvider is true AND the DI package is referenced
        var canGenerateServiceProviderFactory = container.IntegrateServiceProvider && hasDIPackage;

        // Effective UseSwitchStatement: when there are imported modules, always use FrozenDictionary
        // because combining services from multiple sources requires dictionary-based lookup
        var effectiveUseSwitchStatement = container.UseSwitchStatement && container.ImportedModules.Length == 0;

        WriteContainerHeader(writer);

        // Write [assembly: MetadataUpdateHandler] attribute for hot reload cache invalidation
        if(container.ImplementComponentActivator || container.ImplementComponentPropertyActivator)
        {
            writer.WriteLine($"[assembly: global::System.Reflection.Metadata.MetadataUpdateHandler(typeof({container.ContainerTypeName}.__HotReloadHandler))]");
            writer.WriteLine();
        }

        WriteContainerNamespaceAndClass(writer, container, groups, canGenerateServiceProviderFactory, effectiveUseSwitchStatement);

        return writer.ToString();
    }

    /// <summary>
    /// Writes the auto-generated header and using directives.
    /// </summary>
    private static void WriteContainerHeader(SourceWriter writer)
    {
        writer.WriteLine(AutoGeneratedHeader);
        writer.WriteLine(NullableEnable);
        writer.WriteLine("#pragma warning disable SGIOCEXP001");
        writer.WriteLine();
        writer.WriteLine("using System;");
        writer.WriteLine("using System.Collections.Frozen;");
        writer.WriteLine("using System.Collections.Generic;");
        writer.WriteLine("using System.Linq;");
        writer.WriteLine("using System.Threading;");
        writer.WriteLine("using System.Threading.Tasks;");
        writer.WriteLine("using Microsoft.Extensions.DependencyInjection;");
        writer.WriteLine("using SourceGen.Ioc;");
        writer.WriteLine();
    }

    /// <summary>
    /// Writes the namespace and class declaration with all implemented interfaces.
    /// </summary>
    private static void WriteContainerNamespaceAndClass(
        SourceWriter writer,
        ContainerModel container,
        ContainerRegistrationGroups groups,
        bool canGenerateServiceProviderFactory,
        bool effectiveUseSwitchStatement)
    {
        // Write namespace if not global
        bool hasNamespace = !string.IsNullOrEmpty(container.ContainerNamespace);
        if(hasNamespace)
        {
            writer.WriteLine($"namespace {container.ContainerNamespace};");
            writer.WriteLine();
        }

        // Get interface list
        var interfaces = GetContainerInterfaces(container, canGenerateServiceProviderFactory);

        // Write class declaration
        writer.WriteLine($"partial class {container.ClassName} : {string.Join(", ", interfaces)}");
        writer.WriteLine("{");
        writer.Indentation++;

        // Write fields
        WriteContainerFields(writer, container);

        // Write constructors
        WriteContainerConstructors(writer, container, groups, effectiveUseSwitchStatement);

        // Write service resolver methods
        WriteServiceResolverMethods(writer, container.ThreadSafeStrategy, groups);

        // Write partial accessor implementations (user-declared partial methods/properties)
        WritePartialAccessorImplementations(writer, container, groups);

        // Write IServiceProvider implementation
        WriteIServiceProviderImplementation(writer, container, groups, effectiveUseSwitchStatement);

        // Write IKeyedServiceProvider implementation
        WriteIKeyedServiceProviderImplementation(writer, container, groups, effectiveUseSwitchStatement);

        // Write ISupportRequiredService implementation
        WriteISupportRequiredServiceImplementation(writer, container);

        // Write ServiceProvider extension methods (generic overloads)
        WriteServiceProviderExtensions(writer, container, effectiveUseSwitchStatement);

        // Write IServiceProviderIsService implementation
        WriteIServiceProviderIsServiceImplementation(writer, container, groups, effectiveUseSwitchStatement);

        // Write IServiceScopeFactory implementation
        WriteIServiceScopeFactoryImplementation(writer, container);

        // Write IIocContainer implementation
        WriteIIocContainerImplementation(writer, container, groups, effectiveUseSwitchStatement);

        // Write IServiceProviderFactory implementation (if DI package is available)
        if(canGenerateServiceProviderFactory)
        {
            WriteIServiceProviderFactoryImplementation(writer, container);
        }

        // Write Disposal implementation
        WriteDisposalImplementation(writer, container, groups);

        // Write IControllerActivator implementation (if container declares the interface)
        if(container.ImplementControllerActivator)
        {
            WriteIControllerActivatorImplementation(writer, container);
        }

        // Write IComponentActivator implementation (if container declares the interface)
        if(container.ImplementComponentActivator)
        {
            WriteIComponentActivatorImplementation(writer, container);
        }

        // Write IComponentPropertyActivator implementation (if container declares the interface)
        if(container.ImplementComponentPropertyActivator)
        {
            WriteIComponentPropertyActivatorImplementation(writer, container, effectiveUseSwitchStatement);
        }

        // Write hot reload handler (if either component activator interface is implemented)
        if(container.ImplementComponentActivator || container.ImplementComponentPropertyActivator)
        {
            WriteHotReloadHandler(writer, container);
        }

        writer.Indentation--;
        writer.WriteLine("}");
    }

    private static readonly string[] _FixedContainerInterfaces = [
        "IServiceProvider",
        "IKeyedServiceProvider",
        "IServiceProviderIsService",
        "IServiceProviderIsKeyedService",
        "ISupportRequiredService",
        "IServiceScopeFactory",
        "IServiceScope",
        "IDisposable",
        "IAsyncDisposable"
    ];
    /// <summary>
    /// Builds the list of interfaces the container should implement.
    /// </summary>
    private static IEnumerable<string> GetContainerInterfaces(ContainerModel container, bool canGenerateServiceProviderFactory)
    {
        yield return $"IIocContainer<{container.ContainerTypeName}>";

        foreach(var i in _FixedContainerInterfaces)
            yield return i;

        if(canGenerateServiceProviderFactory)
            yield return "IServiceProviderFactory<IServiceCollection>";
    }

    /// <summary>
    /// Writes container fields (fallback provider, service storage, locks, etc.).
    /// </summary>
    private static void WriteContainerFields(
        SourceWriter writer,
        ContainerModel container)
    {
        // Fallback provider field (only if IntegrateServiceProvider is enabled)
        if(container.IntegrateServiceProvider)
        {
            writer.WriteLine("private readonly IServiceProvider? _fallbackProvider;");
        }

        // Scope tracking
        writer.WriteLine("private readonly bool _isRootScope = true;");
        writer.WriteLine("private int _disposed;");
        writer.WriteLine();

        // Imported module fields
        foreach(var module in container.ImportedModules)
        {
            var fieldName = GetModuleFieldName(module.Name);
            writer.WriteLine($"private readonly {module.Name} {fieldName};");
        }

        if(container.ImportedModules.Length > 0)
        {
            writer.WriteLine();
        }
    }

    /// <summary>
    /// Writes a service instance field and synchronization field based on ThreadSafeStrategy.
    /// For eager services, fields are non-nullable and no synchronization is needed.
    /// </summary>
    private static void WriteServiceInstanceField(
        SourceWriter writer,
        ThreadSafeStrategy strategy,
        ServiceRegistrationModel reg,
        string fieldName,
        bool hasDecorators,
        bool isEager)
    {
        // When there are decorators, field type is ServiceType (interface), otherwise ImplementationType
        var typeName = hasDecorators ? reg.ServiceType.Name : reg.ImplementationType.Name;

        writer.WriteLine(isEager
            ? $"private {typeName} {fieldName} = null!;"
            : $"private {typeName}? {fieldName};");

        if(isEager)
            return;

        // SpinLock must NOT be readonly because Enter/Exit mutate it
        var syncFieldDeclaration = strategy switch
        {
            ThreadSafeStrategy.Lock => $"private readonly Lock {fieldName}Lock = new();",
            ThreadSafeStrategy.SemaphoreSlim => $"private readonly SemaphoreSlim {fieldName}Semaphore = new(1, 1);",
            ThreadSafeStrategy.SpinLock => $"private SpinLock {fieldName}SpinLock = new(false);",
            _ => null
        };

        if(syncFieldDeclaration is not null)
        {
            writer.WriteLine(syncFieldDeclaration);
        }
    }

    /// <summary>
    /// Writes container constructors.
    /// </summary>
    private static void WriteContainerConstructors(
        SourceWriter writer,
        ContainerModel container,
        ContainerRegistrationGroups groups,
        bool effectiveUseSwitchStatement)
    {
        writer.WriteLine("#region Constructors");
        writer.WriteLine();

        // Default constructor
        writer.WriteLine("/// <summary>");
        writer.WriteLine("/// Creates a new standalone container without external service provider fallback.");
        writer.WriteLine("/// </summary>");

        // Need fallback provider constructor if IntegrateServiceProvider is enabled
        var needsFallbackProvider = container.IntegrateServiceProvider;

        if(needsFallbackProvider)
        {
            writer.WriteLine($"public {container.ClassName}() : this((IServiceProvider?)null) {{ }}");
        }
        else
        {
            // Standalone mode - no fallback provider
            writer.WriteLine($"public {container.ClassName}()");
            writer.WriteLine("{");
            writer.Indentation++;
            WriteConstructorBody(writer, container, groups, hasParameter: false, effectiveUseSwitchStatement);
            writer.Indentation--;
            writer.WriteLine("}");
        }
        writer.WriteLine();

        // Constructor with fallback provider (if enabled)
        if(needsFallbackProvider)
        {
            writer.WriteLine("/// <summary>");
            writer.WriteLine("/// Creates a new container with optional fallback to external service provider.");
            writer.WriteLine("/// </summary>");
            writer.WriteLine("/// <param name=\"fallbackProvider\">Optional external service provider for unknown dependencies.</param>");
            writer.WriteLine($"public {container.ClassName}(IServiceProvider? fallbackProvider)");
            writer.WriteLine("{");
            writer.Indentation++;
            writer.WriteLine("_fallbackProvider = fallbackProvider;");
            WriteConstructorBody(writer, container, groups, hasParameter: true, effectiveUseSwitchStatement);
            writer.Indentation--;
            writer.WriteLine("}");
            writer.WriteLine();
        }

        // Private constructor for scoped instances
        writer.WriteLine($"private {container.ClassName}({container.ClassName} parent)");
        writer.WriteLine("{");
        writer.Indentation++;
        if(needsFallbackProvider)
        {
            writer.WriteLine("_fallbackProvider = parent._fallbackProvider;");
        }
        writer.WriteLine("_isRootScope = false;");

        // Copy singleton references from parent (already filtered for non-open-generics)
        // Skip instance registrations as they don't have fields
        foreach(var cached in groups.Singletons)
        {
            // Instance registrations don't have fields, skip them
            if(cached.Registration.Instance is not null)
                continue;

            writer.WriteLine($"{cached.FieldName} = parent.{cached.FieldName};");
        }

        // Create scopes for imported modules (so their scoped services are properly isolated)
        foreach(var module in container.ImportedModules)
        {
            var fieldName = GetModuleFieldName(module.Name);
            writer.WriteLine($"{fieldName} = ({module.Name})parent.{fieldName}.CreateScope().ServiceProvider;");
        }

        // Initialize eager scoped services by calling their Get methods
        var eagerScoped = groups.EagerScoped;
        if(eagerScoped.Length > 0)
        {
            writer.WriteLine();
            writer.WriteLine("// Initialize eager scoped services");
            foreach(var cached in eagerScoped)
            {
                writer.WriteLine($"{cached.FieldName} = {cached.ResolverMethodName}();");
            }
        }

        // Initialize Lazy/Func wrapper fields (each scope gets its own wrappers)
        WriteContainerLazyFieldInitializations(writer, groups.LazyEntries);
        WriteContainerFuncFieldInitializations(writer, groups.FuncEntries);

        writer.Indentation--;
        writer.WriteLine("}");
        writer.WriteLine();

        writer.WriteLine("#endregion");
        writer.WriteLine();
    }

    /// <summary>
    /// Writes the constructor body for building the service resolver dictionary.
    /// </summary>
    private static void WriteConstructorBody(
        SourceWriter writer,
        ContainerModel container,
        ContainerRegistrationGroups groups,
        bool hasParameter,
        bool effectiveUseSwitchStatement)
    {
        // Initialize imported modules
        foreach(var module in container.ImportedModules)
        {
            var fieldName = GetModuleFieldName(module.Name);
            if(container.IntegrateServiceProvider && hasParameter)
            {
                writer.WriteLine($"{fieldName} = new {module.Name}(fallbackProvider);");
            }
            else
            {
                writer.WriteLine($"{fieldName} = new {module.Name}();");
            }
        }

        // Initialize eager singletons by calling their Get methods
        // This ensures dependencies are resolved in the correct order
        var eagerSingletons = groups.EagerSingletons;
        if(eagerSingletons.Length > 0)
        {
            writer.WriteLine();
            writer.WriteLine("// Initialize eager singletons");
            foreach(var cached in eagerSingletons)
            {
                writer.WriteLine($"{cached.FieldName} = {cached.ResolverMethodName}();");
            }
        }

        // Initialize Lazy/Func wrapper fields
        WriteContainerLazyFieldInitializations(writer, groups.LazyEntries);
        WriteContainerFuncFieldInitializations(writer, groups.FuncEntries);
    }

    /// <summary>
    /// Writes individual service resolver methods.
    /// </summary>
    private static void WritePartialAccessorImplementations(
        SourceWriter writer,
        ContainerModel container,
        ContainerRegistrationGroups groups)
    {
        if(container.PartialAccessors.Length == 0)
            return;

        writer.WriteLine("#region Partial Accessor Implementations");
        writer.WriteLine();

        foreach(var accessor in container.PartialAccessors)
        {
            var isTaskReturn = accessor.Kind == PartialAccessorKind.Method
                && TryExtractTaskInnerType(accessor.ReturnTypeName, out _);

            var resolveExpression = ResolvePartialAccessorExpression(accessor, container, groups);

            switch(accessor.Kind)
            {
                case PartialAccessorKind.Method:
                    // Async partial methods (returning Task<T>) require the 'async' modifier
                    if(isTaskReturn)
                    {
                        writer.WriteLine($"public partial async {accessor.ReturnTypeName} {accessor.Name}() => {resolveExpression};");
                    }
                    else
                    {
                        writer.WriteLine($"public partial {accessor.ReturnTypeName}{(accessor.IsNullable ? "?" : "")} {accessor.Name}() => {resolveExpression};");
                    }
                    break;

                case PartialAccessorKind.Property:
                    writer.WriteLine($"public partial {accessor.ReturnTypeName}{(accessor.IsNullable ? "?" : "")} {accessor.Name} {{ get => {resolveExpression}; }}");
                    break;
            }

            writer.WriteLine();
        }

        writer.WriteLine("#endregion");
        writer.WriteLine();
    }

    /// <summary>
    /// Resolves the expression to use for a partial accessor implementation.
    /// Looks up the registration by return type and optional key, with fallback to IServiceProvider.
    /// For <c>Task&lt;T&gt;</c> return types, routes through the async resolver.
    /// </summary>
    private static string ResolvePartialAccessorExpression(
        PartialAccessorData accessor,
        ContainerModel container,
        ContainerRegistrationGroups groups)
    {
        var serviceType = accessor.ReturnTypeName;
        var key = accessor.Key;

        // Handle Task<T> return types — route through the async resolver.
        if(TryExtractTaskInnerType(serviceType, out var innerTypeName))
        {
            if(groups.ByServiceTypeAndKey.TryGetValue((innerTypeName, key), out var taskRegistrations))
            {
                var cached = taskRegistrations[^1]; // Last registration wins

                if(cached.IsAsyncInit)
                {
                    // Async-init: await the shared async resolver and let the async method wrap the cast.
                    var asyncMethodName = GetAsyncResolverMethodName(cached.ResolverMethodName);
                    return $"await {asyncMethodName}()";
                }
                else
                {
                    // Sync-only service wrapped as Task<T>: use Task.FromResult with cast.
                    return $"global::System.Threading.Tasks.Task.FromResult(({innerTypeName}){cached.ResolverMethodName}())";
                }
            }

            // Fallback: delegate to IServiceProvider if available
            if(container.IntegrateServiceProvider)
            {
                if(key is not null)
                    return $"({serviceType})GetRequiredKeyedService(typeof({serviceType}), {key})";
                return $"({serviceType})GetRequiredService(typeof({serviceType}))";
            }

            return $"""throw new global::System.InvalidOperationException("Service '{innerTypeName}' is not registered.")""";
        }

        // Try to find direct resolver in this container
        if(groups.ByServiceTypeAndKey.TryGetValue((serviceType, key), out var registrations))
        {
            var cached = registrations[^1]; // Last registration wins

            if(cached.Registration.Instance is not null)
            {
                // Instance registration: use the instance expression directly
                return cached.Registration.Instance;
            }

            return $"{cached.ResolverMethodName}()";
        }

        // Fallback to GetService/GetRequiredService (only when IntegrateServiceProvider is enabled)
        if(container.IntegrateServiceProvider)
        {
            if(key is not null)
            {
                return accessor.IsNullable
                    ? $"GetKeyedService(typeof({serviceType}), {key}) as {serviceType}"
                    : $"({serviceType})GetRequiredKeyedService(typeof({serviceType}), {key})";
            }

            return accessor.IsNullable
                ? $"GetService(typeof({serviceType})) as {serviceType}"
                : $"({serviceType})GetRequiredService(typeof({serviceType}))";
        }

        // No resolver found and no fallback: throw (analyzer should have caught this)
        return accessor.IsNullable
            ? "default"
            : $"""throw new global::System.InvalidOperationException("Service '{serviceType}' is not registered.")""";
    }

    /// <summary>
    /// Tries to extract the inner type name from a
    /// <c>global::System.Threading.Tasks.Task&lt;T&gt;</c> type name string.
    /// Returns <see langword="true"/> and sets <paramref name="innerTypeName"/> if matched.
    /// </summary>
    private static bool TryExtractTaskInnerType(string typeName, out string innerTypeName)
    {
        const string TaskPrefix = "global::System.Threading.Tasks.Task<";
        if(typeName.StartsWith(TaskPrefix, StringComparison.Ordinal)
            && typeName.EndsWith(">", StringComparison.Ordinal))
        {
            innerTypeName = typeName[TaskPrefix.Length..^1];
            return true;
        }
        innerTypeName = string.Empty;
        return false;
    }

    /// <summary>
    /// Gets the array resolver method name for IEnumerable&lt;T&gt;, IReadOnlyCollection&lt;T&gt;, IReadOnlyList&lt;T&gt;, T[] resolution.
    /// </summary>
    private static string GetArrayResolverMethodName(string serviceType)
    {
        var baseName = GetSafeIdentifier(serviceType);
        return $"GetAll{baseName}Array";
    }

    /// <summary>
    /// Gets the field name for an imported module.
    /// </summary>
    private static string GetModuleFieldName(string moduleName)
    {
        var baseName = GetSafeIdentifier(moduleName);
        return $"_{char.ToLowerInvariant(baseName[0])}{baseName[1..]}";
    }
}
