using static SourceGen.Ioc.SourceGenerator.Models.Constants;

namespace SourceGen.Ioc;

partial class IocSourceGenerator
{
    private static void GenerateRegisterOutput(
        in SourceProductionContext ctx,
        ImmutableEquatableArray<ServiceRegistrationWithTags> registrations,
        string rootNamespace,
        string assemblyName,
        MsBuildProperties msbuildProps)
    {
        var features = msbuildProps.Features;
        if((features & IocFeatures.Register) == 0 || registrations.Length == 0)
            return;

        // Generate source
        var source = GenerateExtensionMethodSource(registrations, rootNamespace, assemblyName, msbuildProps.CustomIocName, features);
        ctx.AddSource($"{assemblyName}.ServiceRegistration.g.cs", source);
    }

    private static string GenerateExtensionMethodSource(
        ImmutableEquatableArray<ServiceRegistrationWithTags> registrations,
        string rootNamespace,
        string assemblyName,
        string? customIocName,
        IocFeatures features)
    {
        // Use custom IoC name if provided, otherwise use assembly name
        var methodBaseName = !string.IsNullOrWhiteSpace(customIocName)
            ? GetSafeIdentifier(customIocName!)
            : GetSafeIdentifier(assemblyName);

        var tagKeyCache = new Dictionary<ImmutableEquatableArray<string>, string>();
        foreach(var regWithTags in registrations)
        {
            var tags = regWithTags.Tags;
            if(tagKeyCache.ContainsKey(tags))
            {
                continue;
            }

            tagKeyCache[tags] = tags.Length > 0
                ? string.Join(",", tags.OrderBy(static t => t, StringComparer.Ordinal))
                : string.Empty;
        }

        // Group registrations by their tag conditions for generating conditional blocks
        // Key: sorted comma-separated tags (empty string for no tags)
        // Value: list of registrations
        var tagGroups = new Dictionary<string, List<ServiceRegistrationModel>>(StringComparer.Ordinal);
        var shouldFilterInjection = !IocFeaturesHelper.HasAllInjectionFeatures(features);

        foreach(var regWithTags in registrations)
        {
            var registration = shouldFilterInjection
                ? FilterRegistrationForFeatures(regWithTags.Registration, features)
                : regWithTags.Registration;
            var tags = regWithTags.Tags;
            var tagKey = tagKeyCache[tags];

            if(!tagGroups.TryGetValue(tagKey, out var group))
            {
                group = new List<ServiceRegistrationModel>();
                tagGroups[tagKey] = group;
            }

            group.Add(registration);
        }

        // Build the final output
        var mainWriter = new SourceWriter();

        mainWriter.WriteLine(AutoGeneratedHeader);
        mainWriter.WriteLine(NullableEnable);
        mainWriter.WriteLine();
        mainWriter.WriteLine("using Microsoft.Extensions.DependencyInjection;");
        mainWriter.WriteLine("using System.Collections.Generic;");
        mainWriter.WriteLine("using System.Linq;");
        mainWriter.WriteLine();

        mainWriter.WriteLine($"namespace {GetSafeNamespace(rootNamespace)}");
        mainWriter.WriteLine("{");
        mainWriter.Indentation++;

        mainWriter.WriteLine("/// <summary>");
        mainWriter.WriteLine($"/// Extension methods for registering services from {assemblyName}.");
        mainWriter.WriteLine("/// </summary>");
        mainWriter.WriteLine($"public static class {methodBaseName}ServiceCollectionExtensions");
        mainWriter.WriteLine("{");
        mainWriter.Indentation++;

        // Generate single method with tags parameter
        mainWriter.WriteLine("/// <summary>");
        mainWriter.WriteLine("/// Registers services. Services with tags are only registered when matching tags are passed.");
        mainWriter.WriteLine("/// </summary>");
        mainWriter.WriteLine("/// <param name=\"services\">The service collection.</param>");
        mainWriter.WriteLine("/// <param name=\"tags\">Optional tags to filter which services to register.</param>");
        mainWriter.WriteLine($"public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection Add{methodBaseName}(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services, params global::System.Collections.Generic.IEnumerable<string> tags)");
        mainWriter.WriteLine("{");
        mainWriter.Indentation++;

        // Collect standalone Lazy<T>/Func<T> registrations from consumer dependencies
        var lazyEntries = CollectLazyEntries(registrations);
        var funcEntries = CollectFuncEntries(registrations);

        // Group Lazy entries by tag key to emit them within the correct conditional blocks
        var lazyByTagKey = new Dictionary<string, List<LazyRegistrationEntry>>(StringComparer.Ordinal);
        foreach(var entry in lazyEntries)
        {
            var tagKey = tagKeyCache[entry.Tags];

            if(!lazyByTagKey.TryGetValue(tagKey, out var list))
            {
                list = [];
                lazyByTagKey[tagKey] = list;
            }
            list.Add(entry);
        }

        // Group Func entries by tag key to emit them within the correct conditional blocks
        var funcByTagKey = new Dictionary<string, List<FuncRegistrationEntry>>(StringComparer.Ordinal);
        foreach(var entry in funcEntries)
        {
            var tagKey = tagKeyCache[entry.Tags];

            if(!funcByTagKey.TryGetValue(tagKey, out var list))
            {
                list = [];
                funcByTagKey[tagKey] = list;
            }
            list.Add(entry);
        }

        // Collect KVP registrations and group by tag key
        var kvpEntries = CollectKeyValuePairEntries(registrations);
        var kvpByTagKey = new Dictionary<string, List<KvpRegistrationEntry>>(StringComparer.Ordinal);
        foreach(var entry in kvpEntries)
        {
            var tagKey = tagKeyCache[entry.Tags];

            if(!kvpByTagKey.TryGetValue(tagKey, out var list))
            {
                list = [];
                kvpByTagKey[tagKey] = list;
            }
            list.Add(entry);
        }

        // Write registrations grouped by tag conditions
        // Sort groups for deterministic output: no tags first, then by tag key
        var sortedGroups = tagGroups
            .OrderBy(static kvp => kvp.Key, StringComparer.Ordinal)
            .ToList();

        // Compute the set of service type names (and impl type names) that have async-init injection.
        // Used by Task<T> wrapper resolution to distinguish async-init vs sync-only services.
        var asyncInitServiceTypeSet = new HashSet<string>(StringComparer.Ordinal);
        foreach(var group in tagGroups.Values)
        {
            foreach(var reg in group)
            {
                if(reg.InjectionMembers.Any(m => m.MemberType == InjectionMemberType.AsyncMethod))
                {
                    asyncInitServiceTypeSet.Add(reg.ServiceType.Name);
                    asyncInitServiceTypeSet.Add(reg.ImplementationType.Name);
                }
            }
        }
        HashSet<string>? asyncInitServiceTypeNames = asyncInitServiceTypeSet.Count > 0 ? asyncInitServiceTypeSet : null;

        bool isFirstGroup = true;
        foreach(var kvp in sortedGroups)
        {
            var groupKey = kvp.Key;
            var groupRegistrations = kvp.Value;

            var tagList = string.IsNullOrEmpty(groupKey)
                ? []
                : groupKey.Split(',');

            // Get matching wrapper entries for this tag group
            lazyByTagKey.TryGetValue(groupKey, out var groupLazyEntries);
            funcByTagKey.TryGetValue(groupKey, out var groupFuncEntries);
            kvpByTagKey.TryGetValue(groupKey, out var groupKvpEntries);

            if(!isFirstGroup)
            {
                mainWriter.WriteLine();
            }
            isFirstGroup = false;

            if(tagList.Length == 0)
            {
                // No tags - only register when no tags passed (mutually exclusive model)
                WriteNoTagConditionalBlock(mainWriter, groupRegistrations, groupLazyEntries, groupFuncEntries, groupKvpEntries, asyncInitServiceTypeNames);
            }
            else
            {
                // Has tags - only register when tags match
                WriteConditionalTagBlock(mainWriter, tagList, groupRegistrations, groupLazyEntries, groupFuncEntries, groupKvpEntries, asyncInitServiceTypeNames);
            }
        }

        mainWriter.WriteLine();
        mainWriter.WriteLine("return services;");

        mainWriter.Indentation--;
        mainWriter.WriteLine("}");

        mainWriter.Indentation--;
        mainWriter.WriteLine("}");

        mainWriter.Indentation--;
        mainWriter.WriteLine("}");

        return mainWriter.ToString();
    }

    /// <summary>
    /// Writes a group of registrations without any conditional wrapper.
    /// </summary>
    private static void WriteRegistrationGroup(SourceWriter writer, List<ServiceRegistrationModel> registrations, HashSet<string>? asyncInitServiceTypeNames = null)
    {
        foreach(var registration in registrations)
        {
            WriteRegistration(writer, registration, asyncInitServiceTypeNames);
        }
    }

    /// <summary>
    /// Writes a conditional block for tag-based registration.
    /// Services with tags are only registered when the passed tags match.
    /// </summary>
    private static void WriteConditionalTagBlock(
        SourceWriter writer,
        string[] tags,
        List<ServiceRegistrationModel> registrations,
        List<LazyRegistrationEntry>? lazyEntries = null,
        List<FuncRegistrationEntry>? funcEntries = null,
        List<KvpRegistrationEntry>? kvpEntries = null,
        HashSet<string>? asyncInitServiceTypeNames = null)
    {
        // Build the condition - only register when tags match
        var tagConditions = tags.Select(static tag => $"tags.Contains(\"{tag}\")");
        var condition = string.Join(" || ", tagConditions);

        writer.WriteLine($"if ({condition})");
        writer.WriteLine("{");
        writer.Indentation++;

        foreach(var registration in registrations)
        {
            WriteRegistration(writer, registration, asyncInitServiceTypeNames);
        }

        WriteLazyRegistrations(writer, lazyEntries);
        WriteFuncRegistrations(writer, funcEntries);
        WriteKvpRegistrations(writer, kvpEntries);

        writer.Indentation--;
        writer.WriteLine("}");
    }

    /// <summary>
    /// Writes a conditional block for services without tags.
    /// Services without tags are only registered when no tags are passed (mutually exclusive model).
    /// </summary>
    private static void WriteNoTagConditionalBlock(
        SourceWriter writer,
        List<ServiceRegistrationModel> registrations,
        List<LazyRegistrationEntry>? lazyEntries = null,
        List<FuncRegistrationEntry>? funcEntries = null,
        List<KvpRegistrationEntry>? kvpEntries = null,
        HashSet<string>? asyncInitServiceTypeNames = null)
    {
        writer.WriteLine("if (!tags.Any())");
        writer.WriteLine("{");
        writer.Indentation++;

        foreach(var registration in registrations)
        {
            WriteRegistration(writer, registration, asyncInitServiceTypeNames);
        }

        WriteLazyRegistrations(writer, lazyEntries);
        WriteFuncRegistrations(writer, funcEntries);
        WriteKvpRegistrations(writer, kvpEntries);

        writer.Indentation--;
        writer.WriteLine("}");
    }

    /// <summary>
    /// Writes the start of a service registration lambda for keyed or non-keyed registrations.
    /// </summary>
    private static void WriteServiceRegistrationLambdaStart(
        SourceWriter writer,
        string lifetime,
        string serviceTypeName,
        string? registrationKey)
    {
        if(registrationKey is not null)
        {
            writer.WriteLine($"services.AddKeyed{lifetime}<{serviceTypeName}>({registrationKey}, ({IServiceProviderGlobalTypeName} sp, object? key) =>");
            return;
        }

        writer.WriteLine($"services.Add{lifetime}<{serviceTypeName}>(({IServiceProviderGlobalTypeName} sp) =>");
    }

    private static void WriteRegistration(SourceWriter writer, ServiceRegistrationModel registration, HashSet<string>? asyncInitServiceTypeNames = null)
    {
        var lifetime = registration.Lifetime.Name;
        var serviceTypeName = registration.ServiceType.Name;
        var implTypeName = registration.ImplementationType.Name;

        // Check if this registration uses Factory or Instance
        // Note: Factory and Instance cannot be used with open generics - they require concrete types
        bool hasFactory = registration.Factory is not null && !registration.IsOpenGeneric;
        bool hasInstance = registration.Instance is not null && !registration.IsOpenGeneric;

        // Handle Factory registration first (takes precedence)
        if(hasFactory)
        {
            WriteFactoryMethodRegistration(writer, registration, lifetime, asyncInitServiceTypeNames);
            return;
        }

        // Handle Instance registration (only for Singleton)
        if(hasInstance)
        {
            if(registration.Lifetime == ServiceLifetime.Singleton)
                WriteInstanceRegistration(writer, registration);

            return;
        }

        // Check if service type is different from implementation type (registering interface/base class)
        bool isServiceTypeRegistration = serviceTypeName != implTypeName;

        // Check if this registration has decorators and is not the implementation type itself
        bool hasDecorators = registration.Decorators.Length > 0 && isServiceTypeRegistration;

        if(hasDecorators)
        {
            if(registration.IsOpenGeneric)
            {
                // Open generic service types with decorators: do not generate factory lambdas with type parameters.
                // Fall through to open generic registration using typeof() syntax.
            }
            else
            {
                WriteDecoratorRegistration(writer, registration, lifetime, asyncInitServiceTypeNames);
                return;
            }
        }

        // Check if this registration has injection members (properties, fields, methods with [Inject])
        bool hasInjectionMembers = registration.InjectionMembers.Length > 0;

        // Check if the constructor was selected by [Inject] attribute (requires factory for proper constructor selection)
        bool hasInjectConstructor = registration.ImplementationType.HasInjectConstructor;

        // Check constructor parameters for special handling requirements:
        // - [Inject] attribute on parameters: MS.DI doesn't recognize it
        // - Non-IEnumerable collection types (IList<T>, T[], etc.): MS.DI only supports IEnumerable<T>
        // - Has default value and is resolvable type: needs conditional handling (GetService + null check)
        // - Nullable Lazy<T>?/Func<T>? (direct, non-nested): needs factory for optional resolution via GetService
        // Note: [FromKeyedServices], [ServiceKey], IServiceProvider are handled by MS.DI automatically
        var constructorParams = registration.ImplementationType.ConstructorParameters;
        bool hasSpecialConstructorParams = constructorParams?.Any(static p =>
            p.HasInjectAttribute ||
            p.Type.NeedsWrapperResolution ||
            (p.IsNullable && p.Type is LazyTypeData { InstanceType: not WrapperTypeData } or FuncTypeData { ReturnType: not WrapperTypeData }) ||
            p.HasDefaultValue) == true;

        // Determine if factory construction is needed:
        // - Injection members (properties, fields, methods) always require factory
        // - Constructor with [Inject] attribute requires factory (to use correct constructor)
        // - Constructor parameters with special handling (see above)
        bool needsFactoryConstruction = hasInjectionMembers || hasInjectConstructor || hasSpecialConstructorParams;

        // For non-open-generic, service type registrations (interface/base class):
        // Always use forwarding to implementation type to ensure single instance per scope/lifetime
        // This generates: sp => sp.GetRequiredService<ImplementationType>()
        // When impl is async-init, forwards Task<ServiceType> → Task<ImplType> instead.
        if(!registration.IsOpenGeneric && isServiceTypeRegistration)
        {
            // Service type registration (interface/base class) forwards to implementation
            WriteServiceTypeForwardingRegistration(writer, registration, lifetime, asyncInitServiceTypeNames);
            return;
        }

        if(needsFactoryConstruction && !registration.IsOpenGeneric)
        {
            // Self registration with injection members or constructor params with special handling - generate factory method
            bool hasAsyncInjectionMembers = registration.InjectionMembers.Any(m => m.MemberType == InjectionMemberType.AsyncMethod);
            if(hasAsyncInjectionMembers)
            {
                WriteAsyncInjectionRegistration(writer, registration, lifetime, asyncInitServiceTypeNames);
            }
            else
            {
                WriteInjectionRegistration(writer, registration, lifetime, asyncInitServiceTypeNames);
            }
            return;
        }

        if(registration.IsOpenGeneric)
        {
            // Open generic registration requires typeof() syntax
            var serviceTypeOf = ConvertToTypeOf(registration.ServiceType);
            var implTypeOf = ConvertToTypeOf(registration.ImplementationType);

            if(registration.Key is not null)
            {
                writer.WriteLine($"services.AddKeyed{lifetime}({serviceTypeOf}, {registration.Key}, {implTypeOf});");
                return;
            }

            writer.WriteLine($"services.Add{lifetime}({serviceTypeOf}, {implTypeOf});");
            return;
        }

        if(registration.Key is not null)
        {
            // Keyed registration
            writer.WriteLine($"services.AddKeyed{lifetime}<{serviceTypeName}, {registration.ImplementationType.Name}>({registration.Key});");
            return;
        }

        // Non-keyed registration
        writer.WriteLine($"services.Add{lifetime}<{serviceTypeName}, {registration.ImplementationType.Name}>();");
    }

    /// <summary>
    /// Writes registration code using a factory method specified in the attribute.
    /// </summary>
    /// <remarks>
    /// Supports factory methods with different parameter combinations:
    /// <list type="bullet">
    ///   <item>No parameters: <c>services.AddSingleton&lt;IService&gt;(Factory());</c></item>
    ///   <item>IServiceProvider only: <c>services.AddSingleton&lt;IService&gt;(sp => Factory(sp));</c></item>
    ///   <item>object key only (keyed): <c>services.AddKeyedSingleton&lt;IService&gt;("key", (sp, key) => Factory(key));</c></item>
    ///   <item>Both (keyed): <c>services.AddKeyedSingleton&lt;IService&gt;("key", (sp, key) => Factory(sp, key));</c></item>
    ///   <item>Additional parameters: resolved from IServiceProvider using the same logic as [IocInject] methods</item>
    ///   <item>Generic factory with [IocGenericFactory]: <c>services.AddSingleton&lt;IHandler&lt;Request&gt;&gt;(sp => Factory&lt;Request&gt;(sp));</c></item>
    /// </list>
    /// If the factory return type differs from the service type, adds a cast.
    /// </remarks>
    private static void WriteFactoryMethodRegistration(SourceWriter writer, ServiceRegistrationModel registration, string lifetime, HashSet<string>? asyncInitServiceTypeNames = null)
    {
        var serviceTypeName = registration.ServiceType.Name;
        var factory = registration.Factory!;
        var factoryPath = factory.Path;
        var hasServiceProvider = factory.HasServiceProvider;
        var hasKey = factory.HasKey;
        var returnTypeName = factory.ReturnTypeName;
        var additionalParameters = factory.AdditionalParameters;
        bool isKeyedRegistration = registration.Key is not null;

        // Build generic type arguments for generic factory methods
        var genericTypeArgs = BuildGenericFactoryTypeArgs(factory, registration.ServiceType);

        // If factory is generic but we couldn't resolve type arguments (e.g., duplicate placeholder types),
        // skip this registration entirely
        if(factory.TypeParameterCount > 0 && genericTypeArgs is null)
        {
            return;
        }

        // Check if we have additional parameters that need resolution
        bool hasAdditionalParameters = additionalParameters.Length > 0;

        if(hasAdditionalParameters)
        {
            // Use multi-line lambda format for readability
            WriteFactoryMethodRegistrationWithAdditionalParams(
                writer, registration, lifetime, serviceTypeName, factoryPath,
                hasServiceProvider, hasKey, returnTypeName, additionalParameters, isKeyedRegistration, genericTypeArgs, asyncInitServiceTypeNames);
            return;
        }

        // Simple case: no additional parameters
        var factoryInvocation = BuildFactoryInvocation(
            factoryPath,
            genericTypeArgs,
            hasServiceProvider,
            hasKey,
            registration.Key,
            [],
            returnTypeName,
            serviceTypeName);

        WriteFactoryRegistrationLine(writer, lifetime, serviceTypeName, registration.Key, factoryInvocation);
    }

    /// <summary>
    /// Writes factory method registration with additional parameters that need to be resolved from IServiceProvider.
    /// </summary>
    private static void WriteFactoryMethodRegistrationWithAdditionalParams(
        SourceWriter writer,
        ServiceRegistrationModel registration,
        string lifetime,
        string serviceTypeName,
        string factoryPath,
        bool hasServiceProvider,
        bool hasKey,
        string? returnTypeName,
        ImmutableEquatableArray<ParameterData> additionalParameters,
        bool isKeyedRegistration,
        string? genericTypeArgs = null,
        HashSet<string>? asyncInitServiceTypeNames = null)
    {
        // Open the registration lambda
        WriteServiceRegistrationLambdaStart(writer, lifetime, serviceTypeName, registration.Key);

        writer.WriteLine("{");
        writer.Indentation++;

        // Resolve additional parameters using the same logic as [IocInject] methods
        var paramVars = new List<string>(additionalParameters.Length);
        int paramIndex = 0;
        foreach(var param in additionalParameters)
        {
            var paramVar = $"f_p{paramIndex}";
            var varName = ResolveParamAndEmitVar(writer, param, paramVar, isKeyedRegistration, registration.Key, asyncInitServiceTypeNames);

            // Use the resolved variable name
            paramVars.Add(varName);
            paramIndex++;
        }

        var factoryInvocation = BuildFactoryInvocation(
            factoryPath,
            genericTypeArgs,
            hasServiceProvider,
            hasKey,
            registration.Key,
            paramVars,
            returnTypeName,
            serviceTypeName);

        writer.WriteLine($"return {factoryInvocation};");

        writer.Indentation--;
        writer.WriteLine("});");
    }

    /// <summary>
    /// Builds the factory invocation expression with optional generic arguments, service provider, key, and additional parameters.
    /// Adds a cast when the factory return type differs from the service type.
    /// </summary>
    private static string BuildFactoryInvocation(
        string factoryPath,
        string? genericTypeArgs,
        bool hasServiceProvider,
        bool hasKey,
        string? registrationKey,
        List<string> additionalArgs,
        string? returnTypeName,
        string serviceTypeName)
    {
        var args = new List<string>(additionalArgs.Count + 2);
        if(hasServiceProvider)
        {
            args.Add("sp");
        }

        if(hasKey && registrationKey is not null)
        {
            args.Add(registrationKey);
        }

        if(additionalArgs.Count > 0)
        {
            args.AddRange(additionalArgs);
        }

        var factoryCallPath = genericTypeArgs is not null ? $"{factoryPath}<{genericTypeArgs}>" : factoryPath;
        var factoryInvocation = $"{factoryCallPath}({string.Join(", ", args)})";

        if(returnTypeName is not null && returnTypeName != serviceTypeName)
        {
            factoryInvocation = $"({serviceTypeName}){factoryInvocation}";
        }

        return factoryInvocation;
    }

    /// <summary>
    /// Writes a factory registration line for keyed or non-keyed services.
    /// </summary>
    private static void WriteFactoryRegistrationLine(
        SourceWriter writer,
        string lifetime,
        string serviceTypeName,
        string? registrationKey,
        string factoryInvocation)
    {
        if(registrationKey is not null)
        {
            writer.WriteLine($"services.AddKeyed{lifetime}<{serviceTypeName}>({registrationKey}, ({IServiceProviderGlobalTypeName} sp, object? key) => {factoryInvocation});");
            return;
        }

        writer.WriteLine($"services.Add{lifetime}<{serviceTypeName}>(({IServiceProviderGlobalTypeName} sp) => {factoryInvocation});");
    }

    /// <summary>
    /// Writes registration code using a static instance specified in the attribute.
    /// Instance registrations are only valid for Singleton lifetime.
    /// </summary>
    /// <remarks>
    /// Generates code like:
    /// <code>
    /// services.AddSingleton&lt;IMySrevice&gt;(MyService.Default);
    /// // or for keyed:
    /// services.AddKeyedSingleton&lt;IMySrevice&gt;("key", MyService.Default);
    /// </code>
    /// </remarks>
    private static void WriteInstanceRegistration(SourceWriter writer, ServiceRegistrationModel registration)
    {
        var serviceTypeName = registration.ServiceType.Name;
        var instance = registration.Instance!;

        // Instance registration should only be used with Singleton
        // The analyzer should catch invalid lifetime usage
        if(registration.Key is not null)
        {
            // Keyed singleton with instance
            writer.WriteLine($"services.AddKeyedSingleton<{serviceTypeName}>({registration.Key}, {instance});");
        }
        else
        {
            // Non-keyed singleton with instance
            writer.WriteLine($"services.AddSingleton<{serviceTypeName}>({instance});");
        }
    }

    /// <summary>
    /// Writes registration code for service types (interfaces/base classes) that forward to an already-registered implementation.
    /// The implementation is already registered with its own factory method, so we just resolve it from the service provider.
    /// </summary>
    /// <remarks>
    /// Generates code like:
    /// <code>
    /// services.AddTransient&lt;IMyService&gt;(sp => sp.GetRequiredService&lt;MyService&gt;());
    /// </code>
    /// </remarks>
    private static void WriteServiceTypeForwardingRegistration(SourceWriter writer, ServiceRegistrationModel registration, string lifetime, HashSet<string>? asyncInitServiceTypeNames = null)
    {
        var serviceTypeName = registration.ServiceType.Name;
        var implTypeName = registration.ImplementationType.Name;

        // When the implementation type is registered as async-init (Task<ImplType>),
        // the forwarding registration must also use Task<ServiceType>.
        // We must use "async ... => await ..." because Task<T> is invariant in C# —
        // Task<MyService> cannot be implicitly assigned to Task<IMyService> even when
        // MyService : IMyService. The await unwraps the result and the async lambda
        // re-wraps it as Task<ServiceType>.
        bool isAsyncInit = asyncInitServiceTypeNames?.Contains(implTypeName) == true;
        if(isAsyncInit)
        {
            var taskServiceTypeName = $"global::System.Threading.Tasks.Task<{serviceTypeName}>";
            var taskImplTypeName = $"global::System.Threading.Tasks.Task<{implTypeName}>";
            if(registration.Key is not null)
            {
                var requiredCall = BuildServiceCall(GetRequiredKeyedService, taskImplTypeName, "key");
                writer.WriteLine($"services.AddKeyed{lifetime}<{taskServiceTypeName}>({registration.Key}, async ({IServiceProviderGlobalTypeName} sp, object? key) => await {requiredCall});");
            }
            else
            {
                var requiredCall = BuildServiceCall(GetRequiredService, taskImplTypeName, serviceKey: null);
                writer.WriteLine($"services.Add{lifetime}<{taskServiceTypeName}>(async ({IServiceProviderGlobalTypeName} sp) => await {requiredCall});");
            }
            return;
        }

        if(registration.Key is not null)
        {
            // Keyed registration - forward to keyed implementation
            var requiredCall = BuildServiceCall(GetRequiredKeyedService, implTypeName, "key");
            writer.WriteLine($"services.AddKeyed{lifetime}<{serviceTypeName}>({registration.Key}, ({IServiceProviderGlobalTypeName} sp, object? key) => {requiredCall});");
        }
        else
        {
            // Non-keyed registration - forward to implementation
            var requiredCall = BuildServiceCall(GetRequiredService, implTypeName, serviceKey: null);
            writer.WriteLine($"services.Add{lifetime}<{serviceTypeName}>(({IServiceProviderGlobalTypeName} sp) => {requiredCall});");
        }
    }

    /// <summary>
    /// Writes registration code for services with injection members (properties, fields, methods marked with InjectAttribute).
    /// </summary>
    /// <remarks>
    /// Generates code like:
    /// <code>
    /// services.AddSingleton&lt;MyService&gt;((IServiceProvider sp) =>
    /// {
    ///     var s0_p0 = sp.GetRequiredService&lt;IMayServiceDependency1&gt;();
    ///     var s0_p1 = sp.GetRequiredService&lt;IMayServiceDependency2&gt;();
    ///     var s0_p2 = sp.GetRequiredService&lt;IMayServiceDependency3&gt;();
    ///     var s0 = new MyService(s0_p0) { Dependency = s0_p1 };
    ///     s0.Initialize(s0_p2);
    ///     return s0;
    /// });
    /// </code>
    /// For optional parameters with default values, generates conditional logic:
    /// <code>
    /// var p0 = sp.GetService&lt;IOptionalDep&gt;();
    /// var s0 = p0 is not null ? new MyService(optDep: p0) : new MyService();
    /// </code>
    /// </remarks>
    private static void WriteInjectionRegistration(SourceWriter writer, ServiceRegistrationModel registration, string lifetime, HashSet<string>? asyncInitServiceTypeNames = null)
    {
        var serviceTypeName = registration.ServiceType.Name;
        var implTypeName = registration.ImplementationType.Name;
        var injectionMembers = registration.InjectionMembers;

        // Build the factory lambda
        WriteServiceRegistrationLambdaStart(writer, lifetime, serviceTypeName, registration.Key);

        writer.WriteLine("{");
        writer.Indentation++;

        bool isKeyedRegistration = registration.Key is not null;
        WriteConstructInstanceWithInjection(
            writer,
            instanceVarName: "s0",
            implTypeName: implTypeName,
            constructorParams: registration.ImplementationType.ConstructorParameters,
            injectionMembers: injectionMembers,
            isKeyedRegistration: isKeyedRegistration,
            registrationKey: registration.Key,
            serviceTypeNames: null,
            ctorTypeNameResolver: null,
            memberTypeNameResolver: null,
            decoratedPrevVar: null,
            asyncInitServiceTypeNames: asyncInitServiceTypeNames);

        writer.WriteLine("return s0;");

        writer.Indentation--;
        writer.WriteLine("});");
    }

    /// <summary>
    /// Writes registration code for services that have async injection methods.
    /// Generates a <c>Task&lt;T&gt;</c> registration with an async local <c>Init()</c> function
    /// that performs construction, sync injection, and awaited async injection in order.
    /// </summary>
    /// <remarks>
    /// Generates code like:
    /// <code>
    /// services.AddSingleton&lt;Task&lt;MyService&gt;&gt;((IServiceProvider sp) =>
    /// {
    ///     async Task&lt;MyService&gt; Init()
    ///     {
    ///         var s0_p0 = sp.GetRequiredService&lt;ILogger&gt;();
    ///         var s0_m0 = sp.GetRequiredService&lt;IAsyncInitializer&gt;();
    ///         var s0 = new MyService { Logger = s0_p0 };
    ///         await s0.InitAsync(s0_m0);
    ///         return s0;
    ///     }
    ///     return Init();
    /// });
    /// </code>
    /// </remarks>
    private static void WriteAsyncInjectionRegistration(SourceWriter writer, ServiceRegistrationModel registration, string lifetime, HashSet<string>? asyncInitServiceTypeNames = null)
    {
        var serviceTypeName = registration.ServiceType.Name;
        var implTypeName = registration.ImplementationType.Name;
        var injectionMembers = registration.InjectionMembers;
        bool isKeyedRegistration = registration.Key is not null;

        // Service type is wrapped in Task<T> for async-init registrations
        var taskServiceTypeName = $"global::System.Threading.Tasks.Task<{serviceTypeName}>";
        var taskImplTypeName = $"global::System.Threading.Tasks.Task<{implTypeName}>";

        // Open the registration lambda for Task<ServiceType>
        WriteServiceRegistrationLambdaStart(writer, lifetime, taskServiceTypeName, registration.Key);

        writer.WriteLine("{");
        writer.Indentation++;

        // Write the async local function header
        writer.WriteLine($"async {taskImplTypeName} Init()");
        writer.WriteLine("{");
        writer.Indentation++;

        // Emit construction with sync + async injection (isAsyncMode = true)
        WriteConstructInstanceWithInjection(
            writer,
            instanceVarName: "s0",
            implTypeName: implTypeName,
            constructorParams: registration.ImplementationType.ConstructorParameters,
            injectionMembers: injectionMembers,
            isKeyedRegistration: isKeyedRegistration,
            registrationKey: registration.Key,
            serviceTypeNames: null,
            ctorTypeNameResolver: null,
            memberTypeNameResolver: null,
            decoratedPrevVar: null,
            asyncInitServiceTypeNames: asyncInitServiceTypeNames,
            isAsyncMode: true);

        writer.WriteLine("return s0;");

        writer.Indentation--;
        writer.WriteLine("}");

        writer.WriteLine("return Init();");

        writer.Indentation--;
        writer.WriteLine("});");
    }

    

    /// <summary>
    /// Shared helper to construct an instance and apply property/field/method injection with conditional handling.
    /// Supports decorator scenarios via service-parameter detection and generic type substitution.
    /// </summary>
    private static void WriteConstructInstanceWithInjection(
        SourceWriter writer,
        string instanceVarName,
        string implTypeName,
        ImmutableEquatableArray<ParameterData>? constructorParams,
        ImmutableEquatableArray<InjectionMemberData> injectionMembers,
        bool isKeyedRegistration,
        string? registrationKey,
        HashSet<string>? serviceTypeNames,
        Func<TypeData, string>? ctorTypeNameResolver,
        Func<TypeData, string>? memberTypeNameResolver,
        string? decoratedPrevVar,
        HashSet<string>? asyncInitServiceTypeNames = null,
        bool isAsyncMode = false)
    {
        var ctorParams = constructorParams ?? [];
        var constructorParamEntries = new List<(string Name, string? Value, bool NeedsConditional)>(ctorParams.Length);
        int paramIndex = 0;

        foreach(var param in ctorParams)
        {
            var resolvedTypeName = ctorTypeNameResolver is not null ? ctorTypeNameResolver(param.Type) : param.Type.Name;
            if(decoratedPrevVar is not null && serviceTypeNames is not null && IsServiceTypeParameter(param.Type, resolvedTypeName, serviceTypeNames))
            {
                constructorParamEntries.Add((param.Name, decoratedPrevVar, false));
            }
            else
            {
                var varName = decoratedPrevVar is not null ? $"{instanceVarName}_p{paramIndex}" : $"p{paramIndex}";
                var resolvedVar = ResolveParamAndEmitVar(writer, param, varName, isKeyedRegistration, registrationKey, asyncInitServiceTypeNames);
                constructorParamEntries.Add((param.Name, resolvedVar, false));
                paramIndex++;
            }
        }

        if(constructorParamEntries.Any(e => e.NeedsConditional))
        {
            var conditionalParams = constructorParamEntries.Where(e => e.NeedsConditional && e.Value is not null).ToArray();
            var initializerPart = "";
            if(conditionalParams.Length == 1)
            {
                var condParam = conditionalParams[0];
                var withArgs = BuildArgumentListFromEntries([.. constructorParamEntries.Select(e => (e.Name, e.NeedsConditional ? e.Value : e.Value, false))]);
                var withoutArgs = BuildArgumentListFromEntries([.. constructorParamEntries.Select(e => (e.Name, e.NeedsConditional ? (string?)null : e.Value, false))]);
                var withInvocation = BuildConstructorInvocation(implTypeName, withArgs, initializerPart);
                var withoutInvocation = BuildConstructorInvocation(implTypeName, withoutArgs, initializerPart);
                writer.WriteLine($"var {instanceVarName} = {condParam.Value} is not null ? {withInvocation} : {withoutInvocation};");
            }
            else
            {
                var conditions = conditionalParams.Select(p => $"{p.Value} is not null").ToArray();
                var allCondition = string.Join(" && ", conditions);
                writer.WriteLine($"{implTypeName} {instanceVarName};");
                writer.WriteLine($"if ({allCondition})");
                writer.WriteLine("{");
                writer.Indentation++;
                var allArgs = BuildArgumentListFromEntries([.. constructorParamEntries.Select(e => (e.Name, e.Value, false))]);
                var allInvocation = BuildConstructorInvocation(implTypeName, allArgs, initializerPart);
                writer.WriteLine($"{instanceVarName} = {allInvocation};");
                writer.Indentation--;
                writer.WriteLine("}");
                writer.WriteLine("else");
                writer.WriteLine("{");
                writer.Indentation++;
                var fallbackArgs = BuildArgumentListFromEntries([.. constructorParamEntries.Select(e => (e.Name, e.NeedsConditional ? (string?)null : e.Value, false))]);
                var fallbackInvocation = BuildConstructorInvocation(implTypeName, fallbackArgs, initializerPart);
                writer.WriteLine($"{instanceVarName} = {fallbackInvocation};");
                writer.Indentation--;
                writer.WriteLine("}");
            }
        }
        else
        {
            // Unified construction behavior for both decorator and non-decorator cases
            EmitConstruction(
                writer,
                instanceVarName,
                implTypeName,
                constructorParamEntries,
                injectionMembers,
                isKeyedRegistration,
                registrationKey,
                memberTypeNameResolver,
                asyncInitServiceTypeNames,
                isAsyncMode);
        }

    }

    private static void EmitConstruction(
        SourceWriter writer,
        string instanceVarName,
        string implTypeName,
        List<(string Name, string? Value, bool NeedsConditional)> constructorParamEntries,
        ImmutableEquatableArray<InjectionMemberData> injectionMembers,
        bool isKeyedRegistration,
        string? registrationKey,
        Func<TypeData, string>? memberTypeNameResolver,
        HashSet<string>? asyncInitServiceTypeNames = null,
        bool isAsyncMode = false)
    {
        // Resolve property/field injection parameters
        int pfCount = injectionMembers.Count(m => m.MemberType is InjectionMemberType.Property or InjectionMemberType.Field);
        var preProps = pfCount > 0 ? new (string Name, string ParamVar)[pfCount] : [];
        int idx = 0;
        int pfIdxCounter = 0;
        foreach(var m in injectionMembers)
        {
            if(m.MemberType is not (InjectionMemberType.Property or InjectionMemberType.Field))
                continue;
            var varN = $"{instanceVarName}_p{pfIdxCounter}";
            var mt = m.Type;
            var mtName = mt is null ? "object" : (memberTypeNameResolver is not null ? memberTypeNameResolver(mt) : mt.Name);
            bool hasNonNullDefault = m.HasDefaultValue && !m.DefaultValueIsNull;
            ResolveMemberValue(writer, mt, mtName, varN, m.Key, m.IsNullable, hasNonNullDefault, m.DefaultValue, asyncInitServiceTypeNames);
            preProps[idx++] = (m.Name, varN);
            pfIdxCounter++;
        }

        // Resolve sync method parameters before instance creation
        var methodParamResolutions = new List<(string MethodName, string?[] ParamVars, string[] ParamNames)>();
        int memberParamIndex = pfIdxCounter;
        foreach(var method in injectionMembers)
        {
            if(method.MemberType != InjectionMemberType.Method)
                continue;
            var mParams = method.Parameters ?? [];
            var mVars = new string?[mParams.Length];
            var mNames = new string[mParams.Length];
            int mi = 0;
            foreach(var p in mParams)
            {
                var pVar = $"{instanceVarName}_m{memberParamIndex}";
                mNames[mi] = p.Name;
                if(method.Key is not null)
                {
                    mVars[mi] = ResolveMethodParameterWithKey(
                        writer,
                        p,
                        pVar,
                        method.Key,
                        isKeyedRegistration,
                        registrationKey,
                        memberTypeNameResolver,
                        asyncInitServiceTypeNames);
                }
                else
                {
                    var resolvedVar = ResolveParamAndEmitVar(writer, p, pVar, isKeyedRegistration, registrationKey, asyncInitServiceTypeNames);
                    mVars[mi] = resolvedVar;
                }
                mi++;
                memberParamIndex++;
            }
            methodParamResolutions.Add((method.Name, mVars, mNames));
        }

        // Resolve async method parameters before instance creation (only when in async mode)
        var asyncMethodParamResolutions = new List<(string MethodName, string?[] ParamVars, string[] ParamNames)>();
        if(isAsyncMode)
        {
            foreach(var method in injectionMembers)
            {
                if(method.MemberType != InjectionMemberType.AsyncMethod)
                    continue;
                var mParams = method.Parameters ?? [];
                var mVars = new string?[mParams.Length];
                var mNames = new string[mParams.Length];
                int mi = 0;
                foreach(var p in mParams)
                {
                    var pVar = $"{instanceVarName}_m{memberParamIndex}";
                    mNames[mi] = p.Name;
                    if(method.Key is not null)
                    {
                        mVars[mi] = ResolveMethodParameterWithKey(
                            writer,
                            p,
                            pVar,
                            method.Key,
                            isKeyedRegistration,
                            registrationKey,
                            memberTypeNameResolver,
                            asyncInitServiceTypeNames);
                    }
                    else
                    {
                        var resolvedVar = ResolveParamAndEmitVar(writer, p, pVar, isKeyedRegistration, registrationKey, asyncInitServiceTypeNames);
                        mVars[mi] = resolvedVar;
                    }
                    mi++;
                    memberParamIndex++;
                }
                asyncMethodParamResolutions.Add((method.Name, mVars, mNames));
            }
        }

        // Property/field values are resolved upfront; include all properties in the object initializer
        var propertyInits = preProps.Select(p => $"{p.Name} = {p.ParamVar}").ToArray();
        var constructorArgs = BuildArgumentListFromEntries([.. constructorParamEntries]);
        var initializerPart = propertyInits.Length > 0 ? $" {{ {string.Join(", ", propertyInits)} }}" : "";
        var constructorInvocation = BuildConstructorInvocation(implTypeName, constructorArgs, initializerPart);
        writer.WriteLine($"var {instanceVarName} = {constructorInvocation};");

        // Call sync methods
        foreach(var (mName, mVars, mNames) in methodParamResolutions)
        {
            var entries = new List<(string Name, string? Value, bool NeedsConditional)>(mVars.Length);
            for(int i = 0; i < mVars.Length; i++)
                entries.Add((mNames[i], mVars[i], false));
            var args = BuildArgumentListFromEntries([.. entries]);
            writer.WriteLine($"{instanceVarName}.{mName}({args});");
        }

        // Await async methods (only in async mode)
        foreach(var (mName, mVars, mNames) in asyncMethodParamResolutions)
        {
            var entries = new List<(string Name, string? Value, bool NeedsConditional)>(mVars.Length);
            for(int i = 0; i < mVars.Length; i++)
                entries.Add((mNames[i], mVars[i], false));
            var args = BuildArgumentListFromEntries([.. entries]);
            writer.WriteLine($"await {instanceVarName}.{mName}({args});");
        }
    }

    /// <summary>
    /// Builds a constructor invocation expression with an optional initializer.
    /// </summary>
    private static string BuildConstructorInvocation(string implTypeName, string args, string initializerPart) =>
        $"new {implTypeName}({args}){initializerPart}";

    /// <summary>
    /// Resolves a property or field injection value and emits its variable declaration.
    /// </summary>
    private static void ResolveMemberValue(
        SourceWriter writer,
        TypeData? memberType,
        string memberTypeName,
        string paramVar,
        string? serviceKey,
        bool isNullable,
        bool hasNonNullDefault,
        string? defaultValue,
        HashSet<string>? asyncInitServiceTypeNames = null)
    {
        if(memberType is CollectionWrapperTypeData)
        {
            WriteCollectionResolution(writer, memberType, paramVar, serviceKey, isOptional: isNullable);
            return;
        }

        if(memberType is LazyTypeData or FuncTypeData or DictionaryTypeData or KeyValuePairTypeData or TaskTypeData)
        {
            WriteWrapperResolution(writer, memberType, paramVar, serviceKey, isOptional: isNullable, asyncInitServiceTypeNames);
            return;
        }

        if(hasNonNullDefault)
        {
            var defExpr = defaultValue ?? "default";
            var svcCall = BuildServiceCall(serviceKey is not null ? GetKeyedService : GetService, memberTypeName, serviceKey);
            writer.WriteLine($"var {paramVar} = {svcCall} ?? {defExpr};");
            return;
        }

        var methodName = isNullable
            ? (serviceKey is not null ? GetKeyedService : GetService)
            : (serviceKey is not null ? GetRequiredKeyedService : GetRequiredService);
        var call = BuildServiceCall(methodName, memberTypeName, serviceKey);
        writer.WriteLine($"var {paramVar} = {call};");
    }

    /// <summary>
    /// Resolves a keyed method parameter and emits its variable declaration.
    /// </summary>
    private static string? ResolveMethodParameterWithKey(
        SourceWriter writer,
        ParameterData param,
        string paramVar,
        string methodKey,
        bool isKeyedRegistration,
        string? registrationKey,
        Func<TypeData, string>? typeNameResolver,
        HashSet<string>? asyncInitServiceTypeNames = null)
    {
        if(TryResolveCommonParameter(writer, param, paramVar, isKeyedRegistration, registrationKey, methodKey, isOptional: false, typeNameResolver, asyncInitServiceTypeNames, out var resolvedVar))
        {
            return resolvedVar!;
        }

        var resolvedTypeName = typeNameResolver is not null ? typeNameResolver(param.Type) : param.Type.Name;
        if(param.HasDefaultValue)
        {
            var defExpr = param.DefaultValue ?? "default";
            var svcCall = BuildServiceCall(GetKeyedService, resolvedTypeName, methodKey);
            writer.WriteLine($"var {paramVar} = {svcCall} ?? {defExpr};");
            return paramVar;
        }

        var requiredCall = BuildServiceCall(GetRequiredKeyedService, resolvedTypeName, methodKey);
        writer.WriteLine($"var {paramVar} = {requiredCall};");
        return paramVar;
    }



    /// <summary>
    /// Builds an argument list from entries with conditional flag.
    /// </summary>
    private static string BuildArgumentListFromEntries((string Name, string? Value, bool NeedsConditional)[] entries)
    {
        // Check if any parameter uses default value
        bool hasDefaultValue = entries.Any(e => e.Value is null);

        if(!hasDefaultValue)
        {
            // All values present - use positional arguments
            return string.Join(", ", entries.Select(e => e.Value!));
        }

        // Some values are null - use named arguments for non-null values only
        var namedArgs = entries.Where(e => e.Value is not null).Select(e => $"{e.Name}: {e.Value}");
        return string.Join(", ", namedArgs);
    }

    /// <summary>
    /// Converts a TypeData to typeof() syntax for open generic types.
    /// For example: TypeData with Name="global::Namespace.GenericTest&lt;T&gt;" becomes "typeof(global::Namespace.GenericTest&lt;&gt;)"
    /// </summary>
    private static string ConvertToTypeOf(TypeData typeData)
    {
        if(typeData is not GenericTypeData genericTypeData || genericTypeData.GenericArity == 0)
        {
            return $"typeof({typeData.Name})";
        }

        // Build the open generic typeof
        return $"typeof({genericTypeData.NameWithoutGeneric}{GetGenericString(genericTypeData.GenericArity)})";
    }

    /// <summary>
    /// Cached generic arity strings to avoid repeated allocations.
    /// </summary>
    private static readonly string[] s_genericArityStrings =
    [
        "<>",
        "<,>",
        "<,,>",
        "<,,,>",
        "<,,,,>",
        "<,,,,,>",
        "<,,,,,,>",
        "<,,,,,,,>",
        "<,,,,,,,,>"
    ];

    private static string GetGenericString(in int arity) =>
        arity <= 9 ? s_genericArityStrings[arity - 1] : '<' + new string(',', arity - 1) + '>';

    /// <summary>
    /// Writes decorator pattern registration code.
    /// </summary>
    /// <remarks>
    /// Generates code like:
    /// <code>
    /// services.AddSingleton&lt;IMyService&gt;((IServiceProvider sp) =>
    /// {
    ///     var s0 = sp.GetRequiredService&lt;MyService&gt;();
    ///     var s1_p0 = sp.GetRequiredService&lt;ILogger&lt;MyServiceDecorator2&gt;&gt;();
    ///     var s1 = new MyServiceDecorator2(s1_p0, s0);
    ///     var s2_p0 = sp.GetRequiredService&lt;ILogger&lt;MyServiceDecorator&gt;&gt;();
    ///     var s2 = new MyServiceDecorator(s2_p0, s1);
    ///     return s2;
    /// });
    /// </code>
    /// For open generic decorators, falls back to ActivatorUtilities.CreateInstance.
    /// </remarks>
    private static void WriteDecoratorRegistration(SourceWriter writer, ServiceRegistrationModel registration, string lifetime, HashSet<string>? asyncInitServiceTypeNames = null)
    {
        var decorators = registration.Decorators;
        // Decorators array is in order from outermost to innermost,
        // we iterate in reverse order for building the chain from inner to outer
        var decoratorCount = decorators.Length;

        // Get generic arguments from the service type (for closed generic service types)
        var serviceTypeParams = registration.ServiceType is GenericTypeData genericServiceType
            ? genericServiceType.TypeParameters
            : null;
        var serviceTypeName = registration.ServiceType.Name;

        // Build service type names set for IsServiceParameter check
        var serviceTypeNames = BuildServiceTypeNames(registration);

        WriteServiceRegistrationLambdaStart(writer, lifetime, serviceTypeName, registration.Key);

        writer.WriteLine("{");
        writer.Indentation++;

        // s0 = implementation instance
        if(registration.Key is not null)
        {
            writer.WriteLine($"var s0 = sp.GetRequiredKeyedService<{registration.ImplementationType.Name}>(key);");
        }
        else
        {
            writer.WriteLine($"var s0 = sp.GetRequiredService<{registration.ImplementationType.Name}>();");
        }

        // Build decorator chain (iterate in reverse order: from innermost to outermost)
        for(int i = 0; i < decoratorCount; i++)
        {
            var decorator = decorators[decoratorCount - 1 - i];
            var prevVar = $"s{i}";
            var currentVar = $"s{i + 1}";

            var decoratorTypeName = GetClosedDecoratorTypeName(decorator, serviceTypeParams);
            var ctorParams = decorator.ConstructorParameters;
            if(ctorParams is null || ctorParams.Length == 0)
            {
                writer.WriteLine($"var {currentVar} = global::Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance<{decoratorTypeName}>(sp, {prevVar});");
                continue;
            }

            // Use shared helper to construct decorator with Option A conditional handling and service parameter wiring
            bool isKeyedRegistration = registration.Key is not null;
            WriteConstructInstanceWithInjection(
                writer,
                instanceVarName: currentVar,
                implTypeName: decoratorTypeName,
                constructorParams: ctorParams,
                injectionMembers: decorator.InjectionMembers ?? [],
                isKeyedRegistration: isKeyedRegistration,
                registrationKey: registration.Key,
                serviceTypeNames: serviceTypeNames,
                ctorTypeNameResolver: t => decorator is GenericTypeData { IsOpenGeneric: true } && serviceTypeParams is not null ? SubstituteGenericArguments(t, decorator, serviceTypeParams) : t.Name,
                memberTypeNameResolver: t => decorator is GenericTypeData { IsOpenGeneric: true } && serviceTypeParams is not null ? SubstituteGenericArguments(t, decorator, serviceTypeParams) : t.Name,
                decoratedPrevVar: prevVar,
                asyncInitServiceTypeNames: asyncInitServiceTypeNames);
        }

        // Return the outermost decorator
        writer.WriteLine($"return s{decoratorCount};");

        writer.Indentation--;
        writer.WriteLine("});");
    }

    /// <summary>
    /// Gets the closed decorator type name by substituting generic arguments if the decorator is an open generic.
    /// </summary>
    /// <param name="decorator">The decorator type data.</param>
    /// <param name="serviceTypeParams">The type parameters from the service type.</param>
    /// <returns>The closed decorator type name.</returns>
    private static string GetClosedDecoratorTypeName(TypeData decorator, ImmutableEquatableArray<TypeParameter>? serviceTypeParams)
    {
        // If decorator is not open generic, return as-is
        if(decorator is not GenericTypeData { IsOpenGeneric: true } genericDecorator)
        {
            return decorator.Name;
        }

        // If no generic arguments available from service type, return as-is (this shouldn't happen in valid scenarios)
        if(serviceTypeParams is null || serviceTypeParams.Length == 0)
        {
            return decorator.Name;
        }

        // Replace the open generic parameters with the service type's generic arguments
        // e.g., "global::Namespace.Decorator<TRequest, TResponse>" -> "global::Namespace.Decorator<global::Ns.TestRequest, global::Ns.TestResponse>"
        return $"{genericDecorator.NameWithoutGeneric}<{string.Join(", ", serviceTypeParams.Select(a => a.Type.Name))}>";
    }

    /// <summary>
    /// Substitutes generic type parameters in a parameter type with actual generic arguments.
    /// </summary>
    /// <param name="paramType">The parameter type data that may contain type parameters.</param>
    /// <param name="decorator">The decorator type data containing type parameter information.</param>
    /// <param name="serviceTypeParams">The type parameters from the service type.</param>
    /// <returns>The type name with substituted generic arguments.</returns>
    private static string SubstituteGenericArguments(TypeData paramType, TypeData decorator, ImmutableEquatableArray<TypeParameter> serviceTypeParams)
    {
        // Use pre-extracted type arguments from TypeData
        var decoratorTypeParams = decorator is GenericTypeData genericDecorator
            ? genericDecorator.TypeParameters
            : null;
        if(decoratorTypeParams is null || decoratorTypeParams.Length == 0)
        {
            return paramType.Name;
        }

        if(serviceTypeParams.Length != decoratorTypeParams.Length)
        {
            // Mismatch in arity, return original
            return paramType.Name;
        }

        // Build replacement map and apply substitutions
        var result = paramType.Name;
        for(int i = 0; i < decoratorTypeParams.Length; i++)
        {
            // Replace type parameter with actual argument from service type
            // Need to be careful to replace whole type names, not partial matches
            result = ReplaceTypeParameter(result, decoratorTypeParams[i].ParameterName, serviceTypeParams[i].Type.Name);
        }

        return result;
    }

    /// <summary>
    /// Builds a set of service type names for IsServiceParameter check.
    /// Includes the service type, implementation type, all base classes, and all interfaces.
    /// This ensures decorator parameters that reference any service type are correctly identified.
    /// </summary>
    private static HashSet<string> BuildServiceTypeNames(ServiceRegistrationModel registration)
    {
        var serviceTypeNames = new HashSet<string>(StringComparer.Ordinal);

        // Add service type variants
        AddTypeNameVariants(serviceTypeNames, registration.ServiceType);

        // Add implementation type variants
        AddTypeNameVariants(serviceTypeNames, registration.ImplementationType);

        // Add all base classes (important for decorator parameter matching)
        if(registration.ImplementationType.AllBaseClasses is not null)
        {
            foreach(var baseClass in registration.ImplementationType.AllBaseClasses)
            {
                AddTypeNameVariants(serviceTypeNames, baseClass);
            }
        }

        // Add all interfaces (important when multiple service types exist)
        if(registration.ImplementationType.AllInterfaces is not null)
        {
            foreach(var iface in registration.ImplementationType.AllInterfaces)
            {
                AddTypeNameVariants(serviceTypeNames, iface);
            }
        }

        return serviceTypeNames;
    }

    /// <summary>
    /// Adds both the full name and non-generic name variants to the set.
    /// </summary>
    private static void AddTypeNameVariants(HashSet<string> set, TypeData type)
    {
        set.Add(type.Name);
        if(type is GenericTypeData genericType && type.Name != genericType.NameWithoutGeneric)
        {
            set.Add(genericType.NameWithoutGeneric);
        }
    }

    /// <summary>
    /// Checks if a parameter type matches any of the service types.
    /// </summary>
    private static bool IsServiceTypeParameter(TypeData paramType, string substitutedTypeName, HashSet<string> serviceTypeNames)
    {
        // Check substituted type name first (for open generic decorators)
        if(serviceTypeNames.Contains(substitutedTypeName))
        {
            return true;
        }

        // Direct match on full name or non-generic name
        if(serviceTypeNames.Contains(paramType.Name))
        {
            return true;
        }

        return paramType is GenericTypeData genericParamType
            && serviceTypeNames.Contains(genericParamType.NameWithoutGeneric);
    }

    /// <summary>
    /// Writes parameter resolution code for [ServiceKey] attribute.
    /// When the service is registered as keyed, injects the registration key with appropriate type casting.
    /// When the service is not keyed, injects null.
    /// </summary>
    /// <param name="writer">The source writer.</param>
    /// <param name="paramVar">The variable name for this parameter.</param>
    /// <param name="paramTypeName">The resolved parameter type name.</param>
    /// <param name="isKeyedRegistration">Whether this is a keyed service registration.</param>
    /// <param name="registrationKey">The registration key for keyed services.</param>
    /// <returns>The variable name or expression to use for this parameter.</returns>
    private static string WriteServiceKeyParameterResolution(
        SourceWriter writer,
        string paramVar,
        string paramTypeName,
        bool isKeyedRegistration,
        string? registrationKey)
    {
        if(isKeyedRegistration && registrationKey is not null)
        {
            writer.WriteLine($"var {paramVar} = {registrationKey};");
        }
        else
        {
            // Non-keyed registration: use the default value for the key type
            writer.WriteLine($"var {paramVar} = default({paramTypeName});");
        }
        return paramVar;
    }

    /// <summary>
    /// Resolve a parameter and emit its variable declaration.
    /// Produces lines like:
    /// var p = sp.GetService<T>() ?? <default>;
    /// var p = sp.GetKeyedService<T>(key) ?? <default>;
    /// or returns "sp" for IServiceProvider parameters (no var emitted).
    /// </summary>
    private static string ResolveParamAndEmitVar(
        SourceWriter writer,
        ParameterData param,
        string paramVar,
        bool isKeyedRegistration,
        string? registrationKey = null,
        HashSet<string>? asyncInitServiceTypeNames = null)
    {
        var paramTypeName = param.Type.Name;

        if(TryResolveCommonParameter(writer, param, paramVar, isKeyedRegistration, registrationKey, param.ServiceKey, param.IsOptional, typeNameResolver: null, asyncInitServiceTypeNames, out var resolvedVar))
        {
            return resolvedVar!;
        }

        // General case: if the parameter is optional (HasDefaultValue or IsOptional), use GetService + ?? default; otherwise use GetRequiredService
        if(param.HasDefaultValue || param.IsOptional)
        {
            var methodName = param.ServiceKey is not null ? GetKeyedService : GetService;
            var svcCall = BuildServiceCall(methodName, paramTypeName, param.ServiceKey);
            var defExpr = param.HasDefaultValue ? (param.DefaultValue ?? "default") : "default";
            writer.WriteLine($"var {paramVar} = {svcCall} ?? {defExpr};");
            return paramVar;
        }
        else
        {
            var methodName = param.ServiceKey is not null ? GetRequiredKeyedService : GetRequiredService;
            var svcCall = BuildServiceCall(methodName, paramTypeName, param.ServiceKey);
            writer.WriteLine($"var {paramVar} = {svcCall};");
            return paramVar;
        }
    }

    /// <summary>
    /// Writes collection resolution code for constructor parameters and injection members.
    /// Handles all collection types including IEnumerable&lt;T&gt;, IList&lt;T&gt;, T[], IReadOnlyList&lt;T&gt;, etc.
    /// </summary>
    /// <param name="writer">The source writer.</param>
    /// <param name="type">The type data of the collection.</param>
    /// <param name="paramVar">The variable name for this parameter.</param>
    /// <param name="serviceKey">The service key (null for non-keyed services).</param>
    /// <param name="isOptional">Whether the parameter is optional (uses GetService instead of GetRequiredService).</param>
    private static void WriteCollectionResolution(
        SourceWriter writer,
        TypeData type,
        string paramVar,
        string? serviceKey,
        bool isOptional = false)
    {
        var isKeyed = serviceKey is not null;

        // Extract element type name based on collection type
        var elementTypeName = type switch
        {
            EnumerableTypeData e => e.ElementType.Name,
            ReadOnlyCollectionTypeData r => r.ElementType.Name,
            CollectionTypeData c => c.ElementType.Name,
            ReadOnlyListTypeData rl => rl.ElementType.Name,
            ListTypeData l => l.ElementType.Name,
            ArrayTypeData a => a.ElementType.Name,
            _ => null
        };

        if(elementTypeName is null)
        {
            // Fallback: not a collection type, use direct service resolution
            if(isKeyed)
            {
                var method = isOptional ? GetKeyedService : GetRequiredKeyedService;
                var call = BuildServiceCall(method, type.Name, serviceKey);
                writer.WriteLine($"var {paramVar} = {call};");
            }
            else
            {
                var method = isOptional ? GetService : GetRequiredService;
                var call = BuildServiceCall(method, type.Name, serviceKey: null);
                writer.WriteLine($"var {paramVar} = {call};");
            }
            return;
        }

        // Use WrapperKind to determine the resolution method
        switch(((WrapperTypeData)type).WrapperKind)
        {
            case WrapperKind.Enumerable:
                // IEnumerable<T> - use GetServices directly
                if(isKeyed)
                {
                    var call = BuildServiceCall(GetKeyedServices, elementTypeName, serviceKey);
                    writer.WriteLine($"var {paramVar} = {call};");
                }
                else
                {
                    var call = BuildServiceCall(GetServices, elementTypeName, serviceKey: null);
                    writer.WriteLine($"var {paramVar} = {call};");
                }
                break;

            case WrapperKind.ReadOnlyCollection:
            case WrapperKind.Collection:
            case WrapperKind.ReadOnlyList:
            case WrapperKind.List:
            case WrapperKind.Array:
                // IReadOnlyCollection<T>, ICollection<T>, IReadOnlyList<T>, IList<T>, T[] - resolve as array
                if(isKeyed)
                {
                    var call = BuildServiceCall(GetKeyedServices, elementTypeName, serviceKey);
                    writer.WriteLine($"var {paramVar} = {call}.ToArray();");
                }
                else
                {
                    var call = BuildServiceCall(GetServices, elementTypeName, serviceKey: null);
                    writer.WriteLine($"var {paramVar} = {call}.ToArray();");
                }
                break;

            default:
                // Fallback for unknown collection types
                if(isKeyed)
                {
                    var method = isOptional ? GetKeyedService : GetRequiredKeyedService;
                    var call = BuildServiceCall(method, type.Name, serviceKey);
                    writer.WriteLine($"var {paramVar} = {call};");
                }
                else
                {
                    var method = isOptional ? GetService : GetRequiredService;
                    var call = BuildServiceCall(method, type.Name, serviceKey: null);
                    writer.WriteLine($"var {paramVar} = {call};");
                }
                break;
        }
    }

    /// <summary>
    /// Writes wrapper type resolution code for Lazy&lt;T&gt;, Func&lt;T&gt;, IDictionary&lt;TKey, TValue&gt;,
    /// and KeyValuePair&lt;TKey, TValue&gt;. Supports nested wrapper types (e.g., Lazy&lt;KeyValuePair&lt;K, V&gt;&gt;).
    /// </summary>
    /// <param name="writer">The source writer.</param>
    /// <param name="type">The wrapper type data.</param>
    /// <param name="paramVar">The variable name for this parameter.</param>
    /// <param name="serviceKey">The service key (null for non-keyed services).</param>
    /// <param name="isOptional">Whether the parameter is optional.</param>
    private static void WriteWrapperResolution(
        SourceWriter writer,
        TypeData type,
        string paramVar,
        string? serviceKey,
        bool isOptional = false,
        HashSet<string>? asyncInitServiceTypeNames = null)
    {
        var expr = BuildWrapperExpression(type, serviceKey, isOptional, asyncInitServiceTypeNames);
        writer.WriteLine($"var {paramVar} = {expr};");
    }

    /// <summary>
    /// Builds an inline wrapper expression. Recursively handles nested wrappers.
    /// </summary>
    /// <param name="type">The wrapper type data to build an expression for.</param>
    /// <param name="serviceKey">The service key (null for non-keyed services).</param>
    /// <param name="isOptional">Whether this resolution is optional.</param>
    /// <returns>A C# expression string that resolves the wrapper type.</returns>
    private static string BuildWrapperExpression(TypeData type, string? serviceKey, bool isOptional, HashSet<string>? asyncInitServiceTypeNames = null)
    {
        switch(type)
        {
            case LazyTypeData lazy:
            {
                var innerType = lazy.InstanceType;
                // Direct Lazy<T> where T is not a wrapper — resolve from DI (standalone registration exists)
                if(innerType is not WrapperTypeData)
                {
                    var methodName = isOptional
                        ? (serviceKey is not null ? GetKeyedService : GetService)
                        : (serviceKey is not null ? GetRequiredKeyedService : GetRequiredService);
                    return BuildServiceCall(methodName, type.Name, serviceKey);
                }
                // Nested wrapper (e.g., Lazy<IEnumerable<T>>) — inline construction
                var lazyInnerExpr = BuildInnerResolutionExpression(innerType, serviceKey, isOptional, asyncInitServiceTypeNames);
                return $"new global::System.Lazy<{innerType.Name}>(() => {lazyInnerExpr}, global::System.Threading.LazyThreadSafetyMode.ExecutionAndPublication)";
            }

            case FuncTypeData func:
            {
                var innerType = func.ReturnType;
                if(func.HasInputParameters)
                {
                    var methodName = isOptional
                        ? (serviceKey is not null ? GetKeyedService : GetService)
                        : (serviceKey is not null ? GetRequiredKeyedService : GetRequiredService);
                    return BuildServiceCall(methodName, type.Name, serviceKey);
                }

                // Direct Func<T> where T is not a wrapper — resolve from DI (standalone registration exists)
                if(innerType is not WrapperTypeData)
                {
                    var methodName = isOptional
                        ? (serviceKey is not null ? GetKeyedService : GetService)
                        : (serviceKey is not null ? GetRequiredKeyedService : GetRequiredService);
                    return BuildServiceCall(methodName, type.Name, serviceKey);
                }
                // Nested wrapper (e.g., Func<IEnumerable<T>>) — inline construction
                var funcInnerExpr = BuildInnerResolutionExpression(innerType, serviceKey, isOptional, asyncInitServiceTypeNames);
                return $"new global::System.Func<{innerType.Name}>(() => {funcInnerExpr})";
            }

            case KeyValuePairTypeData kvp:
            {
                var keyType = kvp.KeyType;
                var valueType = kvp.ValueType;
                // KeyValuePair uses the registration's service key as the key value
                var keyExpr = serviceKey ?? "default";
                var valueExpr = BuildInnerResolutionExpression(valueType, serviceKey, isOptional, asyncInitServiceTypeNames);
                return $"new global::System.Collections.Generic.KeyValuePair<{keyType.Name}, {valueType.Name}>({keyExpr}, {valueExpr})";
            }

            case DictionaryTypeData dict:
            {
                // Dictionary resolution: collect all KeyValuePair<K,V> services and convert to dictionary.
                var keyType = dict.KeyType;
                var valueType = dict.ValueType;
                var kvpTypeName = $"global::System.Collections.Generic.KeyValuePair<{keyType.Name}, {valueType.Name}>";
                var getServicesCall = BuildServiceCall(
                    serviceKey is not null ? GetKeyedServices : GetServices,
                    kvpTypeName,
                    serviceKey);
                return $"{getServicesCall}.ToDictionary()";
            }

            case TaskTypeData task:
            {
                // Task<T> wrapper: if inner type is an async-init service, resolve Task<T> directly;
                // otherwise wrap synchronous resolution in Task.FromResult(...).
                var innerTypeName = task.InnerType.Name;
                if(asyncInitServiceTypeNames?.Contains(innerTypeName) == true)
                {
                    // Async-init service: Task<T> is registered directly.
                    var methodName = isOptional
                        ? (serviceKey is not null ? GetKeyedService : GetService)
                        : (serviceKey is not null ? GetRequiredKeyedService : GetRequiredService);
                    return BuildServiceCall(methodName, type.Name, serviceKey);
                }
                else
                {
                    // Sync-only service: wrap with Task.FromResult.
                    var syncMethodName = isOptional
                        ? (serviceKey is not null ? GetKeyedService : GetService)
                        : (serviceKey is not null ? GetRequiredKeyedService : GetRequiredService);
                    var syncCall = BuildServiceCall(syncMethodName, innerTypeName, serviceKey);
                    return $"global::System.Threading.Tasks.Task.FromResult({syncCall})";
                }
            }

            default:
            {
                // Fallback for non-wrapper types
                var methodName = isOptional
                    ? (serviceKey is not null ? GetKeyedService : GetService)
                    : (serviceKey is not null ? GetRequiredKeyedService : GetRequiredService);
                return BuildServiceCall(methodName, type.Name, serviceKey);
            }
        }
    }

    /// <summary>
    /// Builds an inner resolution expression — either a nested wrapper expression, a collection
    /// expression, or a direct service call. Supports nesting such as Lazy&lt;IEnumerable&lt;T&gt;&gt;.
    /// </summary>
    private static string BuildInnerResolutionExpression(TypeData innerType, string? serviceKey, bool isOptional, HashSet<string>? asyncInitServiceTypeNames = null)
    {
        // If the inner type is itself a wrapper, recurse to handle nesting (e.g., Lazy<KeyValuePair<K,V>>)
        if(innerType is LazyTypeData or FuncTypeData or KeyValuePairTypeData or DictionaryTypeData or TaskTypeData)
        {
            return BuildWrapperExpression(innerType, serviceKey, isOptional, asyncInitServiceTypeNames);
        }

        // Collection types inside wrappers (e.g., Lazy<IEnumerable<T>>)
        if(innerType is CollectionWrapperTypeData collectionInner)
        {
            var elementTypeName = (string?)collectionInner.ElementType.Name;

            if(elementTypeName is not null)
            {
                var getServicesCall = BuildServiceCall(
                    serviceKey is not null ? GetKeyedServices : GetServices,
                    elementTypeName,
                    serviceKey);
                return innerType is CollectionWrapperTypeData and not EnumerableTypeData
                    ? $"{getServicesCall}.ToArray()"
                    : getServicesCall;
            }
        }

        // Otherwise, use direct service resolution
        var methodName = isOptional
            ? (serviceKey is not null ? GetKeyedService : GetService)
            : (serviceKey is not null ? GetRequiredKeyedService : GetRequiredService);
        return BuildServiceCall(methodName, innerType.Name, serviceKey);
    }

    /// <summary>
    /// Builds a service resolution call for keyed or non-keyed services.
    /// </summary>
    private static string BuildServiceCall(string methodName, string typeName, string? serviceKey) =>
        serviceKey is not null
            ? $"sp.{methodName}<{typeName}>({serviceKey})"
            : $"sp.{methodName}<{typeName}>()";

    /// <summary>
    /// Attempts to resolve common parameter cases and emit any required variable declarations.
    /// Returns true when a resolution was produced.
    /// </summary>
    private static bool TryResolveCommonParameter(
        SourceWriter writer,
        ParameterData param,
        string paramVar,
        bool isKeyedRegistration,
        string? registrationKey,
        string? serviceKey,
        bool isOptional,
        Func<TypeData, string>? typeNameResolver,
        HashSet<string>? asyncInitServiceTypeNames,
        out string? resolvedVar)
    {
        if(IsServiceProviderType(param.Type.Name))
        {
            resolvedVar = "sp";
            return true;
        }

        var resolvedTypeName = typeNameResolver is not null ? typeNameResolver(param.Type) : param.Type.Name;
        if(param.HasServiceKeyAttribute)
        {
            resolvedVar = WriteServiceKeyParameterResolution(writer, paramVar, resolvedTypeName, isKeyedRegistration, registrationKey);
            return true;
        }

        if(param.Type is CollectionWrapperTypeData)
        {
            WriteCollectionResolution(writer, param.Type, paramVar, serviceKey, isOptional);
            resolvedVar = paramVar;
            return true;
        }

        if(param.Type is LazyTypeData or FuncTypeData or DictionaryTypeData or KeyValuePairTypeData or TaskTypeData)
        {
            WriteWrapperResolution(writer, param.Type, paramVar, serviceKey, isOptional, asyncInitServiceTypeNames);
            resolvedVar = paramVar;
            return true;
        }

        resolvedVar = null;
        return false;
    }

    /// <summary>
    /// Checks if the type name represents System.IServiceProvider.
    /// </summary>
    private static bool IsServiceProviderType(string typeName) =>
        typeName is IServiceProviderGlobalTypeName or IServiceProviderTypeName or "IServiceProvider";

    /// <summary>
    /// Builds the generic type arguments string for a generic factory method.
    /// Uses the <see cref="GenericFactoryTypeMapping"/> to map placeholder types in the service type template
    /// to the actual types from the closed service type.
    /// </summary>
    /// <param name="factory">The factory method data containing the generic type mapping.</param>
    /// <param name="closedServiceType">The closed service type to extract type arguments from.</param>
    /// <returns>The generic type arguments string (e.g., "Entity, Dto"), or null if not a generic factory.</returns>
    /// <example>
    /// Given:
    /// - ServiceTypeTemplate: IRequestHandler&lt;Task&lt;int&gt;&gt;
    /// - PlaceholderToTypeParamMap: { "int" -> 0 }
    /// - ClosedServiceType: IRequestHandler&lt;Task&lt;Entity&gt;&gt;
    /// Returns: "Entity"
    /// </example>
    private static string? BuildGenericFactoryTypeArgs(FactoryMethodData factory, TypeData closedServiceType)
    {
        var mapping = factory.GenericTypeMapping;
        if(mapping is null || factory.TypeParameterCount == 0)
        {
            return null;
        }

        var template = mapping.ServiceTypeTemplate;
        var placeholderMap = mapping.PlaceholderToTypeParamMap;

        // Build a map from placeholder types to actual types by comparing template with closed service type
        var placeholderToActualType = new Dictionary<string, string>(StringComparer.Ordinal);
        ExtractPlaceholderMappings(template, closedServiceType, placeholderToActualType);

        // Build type arguments array in the order of factory method's type parameters
        var typeArgs = new string[factory.TypeParameterCount];
        foreach(var kvp in placeholderMap)
        {
            var placeholderTypeName = kvp.Key;
            var typeParamIndex = kvp.Value;

            if(typeParamIndex < 0 || typeParamIndex >= typeArgs.Length)
            {
                continue;
            }

            if(placeholderToActualType.TryGetValue(placeholderTypeName, out var actualTypeName))
            {
                typeArgs[typeParamIndex] = actualTypeName;
            }
        }

        // Validate all type arguments are filled
        foreach(var arg in typeArgs)
        {
            if(string.IsNullOrEmpty(arg))
            {
                return null; // Missing type argument, cannot generate generic call
            }
        }

        return string.Join(", ", typeArgs);
    }

    /// <summary>
    /// Recursively extracts mappings from placeholder types in the template to actual types in the closed type.
    /// </summary>
    private static void ExtractPlaceholderMappings(
        TypeData template,
        TypeData closed,
        Dictionary<string, string> placeholderToActualType)
    {
        if(template is not GenericTypeData genericTemplate || closed is not GenericTypeData genericClosed)
        {
            return;
        }

        // If base type names don't match, can't extract mappings
        if(genericTemplate.NameWithoutGeneric != genericClosed.NameWithoutGeneric)
        {
            return;
        }

        var templateParams = genericTemplate.TypeParameters;
        var closedParams = genericClosed.TypeParameters;

        if(templateParams is null || closedParams is null)
        {
            return;
        }

        if(templateParams.Length != closedParams.Length)
        {
            return;
        }

        for(int i = 0; i < templateParams.Length; i++)
        {
            var templateParamType = templateParams[i].Type;
            var closedParamType = closedParams[i].Type;

            // If the template param is a simple type (no nested type parameters),
            // it's a placeholder that maps to the closed param type
            if(templateParamType is not GenericTypeData { TypeParameters.Length: > 0 })
            {
                // Map the template type name to the closed type name
                // e.g., "global::System.Int32" -> "global::TestNamespace.Entity"
                placeholderToActualType[templateParamType.Name] = closedParamType.Name;
            }
            else
            {
                // Nested generic type, recurse
                ExtractPlaceholderMappings(templateParamType, closedParamType, placeholderToActualType);
            }
        }
    }
}