using System.Text;

namespace SourceGen.Ioc.Cli.Commands;

public sealed class GenerateCommands(
    ILogger<GenerateCommands> logger,
    GlobalOptions globalOptions,
    IFileSystem fileSystem,
    IEnvironmentProvider environmentProvider)
{
    private readonly ILogger<GenerateCommands> logger = logger;
    private readonly GlobalOptions globalOptions = globalOptions;
    private readonly IFileSystem fileSystem = fileSystem;
    private readonly IEnvironmentProvider environmentProvider = environmentProvider;

    /// <summary>
    /// Collect class and generate [IocRegisterFor] annotations.
    /// </summary>
    /// <param name="outputPath">-o, Output file path.</param>
    /// <param name="target">-t, Target directory or file, default is current directory.</param>
    /// <param name="filePattern">-f, File pattern to filter files.</param>
    /// <param name="searchSubDirectories">-s, Whether to search sub directories.</param>
    /// <param name="classNameRegex">-cn, Regex pattern to match class names.
    ///                                   Full regex will be: "(public|internal)\s+(?!static\s+)[\w\s]*class\s+(classNameRegex)(?=\s|:|$)"</param>
    /// <param name="fullRegex">Full regex pattern to match file content.</param>
    /// <param name="maxApply">-m, How many matches should apply, 0 means unlimited.</param>
    /// <param name="isGenericAttribute">-ig, Whether to generate generic attribute syntax.</param>
    /// <returns></returns>
    [Command("ioc-for")]
    public async Task GenerateIocRegisterFor(
        string outputPath,
        string? target = null,
        string filePattern = "*.cs",
        bool searchSubDirectories = false,
        string? classNameRegex = null,
        string? fullRegex = null,
        int maxApply = 0,
        bool isGenericAttribute = false,
        CancellationToken ct = default)
    {
        if(string.IsNullOrWhiteSpace(outputPath))
        {
            logger.ZLogError($"-o|--output-path can not be empty!");
            return;
        }

        if(string.IsNullOrWhiteSpace(filePattern))
        {
            logger.ZLogError($"-f|--file-pattern can not be empty!");
            return;
        }

        if(string.IsNullOrWhiteSpace(classNameRegex) && string.IsNullOrWhiteSpace(fullRegex))
        {
            logger.ZLogError($"-cn|--class-name-regex and --full-regex can not all be empty! You must specify at least one.");
            return;
        }
        Regex regex;
        if(!string.IsNullOrWhiteSpace(fullRegex))
        {
            regex = CreateFullMatchRegex(fullRegex);
        }
        else if(!string.IsNullOrWhiteSpace(classNameRegex))
        {
            regex = CreateClassMatchRegex(classNameRegex);
        }
        else
        {
            throw new UnreachableException();
        }

        // When using classNameRegex, we need to extract the class name from the match
        bool useClassNameExtraction = !string.IsNullOrWhiteSpace(classNameRegex);

        int classCount = 0;
        List<string> collectedClasses = [];
        bool targetIsEmpty = string.IsNullOrWhiteSpace(target);
        if(targetIsEmpty || fileSystem.Directory.Exists(target))
        {
            var files = fileSystem.Directory.EnumerateFiles(
                targetIsEmpty ? environmentProvider.CurrentDirectory : target!,
                filePattern,
                searchSubDirectories ? SearchOption.AllDirectories : SearchOption.TopDirectoryOnly);

            foreach(var file in files)
            {
                var result = await ProcessFile(file, regex, maxApply, classCount, useClassNameExtraction, ct);
                collectedClasses.AddRange(result.Classes);
                classCount = result.ClassCount;
                if(maxApply > 0 && classCount >= maxApply)
                {
                    logger.ZLogInformation($"Reached the --maxApply:{maxApply} limit. Stopping further processing.");
                    break;
                }
            }
        }
        else if(fileSystem.File.Exists(target))
        {
            var result = await ProcessFile(target, regex, maxApply, classCount, useClassNameExtraction, ct);
            collectedClasses.AddRange(result.Classes);
            classCount = result.ClassCount;
        }
        else
        {
            logger.ZLogError($"Target path does not exist: {target}");
            return;
        }

        logger.ZLogInformation($"Total class count: {classCount}");

        StringBuilder sb = new();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using SourceGen.Ioc;");
        foreach(var c in collectedClasses)
        {
            if(isGenericAttribute)
                sb.AppendLine($"[assembly: IocRegisterFor<{c}>]");
            else
                sb.AppendLine($"[assembly: IocRegisterFor(typeof({c}))]");
        }
        sb.AppendLine();

        if(globalOptions.DryRun)
        {
            logger.ZLogInformation($"[Dry Run] Generated file content:{environmentProvider.NewLine}{sb.ToString()}");
            return;
        }

        await fileSystem.File.WriteAllTextAsync(outputPath, sb.ToString(), ct);
        logger.ZLogInformation($"Generated file at: {outputPath}");
    }

    private async Task<(int ClassCount, List<string> Classes)> ProcessFile(string file, Regex regex, int maxApply, int classCount, bool useClassNameExtraction, CancellationToken ct)
    {
        logger.ZLogTrace($"Processing file: {file}");

        if(!fileSystem.File.Exists(file))
        {
            logger.ZLogWarning($"File not found: {file}");
            return (classCount, []);
        }

        var content = await fileSystem.File.ReadAllTextAsync(file, ct);

        return MatchFileContent(regex, content, maxApply, classCount, useClassNameExtraction, logger);
    }

    public static (int Count, List<string> Result) MatchFileContent(
        Regex regex, string fileContent, int maxApply, int count, bool useClassNameExtraction, ILogger? logger = null)
    {
        int remainingCount = maxApply > 0 ? maxApply - count : int.MaxValue;

        // Extract namespace from file content
        string? ns = useClassNameExtraction ? ExtractNamespace(fileContent) : null;
        string prefix = ns is not null ? $"{ns}." : "";

        List<string> result = [];
        var ms = regex.Matches(fileContent);
        foreach(Match match in ms)
        {
            if(remainingCount <= 0)
                break;

            count++;
            remainingCount--;

            // Extract only the class name when using class name extraction
            string className = useClassNameExtraction
                ? ExtractClassName(match)
                : match.Value;

            string fullName = $"{prefix}{className}";
            logger?.ZLogTrace($"Matched class: {fullName}");
            result.Add(fullName);
        }

        return (count, result);
    }
}
