namespace SourceGen.Ioc.SourceGenerator.Register;

partial class RegisterSourceGenerator
{
    private static void GenerateOutput(
        in SourceProductionContext ctx,
        ImmutableEquatableDictionary<string, ImmutableEquatableArray<ServiceRegistrationModel>> registrationsByMethod,
        string rootNamespace,
        string assemblyName,
        string? customIocName)
    {
        if(registrationsByMethod.Count == 0)
            return;

        // Generate source
        var source = GenerateExtensionMethodSource(registrationsByMethod, rootNamespace, assemblyName, customIocName);
        ctx.AddSource($"{assemblyName}.ServiceRegistration.g.cs", source);
    }

    private static string GenerateExtensionMethodSource(
        ImmutableEquatableDictionary<string, ImmutableEquatableArray<ServiceRegistrationModel>> registrationsByMethod,
        string rootNamespace,
        string assemblyName,
        string? customIocName)
    {
        var writer = new SourceWriter();

        writer.WriteLine("// <auto-generated/>");
        writer.WriteLine("#nullable enable");
        writer.WriteLine();
        writer.WriteLine("using Microsoft.Extensions.DependencyInjection;");
        writer.WriteLine("using System.Linq;");
        writer.WriteLine();

        writer.WriteLine($"namespace {GetSafeNamespace(rootNamespace)}");
        writer.WriteLine("{");
        writer.Indentation++;

        // Use custom IoC name if provided, otherwise use assembly name
        var methodBaseName = !string.IsNullOrWhiteSpace(customIocName)
            ? GetSafeMethodName(customIocName!)
            : GetSafeMethodName(assemblyName);

        writer.WriteLine("/// <summary>");
        writer.WriteLine($"/// Extension methods for registering services from {assemblyName}.");
        writer.WriteLine("/// </summary>");
        writer.WriteLine($"public static class {methodBaseName}ServiceCollectionExtensions");
        writer.WriteLine("{");
        writer.Indentation++;

        bool isFirst = true;
        foreach(var kvp in registrationsByMethod)
        {
            var methodKey = kvp.Key;
            var registrations = kvp.Value;

            if(!isFirst)
            {
                writer.WriteLine();
            }
            isFirst = false;

            if(string.IsNullOrEmpty(methodKey))
            {
                // Default method
                GenerateRegistrationMethod(writer, registrations, methodBaseName, "Registers all default services.");
            }
            else
            {
                // Tag-specific method
                var safeTagName = GetSafeMethodName(methodKey);
                GenerateRegistrationMethod(
                    writer,
                    registrations,
                    $"{methodBaseName}_{safeTagName}",
                    $"Registers all services tagged with '{methodKey}'.");
            }
        }

        writer.Indentation--;
        writer.WriteLine("}");

        writer.Indentation--;
        writer.WriteLine("}");

        return writer.ToString();
    }

    /// <summary>
    /// Generates a single registration method.
    /// </summary>
    private static void GenerateRegistrationMethod(
        SourceWriter writer,
        ImmutableEquatableArray<ServiceRegistrationModel> registrations,
        string methodName,
        string summary)
    {
        writer.WriteLine("/// <summary>");
        writer.WriteLine($"/// {summary}");
        writer.WriteLine("/// </summary>");
        writer.WriteLine($"public static IServiceCollection Add{methodName}(this IServiceCollection services)");
        writer.WriteLine("{");
        writer.Indentation++;

        foreach(var registration in registrations)
        {
            WriteRegistration(writer, registration);
        }

        writer.WriteLine();
        writer.WriteLine("return services;");

        writer.Indentation--;
        writer.WriteLine("}");
    }

    private static void WriteRegistration(SourceWriter writer, ServiceRegistrationModel registration)
    {
        var lifetime = registration.Lifetime.Name;
        var serviceTypeName = registration.ServiceType.Name;
        var implTypeName = registration.ImplementationType.Name;

        // Check if this registration uses Factory or Instance
        bool hasFactory = registration.Factory is not null;
        bool hasInstance = registration.Instance is not null;

        // Handle Factory registration first (takes precedence)
        if(hasFactory)
        {
            WriteFactoryMethodRegistration(writer, registration, lifetime);
            return;
        }

        // Handle Instance registration (only for Singleton)
        if(hasInstance)
        {
            if(registration.Lifetime == ServiceLifetime.Singleton)
                WriteInstanceRegistration(writer, registration);

            return;
        }

        // Check if service type is different from implementation type (registering interface/base class)
        bool isServiceTypeRegistration = serviceTypeName != implTypeName;

        // Check if this registration has decorators and is not the implementation type itself
        bool hasDecorators = registration.Decorators.Length > 0 && isServiceTypeRegistration;

        // Check if this registration has injection members (properties, fields, methods with [Inject])
        bool hasInjectionMembers = registration.InjectionMembers.Length > 0;

        // Check if the constructor was selected by [Inject] attribute (requires factory for proper constructor selection)
        bool hasInjectConstructor = registration.ImplementationType.HasInjectConstructor;

        // Check if any constructor parameter has [Inject] attribute (SourceGen.Ioc specific, MS.DI doesn't recognize it)
        // Note: [FromKeyedServices], IServiceProvider parameters are handled by MS.DI automatically
        var constructorParams = registration.ImplementationType.ConstructorParameters;
        bool hasSpecialConstructorParams = constructorParams?.Any(static p => p.HasInjectAttribute) == true;

        // Check if any constructor parameter is a non-IEnumerable collection type (IList<T>, T[], IReadOnlyList<T>, etc.)
        // MS.DI only supports automatic injection for IEnumerable<T>, other collection types require factory method
        // This check uses pre-computed IsNonEnumerableCollection from TypeData
        bool hasNonEnumerableCollectionParams = constructorParams?.Any(static p => p.Type.IsNonEnumerableCollection) == true;

        // Determine if factory construction is needed:
        // - Injection members (properties, fields, methods) always require factory
        // - Constructor with [Inject] attribute requires factory (to use correct constructor)
        // - Constructor parameters with [Inject] attribute require factory (MS.DI doesn't recognize [Inject])
        // - Constructor parameters with non-IEnumerable collection types require factory (MS.DI doesn't support them)
        bool needsFactoryConstruction = hasInjectionMembers || hasInjectConstructor || hasSpecialConstructorParams || hasNonEnumerableCollectionParams;

        if(hasDecorators)
        {
            WriteDecoratorRegistration(writer, registration, lifetime);
        }
        else if(needsFactoryConstruction && !registration.IsOpenGeneric && isServiceTypeRegistration)
        {
            // Service type registration (interface/base class) where implementation is already registered with factory
            // Just resolve the implementation from the service provider
            WriteServiceTypeForwardingRegistration(writer, registration, lifetime);
        }
        else if(needsFactoryConstruction && !registration.IsOpenGeneric)
        {
            // Self registration with injection members or constructor params with special handling - generate factory method
            WriteInjectionRegistration(writer, registration, lifetime);
        }
        else if(registration.IsOpenGeneric)
        {
            // Open generic registration requires typeof() syntax
            var serviceTypeOf = ConvertToTypeOf(registration.ServiceType);
            var implTypeOf = ConvertToTypeOf(registration.ImplementationType);

            if(registration.Key != null)
            {
                writer.WriteLine($"services.AddKeyed{lifetime}({serviceTypeOf}, {registration.Key}, {implTypeOf});");
            }
            else
            {
                writer.WriteLine($"services.Add{lifetime}({serviceTypeOf}, {implTypeOf});");
            }
        }
        else if(registration.Key != null)
        {
            // Keyed registration
            writer.WriteLine($"services.AddKeyed{lifetime}<{serviceTypeName}, {registration.ImplementationType.Name}>({registration.Key});");
        }
        else
        {
            // Non-keyed registration
            writer.WriteLine($"services.Add{lifetime}<{serviceTypeName}, {registration.ImplementationType.Name}>();");
        }
    }

    /// <summary>
    /// Writes registration code using a factory method specified in the attribute.
    /// </summary>
    /// <remarks>
    /// Supports factory methods with different parameter combinations:
    /// <list type="bullet">
    ///   <item>No parameters: <c>services.AddSingleton&lt;IService&gt;(Factory());</c></item>
    ///   <item>IServiceProvider only: <c>services.AddSingleton&lt;IService&gt;(sp => Factory(sp));</c></item>
    ///   <item>object key only (keyed): <c>services.AddKeyedSingleton&lt;IService&gt;("key", (sp, key) => Factory(key));</c></item>
    ///   <item>Both (keyed): <c>services.AddKeyedSingleton&lt;IService&gt;("key", (sp, key) => Factory(sp, key));</c></item>
    /// </list>
    /// If the factory return type differs from the service type, adds a cast.
    /// </remarks>
    private static void WriteFactoryMethodRegistration(SourceWriter writer, ServiceRegistrationModel registration, string lifetime)
    {
        var serviceTypeName = registration.ServiceType.Name;
        var factory = registration.Factory!;
        var factoryPath = factory.Path;
        var hasServiceProvider = factory.HasServiceProvider;
        var hasKey = factory.HasKey;
        var returnTypeName = factory.ReturnTypeName;

        // Build factory invocation based on parameters
        string factoryInvocation = (hasServiceProvider, hasKey) switch
        {
            (true, true) => $"{factoryPath}(sp, key)",
            (true, false) => $"{factoryPath}(sp)",
            (false, true) => $"{factoryPath}(key)",
            (false, false) => $"{factoryPath}()"
        };

        // Add cast if return type differs from service type
        if(returnTypeName is not null && returnTypeName != serviceTypeName)
        {
            factoryInvocation = $"({serviceTypeName}){factoryInvocation}";
        }

        if(registration.Key is not null)
        {
            // Keyed registration with factory
            writer.WriteLine($"services.AddKeyed{lifetime}<{serviceTypeName}>({registration.Key}, (global::System.IServiceProvider sp, object? key) => {factoryInvocation});");
        }
        else if(hasServiceProvider)
        {
            // Non-keyed registration with factory
            writer.WriteLine($"services.Add{lifetime}<{serviceTypeName}>((global::System.IServiceProvider sp) => {factoryInvocation});");
        }
        else
        {
            // No parameters factory - direct invocation
            writer.WriteLine($"services.Add{lifetime}<{serviceTypeName}>({factoryInvocation});");
        }
    }

    /// <summary>
    /// Writes registration code using a static instance specified in the attribute.
    /// Instance registrations are only valid for Singleton lifetime.
    /// </summary>
    /// <remarks>
    /// Generates code like:
    /// <code>
    /// services.AddSingleton&lt;IMySrevice&gt;(MyService.Default);
    /// // or for keyed:
    /// services.AddKeyedSingleton&lt;IMySrevice&gt;("key", MyService.Default);
    /// </code>
    /// </remarks>
    private static void WriteInstanceRegistration(SourceWriter writer, ServiceRegistrationModel registration)
    {
        var serviceTypeName = registration.ServiceType.Name;
        var instance = registration.Instance!;

        // Instance registration should only be used with Singleton
        // The analyzer should catch invalid lifetime usage
        if(registration.Key is not null)
        {
            // Keyed singleton with instance
            writer.WriteLine($"services.AddKeyedSingleton<{serviceTypeName}>({registration.Key}, {instance});");
        }
        else
        {
            // Non-keyed singleton with instance
            writer.WriteLine($"services.AddSingleton<{serviceTypeName}>({instance});");
        }
    }

    /// <summary>
    /// Writes registration code for service types (interfaces/base classes) that forward to an already-registered implementation.
    /// The implementation is already registered with its own factory method, so we just resolve it from the service provider.
    /// </summary>
    /// <remarks>
    /// Generates code like:
    /// <code>
    /// services.AddTransient&lt;IMyService&gt;(sp => sp.GetRequiredService&lt;MyService&gt;());
    /// </code>
    /// </remarks>
    private static void WriteServiceTypeForwardingRegistration(SourceWriter writer, ServiceRegistrationModel registration, string lifetime)
    {
        var serviceTypeName = registration.ServiceType.Name;
        var implTypeName = registration.ImplementationType.Name;

        if(registration.Key is not null)
        {
            // Keyed registration - forward to keyed implementation
            writer.WriteLine($"services.AddKeyed{lifetime}<{serviceTypeName}>({registration.Key}, (global::System.IServiceProvider sp, object? key) => sp.GetRequiredKeyedService<{implTypeName}>(key));");
        }
        else
        {
            // Non-keyed registration - forward to implementation
            writer.WriteLine($"services.Add{lifetime}<{serviceTypeName}>((global::System.IServiceProvider sp) => sp.GetRequiredService<{implTypeName}>());");
        }
    }

    /// <summary>
    /// Writes registration code for services with injection members (properties, fields, methods marked with InjectAttribute).
    /// </summary>
    /// <remarks>
    /// Generates code like:
    /// <code>
    /// services.AddSingleton&lt;MyService&gt;((IServiceProvider sp) =>
    /// {
    ///     var s0_p0 = sp.GetRequiredService&lt;IMayServiceDependency1&gt;();
    ///     var s0_p1 = sp.GetRequiredService&lt;IMayServiceDependency2&gt;();
    ///     var s0_p2 = sp.GetRequiredService&lt;IMayServiceDependency3&gt;();
    ///     var s0 = new MyService(s0_p0) { Dependency = s0_p1 };
    ///     s0.Initialize(s0_p2);
    ///     return s0;
    /// });
    /// </code>
    /// </remarks>
    private static void WriteInjectionRegistration(SourceWriter writer, ServiceRegistrationModel registration, string lifetime)
    {
        var serviceTypeName = registration.ServiceType.Name;
        var implTypeName = registration.ImplementationType.Name;
        var injectionMembers = registration.InjectionMembers;

        // Build the factory lambda
        if(registration.Key is not null)
        {
            // Keyed registration with injection
            writer.WriteLine($"services.AddKeyed{lifetime}<{serviceTypeName}>({registration.Key}, (global::System.IServiceProvider sp, object? key) =>");
        }
        else
        {
            // Non-keyed registration with injection
            writer.WriteLine($"services.Add{lifetime}<{serviceTypeName}>((global::System.IServiceProvider sp) =>");
        }

        writer.WriteLine("{");
        writer.Indentation++;

        // Resolve constructor parameters
        var constructorParams = registration.ImplementationType.ConstructorParameters ?? [];
        var constructorParamVars = new string[constructorParams.Length];
        bool isKeyedRegistration = registration.Key is not null;
        int paramIndex = 0;

        foreach(var param in constructorParams)
        {
            var paramVar = $"p{paramIndex}";
            constructorParamVars[paramIndex] = WriteParameterResolution(writer, param, paramVar, param.Type.Name, isKeyedRegistration);
            paramIndex++;
        }

        // Count property/field and method members for pre-allocation
        int propertyFieldCount = 0;
        int methodCount = 0;
        foreach(var member in injectionMembers)
        {
            if(member.MemberType is InjectionMemberType.Property or InjectionMemberType.Field)
                propertyFieldCount++;
            else if(member.MemberType == InjectionMemberType.Method)
                methodCount++;
        }

        // Pre-allocate arrays based on counts
        var propertyInitializers = propertyFieldCount > 0 ? new string[propertyFieldCount] : [];
        var methodCalls = methodCount > 0 ? new (string MethodName, string[] ParamVars)[methodCount] : [];

        // Process property/field injection parameters
        int propertyIndex = 0;
        int memberParamIndex = 0;
        foreach(var member in injectionMembers)
        {
            if(member.MemberType is not (InjectionMemberType.Property or InjectionMemberType.Field))
                continue;

            var paramVar = $"s0_p{memberParamIndex}";
            var memberTypeName = member.Type?.Name ?? "object";

            if(member.Key is not null)
            {
                var getKeyedServiceMethod = member.IsOptional ? "GetKeyedService" : "GetRequiredKeyedService";
                writer.WriteLine($"var {paramVar} = sp.{getKeyedServiceMethod}<{memberTypeName}>({member.Key});");
            }
            else
            {
                var getServiceMethod = member.IsOptional ? "GetService" : "GetRequiredService";
                writer.WriteLine($"var {paramVar} = sp.{getServiceMethod}<{memberTypeName}>();");
            }

            propertyInitializers[propertyIndex++] = $"{member.Name} = {paramVar}";
            memberParamIndex++;
        }

        // Process method injection parameters
        int methodIndex = 0;
        foreach(var method in injectionMembers)
        {
            if(method.MemberType != InjectionMemberType.Method)
                continue;

            var methodParams = method.Parameters ?? [];
            var methodParamVars = new string[methodParams.Length];
            int methodParamIdx = 0;

            foreach(var param in methodParams)
            {
                var paramVar = $"s0_m{memberParamIndex}";

                if(method.Key is not null)
                {
                    // Method has explicit key from [Inject] attribute
                    if(IsServiceProviderType(param.Type.Name))
                    {
                        methodParamVars[methodParamIdx++] = "sp";
                    }
                    else
                    {
                        writer.WriteLine($"var {paramVar} = sp.GetRequiredKeyedService<{param.Type.Name}>({method.Key});");
                        methodParamVars[methodParamIdx++] = paramVar;
                    }
                }
                else
                {
                    methodParamVars[methodParamIdx++] = WriteParameterResolution(writer, param, paramVar, param.Type.Name, isKeyedRegistration);
                }
                memberParamIndex++;
            }

            methodCalls[methodIndex++] = (method.Name, methodParamVars);
        }

        // Create the instance with constructor and property initializers
        var constructorArgs = string.Join(", ", constructorParamVars);

        if(propertyInitializers.Length > 0)
        {
            var initializerList = string.Join(", ", propertyInitializers);
            writer.WriteLine($"var s0 = new {implTypeName}({constructorArgs}) {{ {initializerList} }};");
        }
        else
        {
            writer.WriteLine($"var s0 = new {implTypeName}({constructorArgs});");
        }

        // Call injection methods
        foreach(var (methodName, methodParamVars) in methodCalls)
        {
            var methodArgs = string.Join(", ", methodParamVars);
            writer.WriteLine($"s0.{methodName}({methodArgs});");
        }

        // Return the instance
        writer.WriteLine("return s0;");

        writer.Indentation--;
        writer.WriteLine("});");
    }

    /// <summary>
    /// Converts a TypeData to typeof() syntax for open generic types.
    /// For example: TypeData with Name="global::Namespace.GenericTest&lt;T&gt;" becomes "typeof(global::Namespace.GenericTest&lt;&gt;)"
    /// </summary>
    private static string ConvertToTypeOf(TypeData typeData)
    {
        if(typeData.GenericArity == 0)
        {
            return $"typeof({typeData.Name})";
        }

        // Build the open generic typeof
        return $"typeof({typeData.NameWithoutGeneric}{GetGenericString(typeData.GenericArity)})";
    }

    /// <summary>
    /// Cached generic arity strings to avoid repeated allocations.
    /// </summary>
    private static readonly string[] s_genericArityStrings =
    [
        "<>",
        "<,>",
        "<,,>",
        "<,,,>",
        "<,,,,>",
        "<,,,,,>",
        "<,,,,,,>",
        "<,,,,,,,>",
        "<,,,,,,,,>"
    ];

    private static string GetGenericString(in int arity) =>
        arity <= 9 ? s_genericArityStrings[arity - 1] : '<' + new string(',', arity - 1) + '>';

    /// <summary>
    /// Writes decorator pattern registration code.
    /// </summary>
    /// <remarks>
    /// Generates code like:
    /// <code>
    /// services.AddSingleton&lt;IMyService&gt;((IServiceProvider sp) =>
    /// {
    ///     var s0 = sp.GetRequiredService&lt;MyService&gt;();
    ///     var s1_p0 = sp.GetRequiredService&lt;ILogger&lt;MyServiceDecorator2&gt;&gt;();
    ///     var s1 = new MyServiceDecorator2(s1_p0, s0);
    ///     var s2_p0 = sp.GetRequiredService&lt;ILogger&lt;MyServiceDecorator&gt;&gt;();
    ///     var s2 = new MyServiceDecorator(s2_p0, s1);
    ///     return s2;
    /// });
    /// </code>
    /// For open generic decorators, falls back to ActivatorUtilities.CreateInstance.
    /// </remarks>
    private static void WriteDecoratorRegistration(SourceWriter writer, ServiceRegistrationModel registration, string lifetime)
    {
        var decorators = registration.Decorators;
        // Decorators array is in order from outermost to innermost,
        // we iterate in reverse order for building the chain from inner to outer
        var decoratorCount = decorators.Length;

        // Get generic arguments from the service type (for closed generic service types)
        var serviceTypeParams = registration.ServiceType.TypeParameters;
        var serviceTypeName = registration.ServiceType.Name;

        // Build service type names set for IsServiceParameter check
        var serviceTypeNames = BuildServiceTypeNames(registration);

        if(registration.Key is not null)
        {
            writer.WriteLine($"services.AddKeyed{lifetime}<{serviceTypeName}>({registration.Key}, (global::System.IServiceProvider sp, object? key) =>");
        }
        else
        {
            writer.WriteLine($"services.Add{lifetime}<{serviceTypeName}>((global::System.IServiceProvider sp) =>");
        }

        writer.WriteLine("{");
        writer.Indentation++;

        // s0 = implementation instance
        if(registration.Key is not null)
        {
            writer.WriteLine($"var s0 = sp.GetRequiredKeyedService<{registration.ImplementationType.Name}>(key);");
        }
        else
        {
            writer.WriteLine($"var s0 = sp.GetRequiredService<{registration.ImplementationType.Name}>();");
        }

        // Build decorator chain (iterate in reverse order: from innermost to outermost)
        for(int i = 0; i < decoratorCount; i++)
        {
            // Access decorators in reverse order
            var decorator = decorators[decoratorCount - 1 - i];
            var prevVar = $"s{i}";
            var currentVar = $"s{i + 1}";

            // If the decorator is an open generic, substitute with the service type's generic arguments
            var decoratorTypeName = GetClosedDecoratorTypeName(decorator, serviceTypeParams);

            // Get constructor parameters and generate service resolution for each
            var constructorParams = decorator.ConstructorParameters ?? [];
            if(constructorParams.Length == 0)
            {
                // No constructor info available, use ActivatorUtilities as fallback (Shouldn't reach here)
                writer.WriteLine($"var {currentVar} = global::Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance<{decoratorTypeName}>(sp, {prevVar});");
            }
            else
            {
                // Resolve each non-service parameter from IServiceProvider
                var paramVars = new string[constructorParams.Length];
                int paramIndex = 0;
                int paramVarIndex = 0;
                foreach(var param in constructorParams)
                {
                    // Check if this parameter is the service type being decorated
                    // For open generic decorators, substitute type parameters first
                    var paramTypeName = decorator.IsOpenGeneric && serviceTypeParams is not null
                        ? SubstituteGenericArguments(param.Type, decorator, serviceTypeParams)
                        : param.Type.Name;

                    if(IsServiceTypeParameter(param.Type, paramTypeName, serviceTypeNames))
                    {
                        // This is the decorated service, use the previous variable
                        paramVars[paramVarIndex++] = prevVar;
                    }
                    else
                    {
                        // This is a dependency, resolve it from service provider
                        var paramVar = $"{currentVar}_p{paramIndex}";
                        bool isKeyedRegistration = registration.Key is not null;
                        paramVars[paramVarIndex++] = WriteParameterResolution(writer, param, paramVar, paramTypeName, isKeyedRegistration);
                        paramIndex++;
                    }
                }

                // Create the decorator instance with resolved parameters
                var paramList = string.Join(", ", paramVars);
                writer.WriteLine($"var {currentVar} = new {decoratorTypeName}({paramList});");
            }
        }

        // Return the outermost decorator
        writer.WriteLine($"return s{decoratorCount};");

        writer.Indentation--;
        writer.WriteLine("});");
    }

    /// <summary>
    /// Gets the closed decorator type name by substituting generic arguments if the decorator is an open generic.
    /// </summary>
    /// <param name="decorator">The decorator type data.</param>
    /// <param name="serviceTypeParams">The type parameters from the service type.</param>
    /// <returns>The closed decorator type name.</returns>
    private static string GetClosedDecoratorTypeName(TypeData decorator, ImmutableEquatableArray<TypeParameter>? serviceTypeParams)
    {
        // If decorator is not open generic, return as-is
        if(!decorator.IsOpenGeneric)
        {
            return decorator.Name;
        }

        // If no generic arguments available from service type, return as-is (this shouldn't happen in valid scenarios)
        if(serviceTypeParams is null || serviceTypeParams.Length == 0)
        {
            return decorator.Name;
        }

        // Replace the open generic parameters with the service type's generic arguments
        // e.g., "global::Namespace.Decorator<TRequest, TResponse>" -> "global::Namespace.Decorator<global::Ns.TestRequest, global::Ns.TestResponse>"
        return $"{decorator.NameWithoutGeneric}<{string.Join(", ", serviceTypeParams.Select(a => a.Type.Name))}>";
    }

    /// <summary>
    /// Substitutes generic type parameters in a parameter type with actual generic arguments.
    /// </summary>
    /// <param name="paramType">The parameter type data that may contain type parameters.</param>
    /// <param name="decorator">The decorator type data containing type parameter information.</param>
    /// <param name="serviceTypeParams">The type parameters from the service type.</param>
    /// <returns>The type name with substituted generic arguments.</returns>
    private static string SubstituteGenericArguments(TypeData paramType, TypeData decorator, ImmutableEquatableArray<TypeParameter> serviceTypeParams)
    {
        // Use pre-extracted type arguments from TypeData
        var decoratorTypeParams = decorator.TypeParameters;
        if(decoratorTypeParams is null || decoratorTypeParams.Length == 0)
        {
            return paramType.Name;
        }

        if(serviceTypeParams.Length != decoratorTypeParams.Length)
        {
            // Mismatch in arity, return original
            return paramType.Name;
        }

        // Build replacement map and apply substitutions
        var result = paramType.Name;
        for(int i = 0; i < decoratorTypeParams.Length; i++)
        {
            // Replace type parameter with actual argument from service type
            // Need to be careful to replace whole type names, not partial matches
            result = ReplaceTypeParameter(result, decoratorTypeParams[i].ParameterName, serviceTypeParams[i].Type.Name);
        }

        return result;
    }

    /// <summary>
    /// Builds a set of service type names for IsServiceParameter check.
    /// Includes the service type, implementation type, all base classes, and all interfaces.
    /// This ensures decorator parameters that reference any service type are correctly identified.
    /// </summary>
    private static HashSet<string> BuildServiceTypeNames(ServiceRegistrationModel registration)
    {
        var serviceTypeNames = new HashSet<string>(StringComparer.Ordinal);

        // Add service type variants
        AddTypeNameVariants(serviceTypeNames, registration.ServiceType);

        // Add implementation type variants
        AddTypeNameVariants(serviceTypeNames, registration.ImplementationType);

        // Add all base classes (important for decorator parameter matching)
        if(registration.ImplementationType.AllBaseClasses is not null)
        {
            foreach(var baseClass in registration.ImplementationType.AllBaseClasses)
            {
                AddTypeNameVariants(serviceTypeNames, baseClass);
            }
        }

        // Add all interfaces (important when multiple service types exist)
        if(registration.ImplementationType.AllInterfaces is not null)
        {
            foreach(var iface in registration.ImplementationType.AllInterfaces)
            {
                AddTypeNameVariants(serviceTypeNames, iface);
            }
        }

        return serviceTypeNames;
    }

    /// <summary>
    /// Adds both the full name and non-generic name variants to the set.
    /// </summary>
    private static void AddTypeNameVariants(HashSet<string> set, TypeData type)
    {
        set.Add(type.Name);
        if(type.Name != type.NameWithoutGeneric)
        {
            set.Add(type.NameWithoutGeneric);
        }
    }

    /// <summary>
    /// Checks if a parameter type matches any of the service types.
    /// </summary>
    private static bool IsServiceTypeParameter(TypeData paramType, string substitutedTypeName, HashSet<string> serviceTypeNames)
    {
        // Check substituted type name first (for open generic decorators)
        if(serviceTypeNames.Contains(substitutedTypeName))
        {
            return true;
        }

        // Direct match on full name or non-generic name
        return serviceTypeNames.Contains(paramType.Name)
            || serviceTypeNames.Contains(paramType.NameWithoutGeneric);
    }

    /// <summary>
    /// Writes parameter resolution code and returns the variable name to use.
    /// Handles special cases: IServiceProvider, [FromKeyedServices], [Inject] with key, and keyed service key parameter.
    /// </summary>
    /// <param name="writer">The source writer.</param>
    /// <param name="param">The parameter data.</param>
    /// <param name="paramVar">The variable name for this parameter.</param>
    /// <param name="paramTypeName">The resolved parameter type name (for generic substitution).</param>
    /// <param name="isKeyedRegistration">Whether this is a keyed service registration.</param>
    /// <returns>The variable name or expression to use for this parameter.</returns>
    private static string WriteParameterResolution(
        SourceWriter writer,
        ParameterData param,
        string paramVar,
        string paramTypeName,
        bool isKeyedRegistration)
    {
        // Case 1: IServiceProvider - pass sp directly
        if(IsServiceProviderType(paramTypeName))
        {
            return "sp";
        }

        // Case 2: [FromKeyedServices] or [Inject] attribute with key - use the specified key
        if(param.ServiceKey is not null)
        {
            var getKeyedServiceMethod = param.IsOptional ? "GetKeyedService" : "GetRequiredKeyedService";
            writer.WriteLine($"var {paramVar} = sp.{getKeyedServiceMethod}<{paramTypeName}>({param.ServiceKey});");
            return paramVar;
        }

        // Case 3: Keyed registration with object/object? parameter named key/serviceKey - pass the key
        if(isKeyedRegistration && IsServiceKeyParameter(param))
        {
            return "key";
        }

        // Case 4: Non-IEnumerable collection type (IList<T>, T[], IReadOnlyList<T>, etc.)
        // MS.DI only supports automatic injection for IEnumerable<T>, other collection types need manual resolution
        // This check uses pre-computed IsNonEnumerableCollection from TypeData
        if(param.Type.IsNonEnumerableCollection)
        {
            WriteCollectionParameterResolution(writer, param, paramVar, isKeyedRegistration);
            return paramVar;
        }

        // Default: resolve from service provider
        var getServiceMethod = param.IsOptional ? "GetService" : "GetRequiredService";
        writer.WriteLine($"var {paramVar} = sp.{getServiceMethod}<{paramTypeName}>();");
        return paramVar;
    }

    /// <summary>
    /// Writes parameter resolution code for non-IEnumerable collection types.
    /// Converts IEnumerable&lt;T&gt; to the target collection type (IList&lt;T&gt;, T[], IReadOnlyList&lt;T&gt;, etc.).
    /// </summary>
    /// <param name="writer">The source writer.</param>
    /// <param name="param">The parameter data.</param>
    /// <param name="paramVar">The variable name for this parameter.</param>
    /// <param name="isKeyedRegistration">Whether this is a keyed service registration.</param>
    private static void WriteCollectionParameterResolution(
        SourceWriter writer,
        ParameterData param,
        string paramVar,
        bool isKeyedRegistration)
    {
        var paramType = param.Type;
        var elementType = paramType.TryGetEnumerableElementType();

        if(elementType is null)
        {
            // Fallback: couldn't determine element type, use direct service resolution
            var getServiceMethod = param.IsOptional ? "GetService" : "GetRequiredService";
            writer.WriteLine($"var {paramVar} = sp.{getServiceMethod}<{paramType.Name}>();");
            return;
        }

        var elementTypeName = elementType.Name;

        // Check if this is an array type (T[])
        if(paramType.Name.EndsWith("[]", StringComparison.Ordinal))
        {
            // Resolve as IEnumerable<T> and convert to array
            if(isKeyedRegistration)
            {
                writer.WriteLine($"var {paramVar} = sp.GetKeyedServices<{elementTypeName}>(key).ToArray();");
            }
            else
            {
                writer.WriteLine($"var {paramVar} = sp.GetServices<{elementTypeName}>().ToArray();");
            }
        }
        else
        {
            // For IList<T>, IReadOnlyList<T>, ICollection<T>, IReadOnlyCollection<T>, List<T>
            // Resolve as IEnumerable<T> and convert to List<T> which implements all these interfaces
            if(isKeyedRegistration)
            {
                writer.WriteLine($"var {paramVar} = sp.GetKeyedServices<{elementTypeName}>(key).ToList();");
            }
            else
            {
                writer.WriteLine($"var {paramVar} = sp.GetServices<{elementTypeName}>().ToList();");
            }
        }
    }

    /// <summary>
    /// Checks if the parameter is a service key parameter (object/object? named key or serviceKey).
    /// </summary>
    private static bool IsServiceKeyParameter(ParameterData param)
    {
        // Check if parameter type is object (with or without nullable)
        var typeName = param.Type.Name;
        if(typeName != "object" && typeName != "global::System.Object")
        {
            return false;
        }

        // Check if parameter name is "key" or "serviceKey" (case-insensitive)
        var paramName = param.Name;
        return paramName.Equals("key", StringComparison.OrdinalIgnoreCase)
            || paramName.Equals("serviceKey", StringComparison.OrdinalIgnoreCase);
    }

    /// <summary>
    /// Checks if the type name represents System.IServiceProvider.
    /// </summary>
    private static bool IsServiceProviderType(string typeName) =>
        typeName is "global::System.IServiceProvider" or "System.IServiceProvider" or "IServiceProvider";
}