namespace SourceGen.Ioc.SourceGenerator.Register;

/// <summary>
/// Generates code to register types marked with SourceGen.Ioc.IoCRegisterAttribute/SourceGen.Ioc.IoCRegisterForAttribute
/// in Microsoft.Extensions.DependencyInjection container.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed partial class RegisterSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // IoCRegisterAttribute
        var registerProvider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                Constants.IoCRegisterAttributeFullName,
                predicate: static (_, _) => true,
                transform: static (ctx, ct) => TransformRegister(ctx, ct))
            .Where(static m => m is not null)
            .Select(static (m, _) => m!)
            .Collect();

        // IoCRegisterForAttribute
        var registerForProvider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                Constants.IoCRegisterForAttributeFullName,
                predicate: static (_, _) => true,
                transform: static (ctx, ct) => TransformRegisterFor(ctx, ct))
            .SelectMany(static (m, _) => m)
            .Collect();

        // Combine all registration data
        var allRegistrations = registerProvider
            .Combine(registerForProvider)
            .Select(static (combined, _) =>
            {
                var (register, registerFor) = combined;
                return register.AddRange(registerFor);
            });

        // Default settings
        var defaultSettingsProvider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                Constants.IoCRegisterDefaultSettingsAttributeFullName,
                predicate: static (_, _) => true,
                transform: static (ctx, ct) => TransformDefaultSettings(ctx, ct))
            .SelectMany(static (m, _) => m)
            .Collect()
            .Select(static (settings, _) => new DefaultSettingsMap(settings));

        // Get compilation info
        var compilationInfo = context.CompilationProvider
            .Select(static (compilation, _) =>
            {
                var rootNamespace = compilation.AssemblyName ?? "Generated";
                return (RootNamespace: rootNamespace, AssemblyName: compilation.AssemblyName ?? "Generated");
            });

        // Combine registrations with default settings, generate service registrations
        var serviceRegistrations = allRegistrations
            .Combine(defaultSettingsProvider)
            .Select(static (source, ct) => GenerateServiceRegistrations(source.Left, source.Right, ct));

        // Combine service registrations with compilation info
        var combined = serviceRegistrations
            .Combine(compilationInfo);

        // Generate output
        context.RegisterSourceOutput(combined, static (ctx, source) =>
        {
            var (registrations, compilationInfo) = source;
            GenerateOutput(in ctx, registrations, compilationInfo.RootNamespace, compilationInfo.AssemblyName);
        });
    }

    private static void GenerateOutput(
        in SourceProductionContext ctx,
        ImmutableEquatableArray<ServiceRegistrationModel> registrations,
        string rootNamespace,
        string assemblyName)
    {
        if(registrations.Length == 0)
            return;

        // Generate source
        var source = GenerateExtensionMethodSource(registrations, rootNamespace, assemblyName);
        ctx.AddSource($"{assemblyName}.ServiceRegistration.g.cs", source);
    }

    private static string GenerateExtensionMethodSource(
        ImmutableEquatableArray<ServiceRegistrationModel> registrations,
        string rootNamespace,
        string assemblyName)
    {
        var writer = new SourceWriter();

        writer.WriteLine("// <auto-generated/>");
        writer.WriteLine("#nullable enable");
        writer.WriteLine();
        writer.WriteLine("using Microsoft.Extensions.DependencyInjection;");
        writer.WriteLine();

        writer.WriteLine($"namespace {GetSafeNamespace(rootNamespace)};");
        writer.WriteLine();

        var safeMethodName = GetSafeMethodName(assemblyName);
        writer.WriteLine("/// <summary>");
        writer.WriteLine($"/// Extension methods for registering services from {assemblyName}.");
        writer.WriteLine("/// </summary>");
        writer.WriteLine($"public static class {safeMethodName}ServiceCollectionExtensions");
        writer.WriteLine("{");
        writer.Indentation++;

        writer.WriteLine("/// <summary>");
        writer.WriteLine($"/// Registers all services from {assemblyName}.");
        writer.WriteLine("/// </summary>");
        writer.WriteLine($"public static IServiceCollection Add{safeMethodName}Services(this IServiceCollection services)");
        writer.WriteLine("{");
        writer.Indentation++;

        foreach(var registration in registrations)
        {
            WriteRegistration(writer, registration);
        }

        writer.WriteLine();
        writer.WriteLine("return services;");

        writer.Indentation--;
        writer.WriteLine("}");

        writer.Indentation--;
        writer.WriteLine("}");

        return writer.ToString();
    }

    private static void WriteRegistration(SourceWriter writer, ServiceRegistrationModel registration)
    {
        var lifetime = registration.Lifetime.Name;

        if(registration.IsOpenGeneric)
        {
            // Open generic registration requires typeof() syntax
            var serviceTypeOf = ConvertToTypeOf(registration.ServiceType, registration.ServiceTypeArity);
            var implTypeOf = ConvertToTypeOf(registration.ImplementationType, registration.ImplementationTypeArity);

            if(registration.Key != null)
            {
                writer.WriteLine($"services.AddKeyed{lifetime}({serviceTypeOf}, {registration.Key}, {implTypeOf});");
            }
            else
            {
                writer.WriteLine($"services.Add{lifetime}({serviceTypeOf}, {implTypeOf});");
            }
        }
        else if(registration.Key != null)
        {
            // Keyed registration
            writer.WriteLine($"services.AddKeyed{lifetime}<{registration.ServiceType}, {registration.ImplementationType}>({registration.Key});");
        }
        else
        {
            // Non-keyed registration
            writer.WriteLine($"services.Add{lifetime}<{registration.ServiceType}, {registration.ImplementationType}>();");
        }
    }

    /// <summary>
    /// Converts a fully qualified generic type name to typeof() syntax.
    /// For example: "global::Namespace.GenericTest&lt;T&gt;" becomes "typeof(global::Namespace.GenericTest&lt;&gt;)"
    /// </summary>
    private static string ConvertToTypeOf(string typeName, int arity)
    {
        // Find the generic part and replace type parameters with empty
        var startIndex = typeName.IndexOf('<');
        if(startIndex < 0)
        {
            return $"typeof({typeName})";
        }

        // Build the open generic typeof
        var baseName = typeName[..startIndex];
        var commas = arity > 1 ? new string(',', arity - 1) : "";
        return $"typeof({baseName}<{commas}>)";
    }
}
