namespace SourceGen.Ioc;

/// <summary>
/// Interface for IoC containers generated by SourceGen.Ioc.
/// Provides access to all registered services and their factory functions.
/// </summary>
public interface IIocContainer
{
    /// <summary>
    /// Gets all registered services with their composite keys and factory functions.
    /// The key is a tuple of (ServiceType, Key) where Key is <see cref="Microsoft.Extensions.DependencyInjection.KeyedService.AnyKey"/>
    /// for non-keyed services.
    /// </summary>
    IReadOnlyCollection<KeyValuePair<(Type ServiceType, object Key), Func<object>>> Services { get; }
}
