using Microsoft.Extensions.DependencyInjection;

namespace SourceGen.Ioc;

/// <summary>
/// Interface for IoC containers generated by SourceGen.Ioc.
/// Provides access to all registered services and their factory functions.
/// </summary>
/// <typeparam name="TContainer">The Container class itself.</typeparam>
public interface IIocContainer<TContainer> :
    IServiceProvider,
    ISupportRequiredService,
    IKeyedServiceProvider,
    IServiceProviderIsService,
    IServiceProviderIsKeyedService,
    IServiceScopeFactory,
    IDisposable,
    IAsyncDisposable
    where TContainer : IIocContainer<TContainer>
{
    /// <summary>
    /// Gets all resolvers with their composite keys and factory functions.<br/>
    /// The key is a <see cref="ServiceIdentifier"/> where Key is <see cref="KeyedService.AnyKey"/>
    /// for non-keyed services.<br/>
    /// The factory function takes the container instance and returns the resolver.
    /// </summary>
    public IReadOnlyCollection<KeyValuePair<ServiceIdentifier, Func<TContainer, object>>> Resolvers { get; }
}
