using Microsoft.Extensions.DependencyInjection;

namespace SourceGen.Ioc;

/// <summary>
/// Interface for IoC containers generated by SourceGen.Ioc.
/// Provides access to all registered services and their factory functions.
/// </summary>
/// <typeparam name="TContainer">The Container class itself.</typeparam>
public interface IIocContainer<TContainer> :
    IServiceProvider,
    ISupportRequiredService,
    IKeyedServiceProvider,
    IServiceProviderIsService,
    IServiceProviderIsKeyedService,
    IServiceScopeFactory,
    IDisposable,
    IAsyncDisposable
    where TContainer : IIocContainer<TContainer>
{
    /// <summary>
    /// Gets all registered services with their composite keys and factory functions.
    /// The key is a tuple of (ServiceType, Key) where Key is <see cref="KeyedService.AnyKey"/>
    /// for non-keyed services.
    /// The factory function takes the container instance and returns the service.
    /// </summary>
    IReadOnlyCollection<KeyValuePair<(Type ServiceType, object Key), Func<TContainer, object>>> Services { get; }
}
