global using System.Collections.Immutable;
global using System.Diagnostics;
global using System.Diagnostics.CodeAnalysis;
global using System.Text;
global using System.Linq;
global using Microsoft.CodeAnalysis;
global using Microsoft.CodeAnalysis.CSharp;
global using Microsoft.CodeAnalysis.CSharp.Syntax;
global using PolyType.Roslyn;
global using SourceGen.Ioc.SourceGenerator.Models;
global using static SourceGen.Ioc.SourceGenerator.RoslynExtensions;