name: SourceGen.Ioc AOT CI

on:
  workflow_dispatch:

  push:
    branches: [main]
    paths:
      - 'src/Ioc/src/SourceGen.Ioc/**'
      - 'src/Ioc/src/SourceGen.Ioc.SourceGenerator/**'
      - 'src/Ioc/test/SourceGen.Ioc.TestAot/**'
      - 'src/Ioc/test/SourceGen.Ioc.TestCase/**'
      - 'src/Ioc/test/Directory.Build.props'
      - 'src/Directory.Build.props'
      - 'Directory.Build.props'
      - 'Directory.Packages.props'
      - 'global.json'
      - '.github/workflows/ioc.aot.ci.yml'
  pull_request:
    branches: [main]
    paths:
      - 'src/Ioc/src/SourceGen.Ioc/**'
      - 'src/Ioc/src/SourceGen.Ioc.SourceGenerator/**'
      - 'src/Ioc/test/SourceGen.Ioc.TestAot/**'
      - 'src/Ioc/test/SourceGen.Ioc.TestCase/**'
      - 'src/Ioc/test/Directory.Build.props'
      - 'src/Directory.Build.props'
      - 'Directory.Build.props'
      - 'Directory.Packages.props'
      - 'global.json'
      - '.github/workflows/ioc.aot.ci.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  aot-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: Publish AOT
        run: dotnet publish src/Ioc/test/SourceGen.Ioc.TestAot/SourceGen.Ioc.TestAot.csproj -c Release -o ./publish-aot

      - name: Run AOT tests
        run: ./publish-aot/SourceGen.Ioc.TestAot
